### PR TITLE
docs(cli): clarify `stop` v. `terminate` with `Long` descriptions

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

Similar to #11625, this is another one of the most frequently asked questions by users and so could definitely use some clarification

### Modifications

- Following the same pattern as #11625, add a `Long` description to the CLI commands that details how `stop` and `terminate` work in more detail
  - via `make codegen`, this resulted in a `### Synopsis` section in the generated docs as well, which is also helpful
  
Descriptions loosely follow the official issue response in https://github.com/argoproj/argo-workflows/issues/4454#issuecomment-721821469.
This is effectively a follow-up to #4653

### Verification

- `make codegen` passes

### Notes for Reviewers

- I wrote this as a "fix" commit so that it can be added as a patch to the CLI (and make it into any cherry-picks), but could make it a "docs" commit instead.

- Feel free to add more modifications to the long descriptions!

### Future Work

I'd like to add these descriptions to the API docs as well, but that seems to be a larger effort as the API docs have _no_ descriptions right now 😕 I'm also not sure where codegen tries to pull the descriptions from, as there are GoDoc descriptions, but perhaps not in the right places?

### CODE REVIEW

**Comment by agilgur5** [comment]
Huh, lint [timed out](https://github.com/argoproj/argo-workflows/actions/runs/5913955535/job/16038915129?pr=11626). Haven't seen that happen before. Will need to retry that but may need to bump the timeout

**Review by isubasinghe — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Please fix lint

**Comment by agilgur5** [comment]
> Please fix lint

Per my comment [above](https://github.com/argoproj/argo-workflows/pull/11626#issuecomment-1685131400), it timed out and needs a retry

**Comment by agilgur5** [comment]
Looks like this is good to merge now

**Pull request merged**
