### PR TITLE
test: increase e2e timeout for ci

### PR DESCRIPTION
**Pull request by dpadhiar**
Currently, it is possible for multiple e2e test to fail when making pull requests when the code is not changed at all. we assume this is because the tests timeout with the current 15 minute threshold. We should increase this threshold to mitigate these intermittent failures to remove the need to rerun tests constantly until they all pass. We can also increase the Github action timeout in order to stop tests from simply cancelling when exceeding 20 minutes.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Has the build been passing stably though?

**Comment by dpadhiar** [comment]
> Has the build been passing stably though?

This is the first run I have done on Github since @juliev0 showed me we could adjust the Github action timeout. We could continue to manually rerun this PR to see if it has any random failures, we would also know if this solution works if we see how it affects PRs over the next day or so if it were to be merged.

**Comment by terrytangyuan** [comment]
I'd suggest we trigger empty commits with `--allow-empty` to see if this solves the problem consistently. Otherwise, we will need to bump timeout again.

**Comment by juliev0** [comment]
> I'd suggest pushing empty commits with `--allow-empty` and trigger the build to see if this solves the problem consistently. Otherwise, we will need to bump timeout again.

Hey Terry. @sarabala1979 and I talked about bumping it up to 25m for now. Ultimately, we need to address [this](https://github.com/argoproj/argo-workflows/issues/9024) issue that the tests are taking too long. But the current state of things seems to be pretty aggravating. I encountered this timeout issue twice in a row and then Dillen did as well.

**Review by juliev0 — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Sure happy to merge once it passes again.

**Review by terrytangyuan — APPROVED** [review]

**Comment by dpadhiar** [comment]
@terrytangyuan Had 1 fail so far but this looks like it wasn't related to any of the other intermittent failures at all.

**Comment by juliev0** [comment]
> Sure happy to merge once it passes again.

thank you!

**Pull request merged**
