### PR TITLE
docs: Fixed broken bash script when installing on macos

### PR DESCRIPTION
**Pull request by htquanq**
This is how I fixed bash script installing using cURL on my macbook.

### CODE REVIEW

**Review by MasonM — APPROVED** [review]
Thanks! The failing `DCO` check is because the commit wasn't signed off. You should be able to fix that with these commands:
```
git commit --signoff --amend
git push --force
```

**Review by terrytangyuan — APPROVED** [review]
LGTM once DCO check is fixed

**Comment by htquanq** [comment]
Hello guys, I have signed off commits

**Comment by saerdnaer** [comment]
The recent release note still have the same issue:

https://github.com/argoproj/argo-workflows/releases

image

**Comment by htquanq** [comment]
@saerdnaer could you open another issue for releases page? I updated the doc but look like the releases page, it need someone who has permission to edit

**Pull request merged**
