### PR TITLE
fix(ui): show container logs when using `templateRef`

### LINKED ISSUE #9938: Log Viewer Container list broken for workflows using templateRef
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Workflows that reference templates with "templateRef" rather than being defined in the same workflow fail to properly list containers in the log viewer UI. 

I have validated this with our own custom workflows as well as https://github.com/argoproj/argo-workflows/blob/master/examples/workflow-template/hello-world.yaml

I think is caused here: https://github.com/argoproj/argo-workflows/blob/master/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx#L87

Code permalink:
https://github.com/argoproj/argo-workflows/blob/v3.4.3/ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx#L87

### Version

v3.4.3, v3.3.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-whalesay-template
spec:
  entrypoint: whalesay-template
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    steps:
      - - name: call-whalesay-template
          templateRef:
            name: workflow-template-whalesay-template
            template: whalesay-template
          arguments:
            parameters:
            - name: message
              value: "hello world"
```

### Logs from the workflow controller

```
time="2022-11-01T18:09:38.511Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.611Z" level=info msg="Updated phase  -> Running" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.611Z" level=info msg="Steps node workflow-template-hello-world-wvw2x initialized Running" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.611Z" level=info msg="StepGroup node workflow-template-hello-world-wvw2x-1392490810 initialized Running" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.613Z" level=info msg="Pod node workflow-template-hello-world-wvw2x-2570399360 initialized Pending" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.746Z" level=info msg="Created pod: workflow-template-hello-world-wvw2x[0].call-whalesay-template (workflow-template-hello-world-wvw2x-whalesay-template-2570399360)" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.746Z" level=info msg="Workflow step group node workflow-template-hello-world-wvw2x-1392490810 not yet completed" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.746Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.746Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:38.775Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Running resourceVersion=4226961899 workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.755Z" level=info msg="Processing workflow" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.756Z" level=info msg="Task-result reconciliation" namespace=argo-workflows numObjs=0 workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.756Z" level=warning msg="workflow uses legacy/insecure pod patch, see https://argoproj.github.io/argo-workflows/workflow-rbac/" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.756Z" level=info msg="node changed" namespace=argo-workflows new.message= new.phase=Succeeded new.progress=0/1 nodeID=workflow-template-hello-world-wvw2x-2570399360 old.message= old.phase=Pending old.progress=0/1 workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="Step group node workflow-template-hello-world-wvw2x-1392490810 successful" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="node workflow-template-hello-world-wvw2x-1392490810 phase Running -> Succeeded" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="node workflow-template-hello-world-wvw2x-1392490810 finished: 2022-11-01 18:09:48.758518001 +0000 UTC" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="Outbound nodes of workflow-template-hello-world-wvw2x-2570399360 is [workflow-template-hello-world-wvw2x-2570399360]" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="Outbound nodes of workflow-template-hello-world-wvw2x is [workflow-template-hello-world-wvw2x-2570399360]" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="node workflow-template-hello-world-wvw2x phase Running -> Succeeded" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="node workflow-template-hello-world-wvw2x finished: 2022-11-01 18:09:48.758889979 +0000 UTC" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="Checking daemoned children of workflow-template-hello-world-wvw2x" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="TaskSet Reconciliation" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg=reconcileAgentPod namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.758Z" level=info msg="Marking workflow completed" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.759Z" level=info msg="Marking workflow as pending archiving" namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.760Z" level=info msg="Checking daemoned children of " namespace=argo-workflows workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.765Z" level=info msg="cleaning up pod" action=deletePod key=argo-workflows/workflow-template-hello-world-wvw2x-1340600742-agent/deletePod
time="2022-11-01T18:09:48.788Z" level=info msg="Workflow update successful" namespace=argo-workflows phase=Succeeded resourceVersion=4226962660 workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.803Z" level=info msg="archiving workflow" namespace=argo-workflows uid=cac4aad2-ff5d-418b-8230-407af6abf299 workflow=workflow-template-hello-world-wvw2x
time="2022-11-01T18:09:48.871Z" level=info msg="Queueing Succeeded workflow argo-workflows/workflow-template-hello-world-wvw2x for delete in 24h0m0s due to TTL"
time="2022-11-01T18:09:53.802Z" level=info msg="cleaning up pod" action=deletePod key=argo-workflows/workflow-template-hello-world-wvw2x-whalesay-template-2570399360/deletePod
```

### Logs from in your workflow's wait container

The workflow itself works fine.

### PR DESCRIPTION
**Pull request by agilgur5**
Fixes #9938
Related to #12970 -- that's for the back-end, this is the one remaining place in the front-end

### Motivation

- the component was incorrectly assuming that `node.templateName` exists, which it doesn't in the case of a `templateRef`

### Modifications

- use the existing `getTemplateNameFromNode` function to properly handle that instead

### Verification

Used the WorkflowTemplate and Workflow from the issue repro, can see all containers and logs.
<details><summary>Screenshot:</summary>

Screenshot 2024-04-23 at 9 11 37 PM

</details>

### CODE REVIEW

**Comment by agilgur5** [comment]
This should be backported to 3.4.x as well, since the bug has been around for a while

**Comment by ryancurrah** [comment]
This explains why I'm not seeing anything when viewing all logs.

**Comment by agilgur5** [comment]
> This explains why I'm not seeing anything when viewing all logs.

This makes you able to use the template combobox in the logs viewer per #9938, to clarify.

**Comment by ryancurrah** [comment]
It is.

**Review by tczhao — APPROVED** [review]

**Comment by agilgur5** [comment]
Merged `main` for new checks per #13027 

Going to merge this one in since Tianchu is Approver now per #13072 (and this is a simple UI patch and we have few UI SMEs other than me)

**Comment by wojtekkubiak** [comment]
I am using latest version v3.5.9 and there is error when trying to open Logs from UI: ReferenceError: getTemplateNameFromNode is not defined 
image

**Comment by agilgur5** [comment]
See #13415.

**Pull request merged**
