### PR TITLE
fix: Use v1 pod name if no template name or ref. Fixes #7595 and #7749

### LINKED ISSUE #7595: v3.2.6 Argo UI failed to render pod log
## Summary

What happened/what you expected to happen?
image-2022-01-19-22-04-27-808

What version of Argo Workflows are you running?
3.2.6 (we just upgrade it from 3.2.3 today, so I guess this issue might be introduced between 3.2.3 and 3.2.6. We'll try to roll back to 3.2.3 and see if this issue still exist)
## Diagnostics

I'm still not able to find a minimal reproducing example, since this issue only happened in some of our pipelines, and not sure which part of the template triggered this issue.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by JPZ13**
Signed-off-by: J.P. Zivalich <jp@pipekit.io>

This PR:
- Falls back to the v1 pod names in the UI if no templateName or templateRef is set on a given node - my hypothesis is that certain virtual nodes might not have a a templateName or templateRef set as seen here: https://github.com/argoproj/argo-workflows/issues/7595#issuecomment-1017776672
- Fixes #7595 

@liuzqt Could you run one of your workflows locally using this PR branch to test if it is working? I want to validate that I don't have to make an additional change to the workflow controller

### CODE REVIEW

**Comment by JPZ13** [comment]
@alexec - We don't yet have an example to reproduce #7595. Once we hear back from @liuzqt's team and have confirmed that this PR fixes their use case, I'll convert it from a draft to ready to review

**Comment by terrytangyuan** [comment]
@JPZ13 Do you have an image for them to test out? I am in touch of their team. Let me know if there’s any other information you need.

**Comment by terrytangyuan** [comment]
> > @JPZ13 Do you have an image for them to test out? I am in touch with their team. Let me know if there’s any other information you need.
> 
> Thanks @terrytangyuan - I cut three images and pushed them to our organization's docker registry since I don't have push access to the argoproj one. Here are the image tags:
> 
>     * `pipekit13/workflow-controller:fix-log-render-v1`
> 
>     * `pipekit13/argoexec:fix-log-render-v1`
> 
>     * `pipekit13/argocli:fix-log-render-v1`
> 
> 
> Let me know if they're able to run those or if they run into any issues

Thanks. We'll test it out.

**Comment by terrytangyuan** [comment]
> @terrytangyuan - have y'all had a chance to test these out yet?

Not yet. I'll check soon.

**Comment by JPZ13** [comment]
@alexec This PR fixes #7749. I hadn't had an example to test it with before, but I was able to test it with @Hunter-Thompson's example

**Review by alexec — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Thanks @JPZ13!

**Comment by JPZ13** [comment]
Any time, @terrytangyuan!

**Pull request merged**
