### PR TITLE
fix: Surface error during wait timeout for OSS artifact driver API calls

### PR DESCRIPTION
**Pull request by terrytangyuan**
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
can you please attach the outpt of your testing?

**Comment by terrytangyuan** [comment]
I was getting a `timed out waiting for the condition` error after the specified retries on transient errors but wasn't able to see the underlying error. Switching to use `wait.Backoff` will give me something like `timed out waiting for the condition: Failed to upload some parts with error: ConnectionTimeoutError: Connect timeout for 60000ms`.

**Comment by dinever** [comment]
This is great! 👍

**Comment by alexec** [comment]
@terrytangyuan can I confirm you tested each of the artifact drivers with their respective cloud providers? If not, can I suggest we break this into one PR per provider so they can be tested by the community?

**Review by alexec — CHANGES_REQUESTED** [review]
testing details requested

**Comment by terrytangyuan** [comment]
Unfortunately I cannot test for all the providers. I can change this to only modifying OSS artifact driver. 

Can I keep the minor refactoring of `DefaultRetry` in `workflow/artifacts/common/common.go` in the same PR though as the code would look much cleaner?

**Comment by alexec** [comment]
Maybe just refactor the OSS code? It is really easy to introduce bugs with retry, so it needs to be tested on actual provider

**Comment by terrytangyuan** [comment]
> Maybe just refactor the OSS code? It is really easy to introduce bugs with retry, so it needs to be tested on actual provider

Yep done!

**Pull request merged**
