### PR TITLE
refactor(ui): migrate `UserInfo` to functional component

### PR DESCRIPTION
**Pull request by agilgur5**
Partial fix for #9810 
Partial fix for #11740 

### Motivation

- Use newer, modern functional components compatible with hooks instead of legacy class-based components

- Use newer, modern async/await syntax instead of Promise chains

- also remove a deprecated usage of `BasePage`
  - `BasePage` is a deprecated usage of `react-router`'s private context before React made context an official API (it's quite old)
    - removing this is necessary to upgrade `react-router-dom` as the old, private context no longer exists in new versions
  - I'm also in process of migrating its remaining usages to functional components, this is one of a few PRs to do so (the others are _significantly_ more complex, so I have split them out. See #11794)

### Modifications

- mostly straightforward state refactor from `this.state` to `useState`
  - plus refactor `componentDidMount` to `useEffect`

- remove deprecated `BasePage` `extends` and typings
  - it wasn't even used in `UserInfo` (or at least not currently), so just removed references
    - no routing primitives are used in `UserInfo`

- plus remove unused `BasePage` methods
  - these are not used by anything at this time
    - searched the codebase and found 0 references

### Verification

- Pure refactor, no real semantic changes
- Manually tested locally that the UserInfo page works the same as it did before

### Notes for Reviewers

Turn on ["ignore whitespace"](https://github.com/argoproj/argo-workflows/pull/11793/files?w=1) to make the diff much simpler to read

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Can we merge similar PRs?

**Comment by agilgur5** [comment]
> Can we merge similar PRs?

At your previous request, I did. You picked the odd one out.

#11791 has 12 components and 27 files changed. They are all pure functional components or have very minimal state.
I mentioned there in the opening comment your previous request as well. 

This one has an effect, unlike all the rest in #11791.

Per my opening comment, I split out #11794 as it is _substantially_ more complex than any of the rest (and also took me _by far_ the longest to rewrite). It also follows the structure of an older PR closely for ease of review.

In any case, all 3 pass CI as there are significantly less flakes after #11753. They all merge cleanly as well. So at this point, it would also be unnecessary extra work to merge them together, especially when that makes the diff much worse and harder to review as well.

**Review by toyamagu-2021 — APPROVED** [review]
I've doublely checked functionality.
I should note `BasePage` can be removed finally after both report page and workflow-list page are migrated as @agilgur5  stated.
Refs:
* #11794
* https://github.com/argoproj/argo-workflows/issues/9810#issuecomment-1712944881

**Review by isubasinghe — APPROVED** [review]
LGTM

**Comment by agilgur5** [comment]
`BasePage` is finally gone with #11891 ! 🎉 
No more 6+ year old APIs! 😅

**Pull request merged**
