### PR TITLE
docs: Correct spelling of Daemoned

### PR DESCRIPTION
**Pull request by lrochette**
Also an explanation of the difference between errored and failed would be nice

Fixes #TODO

### CODE REVIEW

**Comment by lrochette** [comment]
Added explanation except for Daemoned

**Comment by alexec** [comment]
Do you think you could please fix the DCO/semantic builds?

**Comment by lrochette** [comment]
I'm not sure what you mean.
I changed a documentation file. No idea why it would break a build

**Comment by alexec** [comment]
Failed DCO builds:

https://github.com/argoproj/argo-workflows/pull/8029/checks?check_run_id=5368535126

**Comment by lrochette** [comment]
Done

**Comment by sarabala1979** [comment]
@lrochette can you resync from master?

**Comment by lrochette** [comment]
I thought I did. Will do again

**Comment by lrochette** [comment]
Done

**Review by alexec — APPROVED** [review]

**Pull request merged**
