### PR TITLE
chore: upgrade to k8s v0.20.4

### PR DESCRIPTION
**Pull request by uturunku1**
Checklist:

* [x ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Summary:
New Relic has a couple of services that require both Argo Workflows and ArgoCD dependencies in their go.mod. We would like to upgrade those services to use Argo Workflows v3.0.7 and ArgoCD v2.0.3 but the combination of those versions and their k8s dependencies generate some conflicts because Argo Workflows v3 is using k8s v0.19.6 and ArgoCD 2 is using k8s v0.20.4.
After experimenting with some local changes, upgrading Argo Workflows to use the same version of k8s as ArgoCD fixes our conflicts, and does not seem to disrupt our services from running as expected. 

I have also opened a PR for argo-events to upgrade those k8s dependencies: https://github.com/argoproj/argo-events/pull/1260

Locally, I have run `make codegen`, `lint` and `test` successfully but I am interested to get this repo's Github Workflows (ci-build.yaml) running to find out what my changes could have broken.

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
FYI you can convert the PR to draft instead of having "work in progress" in the title: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by alexec** [comment]
you'll also need to upgrade `argo-events`

**Comment by uturunku1** [comment]
Will do!

**Comment by uturunku1** [comment]
Let me know your thoughts on these changes: https://github.com/argoproj/argo-events/pull/1260

**Comment by uturunku1** [comment]
Hi! DCO continues to fail for me despite I ran `git rebase HEAD~93 --signoff` followed by `it push --force-with-lease origin upgrade-k8s-version` locally 😔. I noticed it also brought in a lot of other commits into my PR but I am guessing that is to be expected.
I pulled in my changes made to argo-events (https://github.com/argoproj/argo-events/pull/1260) into this PR, and I also made sure to run `make pre-commit -B` before my last commit to merge in master changes into this branch.

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
@jessesuen this needs a rubber stamp from you as proto code-owner.

**Pull request merged**
