### PR TITLE
feat(ui): allow to display date in absolute format

### PR DESCRIPTION
**Pull request by KillianHmyd**
Fixes #TODO

### CODE REVIEW

**Review by agilgur5 — CHANGES_REQUESTED** [review]
Please fill out the PR template. The "Motivation" section is particularly relevant here.
DCO is also missing from your commit.

There's also some bugs in the current code and this should apply on a much broader scale if implemented, see below in-line comments

**Comment by KillianHmyd** [comment]
@agilgur5 Sorry this was a draft not meant at all to be reviewed/shared for now 🙏🏾 
@JPZ13 You can go for it I won't work on it during the following week

**Comment by JPZ13** [comment]
Thanks @KillianHmyd - I really appreciate it

**Comment by agilgur5** [comment]
This was superseded by https://github.com/argoproj/argo-workflows/pull/13284

**Pull request closed without merging**
