### PR TITLE
feat: Display title and description in archived view

### LINKED ISSUE #10771: Display title and description annotations on workflow archive view
# Summary

In workflow archive view, display title and description if annotations exist

Related to #9805 which handles this for the main workflow view

Since we're already allowing it for the main workflow list, we should support it in the archive view also to give a consistent user experience IMO.

# Use Cases

When viewing the archive list, I'd want to see the titles/descriptions just like I would on the main workflow list

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by jmeridth**
Already working in normal workflow view via #9805

- create shared react component for workflow row name to dry up usage of this code in both normal and archive workflow lists
- add documentation regarding title and description annotations

Screenshot coming soon

Fixes #10771

### CODE REVIEW

**Comment by jmeridth** [comment]
Converting to draft because this isn't working yet.  The archive workflow service does not have much in regards to annotations.  UI is unchanged until the annotation can get to the new react component.  Screen shot also once I get this working locally.  Going to look at adding a test also.

**Comment by jmeridth** [comment]
archived workflows api doesn't allow for additional fields. This is gonna be interesting.

**Comment by jmeridth** [comment]
This will be affected by https://github.com/argoproj/argo-workflows/issues/10781

**Comment by terrytangyuan** [comment]
This will be impacted by https://github.com/argoproj/argo-workflows/pull/11121

**Comment by jmeridth** [comment]
@terrytangyuan 👍 yeah. I'm very excited about your changes. They will give the user a better experience.

**Pull request closed without merging**
