### PR TITLE
fix(log): change task set to task result.

### PR DESCRIPTION
**Pull request by shuangkun**
Log change.  task set -> task result

### CODE REVIEW

**Review by Joibel — APPROVED** [review]
LGTM

**Comment by shuangkun** [comment]
> LGTM

Thanks！

**Comment by agilgur5** [comment]
I edited this to a fix since this a pretty common log for new users, so the correction makes the log message more understandable

**Review by agilgur5 — APPROVED** [review]
Thanks for the correction

**Comment by agilgur5** [comment]
Backported to `release-3.5` as eec6ae0e4
- Fixed merge conflicts with the docs link since it's `release-3.5` on `release-3.5`

**Pull request merged**
