### PR TITLE
chore(deps): upgrade Cosign to v2.2.3

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Fixes #12828

### Motivation

Recently, Sigstore has published a new TUF trust root.

https://sigstore.slack.com/archives/C01DGF0G8U9/p1710871645742299
https://blog.sigstore.dev/tuf-root-update/

A new TUF trust root doesn't support Cosign v1.13.2, so we should upgrade Cosign to v1.13.6 or v2.

### Modifications

- Upgrade Cosign to v2
- Set the command line option `-y`

```
    -y, --yes=false:
	skip confirmation prompts for non-destructive operations
```

Without this option, `cosign sign` and `cosign sign-blob` don't work in CI.

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Is there any way to test the release workflow?

**Review by blkperl — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
> Is there any way to test the release workflow?

Not easily unfortunately -- I mentioned this in #12775 etc. The closest way would be to either run [`act`](https://github.com/nektos/act) locally or to run in your fork. But then you need to change the registries to your fork and respective secrets for those as well, which is a bit easier said than done.

Much of the release workflow runs on `main` though, and the merged commit did [pass on `main`](https://github.com/argoproj/argo-workflows/actions/runs/8487621676/job/23255637944)

**Comment by agilgur5** [comment]
> so we should upgrade Cosign to v1.13.6 or v2.

Cosign v2 should also upload the transparency log by default, which was previously experimental (see my comment https://github.com/argoproj/argo-workflows/discussions/12828#discussioncomment-8912855)

**Comment by agilgur5** [comment]
Cherry-picked into `release-3.5` as 43630bd8ec1207ee882295f47ba682aed8dde534

**Pull request merged**
