### PR TITLE
feat: add resubmit API for archived workflows. Fixes #7909

### LINKED ISSUE #7909: Add Resubmit API  on Archive workflow

### PR DESCRIPTION
**Pull request by dpadhiar**
Fixes #7909

Workflows currently can only be resubmitted if they exist on the cluster. If a workflow is GC-ed immediately after completion, you must save the workflow manually as a plain YAML or into workflow archive, then `kubectl create` before using `argo resubmit`. This API allows for archived workflows to be resubmitted removing the need for this otherwise hacky method.

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
PUT or POST?

**Comment by dpadhiar** [comment]
> PUT or POST?

Resubmit for workflow server is a PUT request so I assumed resubmitting from the archive should be the same.

**Comment by alexec** [comment]
> > PUT or POST?
> 
> Resubmit for workflow server is a PUT request so I assumed resubmitting from the archive should be the same. Since the workflow we are resubmitting has been deleted however, should we use a POST request instead?

Should be consistent. Whatever that is.

**Comment by tczhao** [comment]
Should we upgrade the UI part as well?
when using resubmit button from archive-workflow, use the new endpoint instead of the old method

**Review by alexec — APPROVED** [review]

**Pull request merged**
