### PR TITLE
feat: Parse JSON structured logs in Argo UI. Fixes #6856

### LINKED ISSUE #6856: Parse JSON structured logs in Argo UI
# Summary

When using FluentBit / FluentD, logs are written to stdout/stderr in a structured JSON format. It is difficult to read these easily in the Argo UI

# Use Cases

When clicking through to the node `main` logs, it would be nice to see only the `message` component of a JSON structured log/

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by isubasinghe**
Fixes #6856

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [ ] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Comment by isubasinghe** [comment]
Just revived @krrrr38's PR. Thanks @krrrr38 for your work.

**Review by juliev0 — APPROVED** [review]
neat!

**Comment by sarabala1979** [comment]
@isubasinghe Can you attach the screenshots for log viewer? before and after

**Comment by isubasinghe** [comment]
@sarabala1979 
Before (master branch):
image



After with filtering on other.showme
image

After without filtering:
image

**Review by alexec — CHANGES_REQUESTED** [review]
I will approve this once you fix the lint issue.

**Comment by alexec** [comment]
@isubasinghe question for you. I feel like you might find a few bugs in this that you need to fix afterwards. I've worked on similar feature and found a log tail of bugs that caused me to give up:

https://github.com/kubectl-logz/kubectl-logz

**Comment by isubasinghe** [comment]
@alexec Thanks for the heads up, I will test this manually a bit more in that case, regardless I will be working on Argo Workflows anyway so I should be able to squash these bugs when they do come up. 
Fixing merge conflict now.

**Comment by caelan-io** [comment]
Hi @alexec - @isubasinghe fixed the linter issue you highlighted. Can we please get your approval and merge when you have a moment? Thanks!

**Review by alexec — APPROVED** [review]

**Review by sarabala1979 — APPROVED** [review]
LGMT

**Pull request merged**
