### PR TITLE
docs: Add link to Killercoda interactive course

### PR DESCRIPTION
**Pull request by terrytangyuan**
cc @caelan-io @tico24

### CODE REVIEW

**Review by caelan-io — APPROVED** [review]
Thanks for updating! I forgot this link was in here.

**Comment by tico24** [comment]
> I forgot this link was in here.

it wasn't :)

**Review by tico24 — APPROVED** [review]

**Comment by caelan-io** [comment]
Ah, okay. I was thinking of training.md but looks like you already updated that 🙌

**Review by agilgur5 — COMMENTED** [review]
We should probably add this to `docs/README.md` too right?

**Comment by terrytangyuan** [comment]
Adding in https://github.com/argoproj/argo-workflows/pull/12417

**Pull request merged**
