### PR TITLE
fix: git clone on non-default branch fails (Fixes #5629)

### LINKED ISSUE #5629: Git Clone Fails if Revision is `refs/heads/*`
## Summary 

If a GitArtifact revision is of the form `refs/heads/*`, this error will occur (logs from `init` container):
```
time="2021-04-08T16:42:29.332Z" level=info msg="Loading script source to /argo/staging/script"
time="2021-04-08T16:42:29.332Z" level=info msg="Start loading input artifacts..."
time="2021-04-08T16:42:29.332Z" level=info msg="Downloading artifact: git-source"
time="2021-04-08T16:42:30.386Z" level=info msg="Checking out revision refs/heads/push-test"
time="2021-04-08T16:42:30.389Z" level=error msg="`[git checkout refs/heads/push-test]` stderr:\nerror: pathspec 'refs/heads/push-test' did not match any file(s) known to git\n"
time="2021-04-08T16:42:30.389Z" level=error msg="executor error: error: pathspec 'refs/heads/push-test' did not match any file(s) known to git"
time="2021-04-08T16:42:30.389Z" level=info msg="Alloc=5707 TotalAlloc=16500 Sys=71104 NumGC=6 Goroutines=4"
time="2021-04-08T16:42:30.416Z" level=fatal msg="error: pathspec 'refs/heads/push-test' did not match any file(s) known to git"
```

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: "git-clone-test"
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
        - name: repoOwner
          default: argoproj
        - name: repoName
          default: argo-workflows
        - name: gitRef
          default: refs/heads/release-2.0
      artifacts:
        - name: git-repo
          path: /tmp/src
          git:
            repo: "git@github.com:{{inputs.parameters.repoOwner}}/{{inputs.parameters.repoName}}.git"
            revision: "{{inputs.parameters.gitRef}}"
            depth: 1
            sshPrivateKeySecret:
              name: "cid-workflows-secrets"
              key: GITHUB_PRIVATE_REGISTRY_PULL_PRIVATE_KEY
    outputs:
      artifacts:
        - name: repository
          path: /tmp/src
    script:
      image: alpine:latest
      workingDir: /tmp/src
      command: [/bin/sh]
      env:
        - name: GIT_REF
          value: "{{inputs.parameters.gitRef}}"
      source: |
        echo "Successfully cloned {{inputs.parameters.repoOwner}}/{{inputs.parameters.repoName}} at {{inputs.parameters.gitRef}}"
```

```
argo submit ./clone-test.yaml --watch
Name:                git-clone-test8p5nq
Namespace:           argo
ServiceAccount:      argo-workflow
Status:              Error
Message:             failed to load artifacts: error: pathspec 'refs/heads/release-2.0' did not match any file(s) known to git
Conditions:          
 Completed           True
Created:             Thu Apr 08 11:58:30 -0500 (20 seconds ago)
Started:             Thu Apr 08 11:58:30 -0500 (20 seconds ago)
Finished:            Thu Apr 08 11:58:50 -0500 (now)
Duration:            20 seconds
Progress:            1/1
ResourcesDuration:   7s*(1 cpu),7s*(100Mi memory)

STEP                    TEMPLATE  PODNAME              DURATION  MESSAGE
 ⚠ git-clone-test8p5nq  main      git-clone-test8p5nq  10s       failed to load artifacts: error: pathspec 'refs/heads/release-2.0' did not match any file(s) known to git  
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kennytrytek**
- Fixes Issue 5629.

Signed-off-by: Kenny Trytek <kenneth.g.trytek@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by kennytrytek** [comment]
I don't think this change should cause catastrophic failure of the tests. Closing/reopening to try again...

**Comment by alexec** [comment]
Can you please add a test?

**Review by alexec — CHANGES_REQUESTED** [review]
.

**Comment by kennytrytek** [comment]
> @alexec:
> Can you please add a test?

Added test to verify the revision used is in the expected format. A full e2e test seemed a bit heavy for this change.

**Review by alexec — APPROVED** [review]

**Comment by kennytrytek-wf** [comment]
Rebased onto latest master. No merge conflicts.

**Comment by kennytrytek** [comment]
Rebased onto latest master. No merge conflicts.

**Comment by alexec** [comment]
Please fix lint.

**Review by alexec — APPROVED** [review]

**Comment by kennytrytek** [comment]
Sorry, didn't realize there was a `lint` target locally; I'll be sure to do that before pushing for future changes.

**Comment by alexec** [comment]
Test unrelated to changes failed:

```
--- FAIL: TestDAGTemplateParallelismLimit (0.11s)
    operator_test.go:1519: 
        	Error Trace:	operator_test.go:1519
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 4
        	Test:       	TestDAGTemplateParallelismLimit
```

Re-running build.

**Pull request merged**
