### PR TITLE
chore: move documentation to readthedocs

### LINKED ISSUE #11390: Versioned documentation
# Summary

Adding versioning to argo-workflows docs https://argoproj.github.io/argo-workflows/

# Use Cases

When searching docs for the specific version of argo workflows you have deployed

Currently argo-cd has versioning in their documentation. Was introduced with [this PR](https://github.com/argoproj/argo-cd/pull/5099)

Would require setup and then migration/rewriting of docs to have docs split by version. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by jmeridth**
Yes.  I'm aware of the size of this change.  I cringed also. One must hunt down all URLs and change them. :smile:

I'm aware that the url [argo-workflows.readthedocs.io](http://argo-workflows.readthedocs.io/en/stable/) doesn't work yet.  Coordinating with maintainers to wire-up the webhook on this repo so we can get the first version of the docs setup.

Fixes #11390

### Motivation

Moving to readthedocs so we can have versioned docs easily and standardize like argo-cd and other projects have already.

### Modifications

- [x] add .readthedocs.yml
- [x] add docs/requirements.txt
- [x] update urls in code
  - [x] sdk and other files updates were from `make pre-commit -B` locally
- [x] update .spelling with words to exlude during spellcheck
- [x] delete docs GitHub action
  - [x] update gh-pages branch with fixed index.html linking to new url #12212

### CODE REVIEW

**Comment by Joibel** [comment]
Appreciate you pushing this forward @jmeridth, long overdue. I can't see anything wrong with it. Why are the `.spelling` changes needed, what causes them to be detected now but not in the older version?

**Comment by jmeridth** [comment]
> Appreciate you pushing this forward @jmeridth, long overdue. I can't see anything wrong with it. Why are the `.spelling` changes needed, what causes them to be detected now but not in the older version?

@Joibel great question.  I do not know currently.  But couldn't get pase `make pre-commit -B` until I added those values.  Will look at why not previously detected.

**Comment by jmeridth** [comment]
After talking with @terrytangyuan I'm going to point a temp readthedocs at a fork of this repo to ensure the docs render as we like so we can make the cutover with this PR and have all the pieces in place.  Testing that today.

**Comment by jmeridth** [comment]
Closing temporarily to prevent workflows firing off.  I'm testing in my fork.  will reopen once satisfied.

**Comment by agilgur5** [comment]
Replaced by #12360

**Pull request closed without merging**
