### PR TITLE
chore: Remove docker executor

### LINKED ISSUE #7795: Remove the deprecated `docker` executor
Remove the executor code. Remove `docker` binary from executor.

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes #7795. 

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by blkperl** [comment]
@terrytangyuan There are more references to `ContainerRuntimeExecutorDocker` in multiple files. Specifically, `workflow/controller/workflowpod.go` has a lot of code related to the docker socket that can be removed

**Comment by alexec** [comment]
Search for docker.sock?

**Comment by blkperl** [comment]
@terrytangyuan https://github.com/terrytangyuan/argo-workflows/blob/rm-docker/workflow/controller/workflowpod.go#L587

**Comment by terrytangyuan** [comment]
Done. Let me know if I missed anything else.

**Comment by rohankmr414** [comment]
There are some quickstarts for docker executor in `manifests/quick-start/base/executor`.

**Review by alexec — APPROVED** [review]

**Pull request merged**
