### PR TITLE
docs(ui): full copy-edit of title & description page

### PR DESCRIPTION
**Pull request by agilgur5**
Partial fix for https://github.com/argoproj/argo-workflows/pull/10553#pullrequestreview-1799370952 -- this fixes the docs & example issues, while #12580 fixes the UI issues

### Motivation

<details> <summary>Significantly improve the "Title and Description" page (and related example) from #10553 </summary>

- It was missing version specifiers (as was the example)
- It only showed the markdown variant, but the non-markdown variant actually existed earlier after #9805 (released in [v3.4.4](https://github.com/argoproj/argo-workflows/blob/v3.5.4/CHANGELOG.md#v344-2022-11-28))
- It only had one complex example, and not simple examples
- Complex example had verbal descriptions, but not the raw code
- The example image's alt `title` was not very accessible
- Had an outdated link to Couler
- Had a few k8s docs style guide issues
- Had a few typos
- Had a markdown issue
- etc

</details>

### Modifications

- <details> <summary>split the page into sections with and without markdown </summary>
 
  - add a non-markdown example and description
  - add a simple markdown example of just one row
  - use the same width images for both of these examples for visual consistency with the larger example
 
 </details>
 
- add version specifiers to both of these sections

- link to markdown docs when referencing Markdown
- <details> <summary>improve example descriptions </summary>

  - fix missing end parenthesis
  - be more specific, for instance, one of the examples is multi-line

</details>

- <details> <summary>instead of having loose descriptions of rows in a list, actually write out the (partial) manifest that results in those renderings </summary> 

  - I "reverse-engineered" what they would be based on the image
  - remove extra / duplicated example at the end (?)
  - use one code block instead of multiple to make it easier to read

</details>

<details> <summary> accessibility improvements: </summary>

- better describe the example image(s), specify that they are examples
  - previously, it just said "Workflow Title and Description", which would not really explain the image for someone using a screen reader, as that's the same as the title of the page

</details>

<details> <summary>prose style improvements: </summary>

- use present tense and active voice, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-present-tense)
- be more simple and direct, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
- avoid jargon / idioms, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-jargon-and-idioms)
  - "auto turn" -> "convert"
- be specific, instead of "title and description annotations", specify what the annotations are

</details>

<details> <summary> markdown style improvements: </summary>

- use ordered list when a list is ordered, instead of an unordered one

</details>

<details> <summary>example improvements: </summary>

- fix typo in the file name
- add version specifier like other examples
- don't link to Couler, as it's been unmaintained for some time
  - instead link to these docs themselves -- a link this repo controls and a self reference
  - couldn't do that with the in-line example because I'd need to make a new image to correspond with that

</details>

### Verification

1. `make docs`
1. `open site/title-and-description/index.html`
1. <details> <summary>Took screenshots:</summary>

    Screenshot 2024-01-28 at 5 14 28 PM
    Screenshot 2024-01-28 at 5 14 50 PM

</details>

### Future Work

Backport the non-markdown variant to the `release-3.5` and `release-3.4` branches
- I didn't even know this feature existed, docs would be great for previous versions

### CODE REVIEW

**Review by jmeridth — APPROVED** [review]
I like it. File was misspelled. Lol. Good catch.

**Comment by agilgur5** [comment]
Fixed codegen due to the filename typo

**Review by jmeridth — APPROVED** [review]

**Comment by agilgur5** [comment]
The missing version specifier popped up [on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1707932566476279), so hoping this can get an Approver+ soon

**Comment by agilgur5** [comment]
Another user [confused on Slack](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1708516960529079?thread_ts=1708516515.666799&cid=C01QW9QSSSK) by lack of version specifier...

**Review by juliev0 — APPROVED** [review]

**Comment by agilgur5** [comment]
> ### Future Work
> Backport the non-markdown variant to the `release-3.5` and `release-3.4` branches
> 
> * I didn't even know this feature existed, docs would be great for previous versions

Backported the non-markdown docs to `release-3.5` in a34d98965dce25c002bab3a48431d13c91cb78f8.
In particular, this was something I was reminded of during the [previous Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.5a2asxhc64ss) where I went to this page on `latest` docs and compared it to `release-3.5` docs only for it to not work

**Comment by agilgur5** [comment]
And once more to `release-3.4` in 4a521a5cb1fdd13dbc5d90b52db1831708d71284

**Pull request merged**
