### PR TITLE
feat: Support argo plugin stop. Fixes #12333

### LINKED ISSUE #12333: Can't stop a workflow, when this workflow uses a plugins
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

I wrote a plugin DEMO to simulate a time -consuming task. Now I hope to stop the execution of the plug -in through the stop command of the WF. But I found that the plug -in now cannot receive the instruction of WF at all

The following is my plugin configmap： `plugin/hello-executor-plugin-configmap.yaml`
```
# This is an auto-generated file. DO NOT EDIT
apiVersion: v1
data:
  sidecar.automountServiceAccountToken: "false"
  sidecar.container: |
    args:
    - |
      import json
      import random
      import time
      from http.server import BaseHTTPRequestHandler, HTTPServer


      class Plugin(BaseHTTPRequestHandler):

          def args(self):
              return json.loads(self.rfile.read(int(self.headers.get('Content-Length'))))

          def reply(self, reply):
              self.send_response(200)
              self.end_headers()
              self.wfile.write(json.dumps(reply).encode("UTF-8"))

          def forbidden(self):
              self.send_response(403)
              self.end_headers()

          def unsupported(self):
              self.send_response(404)
              self.end_headers()

          def do_POST(self):
              print("=======================================")
              print("self.path: ", self.path)
              if self.path == '/api/v1/template.execute':
                  args = self.args()
                  random_num = random.randint(1, 10)
                  print("random_num: ", random_num)
                  print(args)
                  if 'hello' in args['template'].get('plugin', {}):
                      if random_num > 0:
                          self.reply(
                              {
                                  "node": {
                                      "phase": "Running",
                                      "message": "Long-running task started"
                                  },
                                  "requeue": "5m"
                              }
                          )
                      else:
                          self.reply(
                              {
                                  "node": {
                                      "phase": "Succeeded",
                                      "message": "finish job~~~"
                                  }
                              }
                          )
                  else:
                      self.reply({})
              else:
                  self.unsupported()


      if __name__ == '__main__':
          httpd = HTTPServer(('', 4355), Plugin)
          httpd.serve_forever()
    command:
    - python
    - -u
    - -c
    image: python:alpine3.6
    name: hello-executor-plugin
    ports:
    - containerPort: 4355
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 250m
        memory: 64Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
  name: hello-executor-plugin
```

Here I simulate the user to terminate the workflow， But my plugin cannot accept this instruction。

image

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
argo executor-plugin build plugin/.
kubectl -n argo apply -f  plugin/hello-executor-plugin-configmap.yaml
argo submit -n argo plugin-hello.yaml --watch --serviceaccount default
argo terminate hello-25wjm
```

### Logs from the workflow controller

```text
time="2023-12-08T10:34:07.212Z" level=info msg=assessAgentPodStatus namespace=argo podName=hello-7wwcp-1340600742-agent

 time="2023-12-08T10:34:07.212Z" level=error msg="was unable to obtain node for hello-7wwcp-2166136261" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:07.212Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:07.212Z" level=info msg="Creating TaskSet" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:12.333Z" level=warning msg="Waited for 5.120860946s, request: Create:https://10.233.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/workflowtasksets"

 time="2023-12-08T10:34:12.545Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:12.545Z" level=info msg=updateAgentPodStatus namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:12.545Z" level=info msg=assessAgentPodStatus namespace=argo podName=hello-7wwcp-1340600742-agent

 time="2023-12-08T10:34:12.545Z" level=info msg="Workflow to be dehydrated" Workflow Size=895

 time="2023-12-08T10:34:12.572Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=117253554 workflow=hello-7wwcp

 time="2023-12-08T10:34:22.573Z" level=info msg="Processing workflow" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:22.574Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=hello-7wwcp

 time="2023-12-08T10:34:22.574Z" level=info msg=updateAgentPodStatus namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:22.574Z" level=info msg=assessAgentPodStatus namespace=argo podName=hello-7wwcp-1340600742-agent

 time="2023-12-08T10:34:22.574Z" level=error msg="was unable to obtain node for hello-7wwcp-2166136261" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:22.574Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:22.574Z" level=info msg="Creating TaskSet" namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:23.102Z" level=info msg=reconcileAgentPod namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:23.102Z" level=info msg=updateAgentPodStatus namespace=argo workflow=hello-7wwcp

 time="2023-12-08T10:34:23.102Z" level=info msg=assessAgentPodStatus namespace=argo podName=hello-7wwcp-1340600742-agent

 time="2023-12-08T10:34:23.103Z" level=info msg="Workflow to be dehydrated" Workflow Size=895

 time="2023-12-08T10:34:23.108Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=117253580 workflow=hello-7wwcp

 time="2023-12-08T10:38:33.967Z" level=info msg="Alloc=6957 TotalAlloc=232719 Sys=30565 NumGC=110 Goroutines=177"
```

### Logs from in your workflow's wait container

```text
no wait container。

plugin container：
 =======================================

 self.path:  /api/v1/template.execute

 random_num:  4

 {'workflow': {'metadata': {'name': 'hello-7wwcp', 'namespace': 'argo', 'uid': '5ecf8bbe-8027-4999-8b4a-c84f8ac9fc17'}}, 'template': {'name': 'hello', 'inputs': {}, 'outputs': {}, 'metadata': {}, 'plugin': {'hello': {'jobName': 'iosBuild', 'jobParams': {'param1': 'value1', 'param2': 'value2'}}}}}

 127.0.0.1 - - [08/Dec/2023 10:30:40] "POST /api/v1/template.execute HTTP/1.1" 200 -

 =======================================

 self.path:  /api/v1/template.execute

 random_num:  4

 {'workflow': {'metadata': {'name': 'hello-7wwcp', 'namespace': 'argo', 'uid': '5ecf8bbe-8027-4999-8b4a-c84f8ac9fc17'}}, 'template': {'name': 'hello', 'inputs': {}, 'outputs': {}, 'metadata': {}, 'plugin': {'hello': {'jobName': 'iosBuild', 'jobParams': {'param1': 'value1', 'param2': 'value2'}}}}}

 127.0.0.1 - - [08/Dec/2023 10:35:40] "POST /api/v1/template.execute HTTP/1.1" 200 -

 =======================================

 self.path:  /api/v1/template.execute

 random_num:  4

 {'workflow': {'metadata': {'name': 'hello-7wwcp', 'namespace': 'argo', 'uid': '5ecf8bbe-8027-4999-8b4a-c84f8ac9fc17'}}, 'template': {'name': 'hello', 'inputs': {}, 'outputs': {}, 'metadata': {}, 'plugin': {'hello': {'jobName': 'iosBuild', 'jobParams': {'param1': 'value1', 'param2': 'value2'}}}}}

 127.0.0.1 - - [08/Dec/2023 10:40:40] "POST /api/v1/template.execute HTTP/1.1" 200 -

 =======================================

 self.path:  /api/v1/template.execute

 random_num:  5

 {'workflow': {'metadata': {'name': 'hello-7wwcp', 'namespace': 'argo', 'uid': '5ecf8bbe-8027-4999-8b4a-c84f8ac9fc17'}}, 'template': {'name': 'hello', 'inputs': {}, 'outputs': {}, 'metadata': {}, 'plugin': {'hello': {'jobName': 'iosBuild', 'jobParams': {'param1': 'value1', 'param2': 'value2'}}}}}

 127.0.0.1 - - [08/Dec/2023 10:45:40] "POST /api/v1/template.execute HTTP/1.1" 200 -
```

### PR DESCRIPTION
**Pull request by GhangZh**
Fixes [#12333](https://github.com/argoproj/argo-workflows/issues/12333)

### Motivation

When using the argo plugin, I found that it doesn't have a stop function
### Modifications

When stopping workflow, mark plugin node as failed. and then skips the taskset update, preventing taskset from updating the node state again.

### CODE REVIEW

**Review by sarabala1979 — APPROVED** [review]
LGTM

**Comment by agilgur5** [comment]
I think this also requires some changes to the plugin spec, no? As plugins can't currently respond to `stop` requests per #10476

**Comment by jswxstw** [comment]
> I think this also requires some changes to the plugin spec, no? As plugins can't currently respond to `stop` requests per #10476

The agent pod will be cleaned up when the workflow comes to completed status, so additional changes may be unnecessary I think.

**Comment by agilgur5** [comment]
> The agent pod will be cleaned up when the workflow comes to completed status, so additional changes may be unnecessary I think.

It might not be able to _gracefully_ stop though

**Comment by jswxstw** [comment]
> > The agent pod will be cleaned up when the workflow comes to completed status, so additional changes may be unnecessary I think.
> 
> That's a good point. It might not be able to _gracefully_ stop though

Yes, when stopping the workflow, there is both 30s by default to allow the pod to stop gracefully.
So, the default behavior of `terminateContainers` and `delete` pod clean up policy may be the same.

**Comment by agilgur5** [comment]
> So, the default behavior of `terminateContainers` and `delete` pod clean up policy may be the same.

Oh, if it's only causing a `SIGTERM` and nothing else, then yes, that would indeed be the same and would simplify things

**Pull request merged**
