### PR TITLE
fix: relative submodules in git artifacts. Fixes #7141

### LINKED ISSUE #7141: Git Artifact does not support relative submodules (fixed in go-git v5.3.0)
## Summary

Using GitArtifact to clone a Git repository with a submodule specified as a relative path, argoexec init fails with `executor error: repository not found`.

The error comes from go-git (my guess would be [during the initial clone](https://github.com/argoproj/argo-workflows/blob/master/workflow/artifacts/git/git.go#L127)). See 

As mentioned there, it has been fixed in [v5.3.0](https://github.com/go-git/go-git/releases/tag/v5.3.0.).

## Diagnostics

You can use the following workflow to reproduce. It tries to clone [this example repo](https://github.com/valorl/repository-with-relative-submodule) to which I added a submodule with a relative path (`../argo-workflows`).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: clone-relative-submodule
spec:
  entrypoint: clone
  templates:
  - name: clone
    inputs:
      artifacts:
      - name: repo
        path: /repo
        git:
          repo: https://github.com/valorl/repository-with-relative-submodule.git
          revision: main
    script:
      image: alpine/git:latest
      command: [sh]
      workingDir: /repo
      source: |
        git status
```
For me on 3.0.7, this results in the following error in init log:
```
time="2021-11-03T13:40:45.372Z" level=info msg="Starting Workflow Executor" version="{v3.0.7 2021-05-25T19:03:05Z e79e7ccda747fa4487bf889142c744457c26e9f7 v3.0.7 clean go1.15.7 gc linux/amd64}"
time="2021-11-03T13:40:45.375Z" level=info msg="Creating a docker executor"
time="2021-11-03T13:40:45.375Z" level=info msg="Executor (version: v3.0.7, build_date: 2021-05-25T19:03:05Z) initialized (pod: ci-main/clone-relative-submodule) with template:\n{\"name\":\"clone\",\"inputs\":{\"artifacts\":[{\"name\":\"repo\",\"path\":\"/repo\",\"git\":{\"rep
o\":\"github.com/valorl/repository-with-relative-submodule\",\"revision\":\"main\"}}]},\"outputs\":{},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"alpine/git:latest\",\"command\":[\"sh\"],\"workingDir\":\"/repo\",\"resources\":{},\"source\":\"git status\\n\"},\"archi
veLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"*****\",\"region\":\"*****\",\"insecure\":false,\"useSDKCreds\":true,\"key\":\"*****\"}}}"
time="2021-11-03T13:40:45.375Z" level=info msg="Loading script source to /argo/staging/script"
time="2021-11-03T13:40:45.375Z" level=info msg="Start loading input artifacts..."
time="2021-11-03T13:40:45.375Z" level=info msg="Downloading artifact: repo"
time="2021-11-03T13:40:45.377Z" level=error msg="executor error: repository not found"
time="2021-11-03T13:40:45.377Z" level=info msg="Alloc=4721 TotalAlloc=8931 Sys=73297 NumGC=3 Goroutines=3"
time="2021-11-03T13:40:45.377Z" level=fatal msg="repository not found"
```

What Kubernetes provider are you using?
EKS

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Docker

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by valorl**
Upgrades src-d/go-git v4 to go-git/go-git v5.3.0.
See https://github.com/go-git/go-git/pull/195.

Signed-off-by: valorl <11498571+valorl@users.noreply.github.com>

# Testing
Built and ran locally and tried to reproduce with the example Workflow from #7141. This time it clone the repo successfully.

## Workflow
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: clone-relative-submodule
spec:
  entrypoint: clone
  templates:
  - name: clone
    inputs:
      artifacts:
      - name: repo
        path: /repo
        git:
          repo: https://github.com/valorl/repository-with-relative-submodule.git
          revision: main
    script:
      image: alpine/git:latest
      command: [sh]
      workingDir: /repo
      source: |
        git status
```

## Output
```
time="2021-11-04T09:47:01.581Z" level=info msg="Starting Workflow Executor" executorType=emissary version=untagged
time="2021-11-04T09:47:01.584Z" level=info msg="Creating a emissary executor"
time="2021-11-04T09:47:01.584Z" level=info msg="Executor initialized" deadline="2021-11-04 09:52:00 +0000 UTC" includeScriptOutput=false namespace=argo podName=clone-relative-submodule-6lr46 template="{\"name\":\"clone\",\"inputs\":{\"artifacts\":[{\"name\":\"repo\",\"path\":\"/repo\",\"git\":{\"repo\":\"https://github.com/valorl/repository-with-relative-submodule.git\",\"revision\":\"main\"}}]},\"outputs\":{},\"metadata\":{},\"script\":{\"name\":\"\",\"image\":\"alpine/git:latest\",\"command\":[\"sh\"],\"workingDir\":\"/repo\",\"resources\":{},\"source\":\"git status\\n\"},\"archiveLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"minio:9000\",\"bucket\":\"my-bucket\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"my-minio-cred\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"my-minio-cred\",\"key\":\"secretkey\"},\"key\":\"clone-relative-submodule-6lr46/clone-relative-submodule-6lr46\"}}}" version="&Version{Version:untagged,BuildDate:2021-11-04T09:37:37Z,GitCommit:b7e4bda9bad2c830dc5f6ef57e42522876e47bfd,GitTag:untagged,GitTreeState:clean,GoVersion:go1.17.2,Compiler:gc,Platform:linux/amd64,}"
time="2021-11-04T09:47:01.629Z" level=info msg="Loading script source to /argo/staging/script"
time="2021-11-04T09:47:01.629Z" level=info msg="Start loading input artifacts..."
time="2021-11-04T09:47:01.629Z" level=info msg="Downloading artifact: repo"
time="2021-11-04T09:49:22.948Z" level=info msg="Checking out revision main"
time="2021-11-04T09:49:23.527Z" level=info msg="`[git checkout main]` stdout:\nYour branch is up to date with 'origin/main'.\n"
time="2021-11-04T09:49:23.788Z" level=info msg="`[git checkout main]` stdout:\nSubmodule path 'argo-workflows': checked out '9293512674c21a2494c704978990cf89eb5ad8c0'\n"
time="2021-11-04T09:49:23.788Z" level=info msg="Detecting if /argo/inputs/artifacts/repo.tmp is a tarball"
time="2021-11-04T09:49:23.789Z" level=info msg="Successfully download file: /argo/inputs/artifacts/repo"
time="2021-11-04T09:49:23.791Z" level=info msg="Alloc=84748 TotalAlloc=5309165 Sys=531815 NumGC=55 Goroutines=3"
```

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
LGTM. Are you aware of any changes that might affect existing users since this is a major version update for go-git?

**Comment by valorl** [comment]
Based on this comment from the project, there shouldn't be any breaking changes going from 4 to 5.
> The new version and all future versions in v5 branch can be used as a drop-in replacement for v4. This major update was required due to the new project home at go-git org and the full adoption of go modules.​

https://github.com/go-git/go-git/wiki/go-git-has-a-new-home!-v5-and-some-explanations

**Review by terrytangyuan — APPROVED** [review]
Sounds good. Thank you!

**Comment by Hunter-Thompson** [comment]
This upgrade might have been responsible for #7736

**Pull request merged**
