### PR TITLE
feat: Support loading manifest from artifacts for resource templates. Fixes #5878

### LINKED ISSUE #5878: Creating A Resource Using Git Artifact
## Summary 

I have a workflow with 2 steps. The first is simply doing a git clone in order to create a git artifact. The repository I clone has a workflow yaml in it. I then want to use the workflow yaml in the next step, where I have a resource template. That is, the resource template should create the workflow which was in the git repo cloned in step 1! 

## Diagnostics

What Kubernetes provider are you using? GKE

What version of Argo Workflows are you running? 3.0.1

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: possible-bug-
spec:
  entrypoint: all-steps
  templates:
  - name: all-steps
    steps:
    - - name: step-1-create-git-artifact
        template: git-clone 
    - - name: step-2-create-workflow
        template: create-resource
        arguments:
          parameters:
          - name: resource-manifest
            value: "steps.step-1-create-git-artifact.outputs.parameters.manifest"
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/argoproj/argo-workflows.git
          revision: master
    container:
      image: golang:1.10
      workingDir: /src
      command: [sh, -c]
      args: ["sleep 1;
              cat examples/hello-world.yaml > /tmp/hello-world.yaml"]
    outputs:
      parameters:
        - name: manifest
          valueFrom:
            default: "hello-world.yaml didnt work"
            path: "/tmp/hello-world.yaml"
  - name: create-resource
    inputs:
      parameters:
      - name: resource-manifest
    resource:
      action: create
      manifest: "{{inputs.parameters.resource-manifest}}"
```

```
Paste the logs from the workflow controller:
 Error (exit code 1): error: error validating "/tmp/manifest.yaml": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false  
```

I have also seen this error when changing the yamls:

```
create-resource master-resource-creator-lhvgb-729962375  2s    Error (exit code 1): error: error parsing /tmp/manifest.yaml: error converting YAML to JSON: yaml: mapping values are not allowed in this context
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by book987**
Signed-off-by: book987 <book78987book@gmail.com>

Fixes #5878

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM. @alexec Want to take another look to see if your feedback from the previous PR has been addressed?

**Comment by alexec** [comment]
This PR opens up a new attack vector which we need to lock down.

The new vector is path traversal via `path`.

Given that the only way to get a manifest is via an artifact artifacts, what about?

```yaml
manifetstFrom:
  artifact:
    name: my-manifest
```

We should also take this opportunity to lock down the resource pods:

Have a security context and resources similar to the agent:

https://github.com/argoproj/argo-workflows/blob/16fef4e5498fac88dc80d33d653c99fec641150d/workflow/controller/agent.go#L175

Thoughts?

**Comment by book987** [comment]
> This PR opens up a new attack vector which we need to lock down.
> 
> The new vector is path traversal via `path`.
> 
> Given that the only way to get a manifest is via an artifact artifacts, what about?
> 
> ```yaml
> manifetstFrom:
>   artifact:
>     name: my-manifest
> ```
> 
> We should also take this opportunity to lock down the resource pods:
> 
> Have a security context and resources similar to the agent:
> 
> https://github.com/argoproj/argo-workflows/blob/16fef4e5498fac88dc80d33d653c99fec641150d/workflow/controller/agent.go#L175
> 
> Thoughts?

I agree with you. Security is always one of the top concerns. I will push new change later, or maybe tomorrow.

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
See Alex’s comments above

**Comment by book987** [comment]
Hi, PTAL at code changes.
And I don't know why docs build failed, could you help?

@alexec @terrytangyuan

**Comment by terrytangyuan** [comment]
The docs build is flaky and is not related to this change.

**Comment by alexec** [comment]
@terrytangyuan would you like to take over reviewing this PR?

**Review by terrytangyuan — APPROVED** [review]
The changes look great to me. The previous comments look addressed. 

@alexec Wanna take another look?

**Comment by alexec** [comment]
Nope. I trust you review.

**Comment by book987** [comment]
should I resolve the conflicts manually? like run another `make pre-commit -B`?

**Comment by terrytangyuan** [comment]
> should I resolve the conflicts manually? like run another `make pre-commit -B`?

Yes please resolve the conflicts.

**Comment by book987** [comment]
> > should I resolve the conflicts manually? like run another `make pre-commit -B`?
> 
> Yes please resolve the conflicts.

Hi conflicts resolved. PTAL

**Review by terrytangyuan — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
