### PR TITLE
docs: Updated Workflow Controller Architecture Image

### PR DESCRIPTION
**Pull request by PranitRout07**
**Issue Details**

Text written in the Workflow controller architecture image is not visible clearly. To see issue go to this link : https://argoproj.github.io/argo-workflows/architecture/#workflow-controller-architecture

### Motivation

Documentation will look more clean.

### Modifications

As the text in the image is not visible clearly so i deleted the previous Workflow controller architecture image and uploaded a new improved image having same content.

**PREVIOUS IMAGE**
text_not_clear_in_image
**UPDATED IMAGE**
workflow-controller-queue

### Verification
[Update mkdocs.yml](https://github.com/argoproj/argo-workflows/pull/11929/commits/45ff753701f7e53be5da20d5bc62eb9e75e20d19)

### CODE REVIEW

**Review by agilgur5 — COMMENTED** [review]
This is indeed cleaner and higher res, thanks!

If we're making improvements to this already can we improve the contrast? Black text on gray shapes is very hard to read. Ideally everything should be WCAG compliant too

**Comment by PranitRout07** [comment]
Thanks for commenting @agilgur5  :),Yes , i can improve the contrast.

**Comment by agilgur5** [comment]
The black arrows on the dark blue workers rectangle are also hard to see

**Comment by PranitRout07** [comment]
Hey @agilgur5 does this work 
workflow-controller-queue

**Comment by agilgur5** [comment]
Seems like this PR was replaced by #11932.

For future reference, please use the same PR when making modifications instead of opening a new one.

**Pull request closed without merging**
