### PR TITLE
Removed Security Nudge and all its invocations

### LINKED ISSUE #8713: Remove security nudge from CLI
The CLI displays a nudge, but this makes output harder to read, and I don't believe has impact:

```
This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
```

I don't believe users change their behaviour (or are really that much interested in security) as a result of this.

Delete this func and its invocations:

https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/util/printer/workflow-printer.go#L117

### PR DESCRIPTION
**Pull request by TheSwarnim**
Signed-off-by: TheSwarnim <swarnimpratap132@gmail.com>

Fixes #8713
I've removed the function [PrintSecurityNudges ](https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/util/printer/workflow-printer.go#L117) and all its invocations from the codebase.
The invocations are located at:
- https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/cmd/argo/commands/common/get.go#L167
- https://github.com/argoproj/argo-workflows/blob/ee3765643632fa6d8dbfb528a395cbb28608e2e8/cmd/argo/commands/common/get.go#L167
In the second invocations, basically, it's the test function for the `PrintSecurityNudges` function. Since the test case is of no use if the original function is removed. So I deleted the whole function.

To make sure that all test cases passed I've removed all the test cases that were checking this function some or the other way located at:
- https://github.com/argoproj/argo-workflows/blob/86ab55726e213bc406e69edb14921b501938fa25/cmd/argo/commands/common/get_test.go#L415
- https://github.com/argoproj/argo-workflows/blob/86ab55726e213bc406e69edb14921b501938fa25/cmd/argo/commands/common/get_test.go#L440

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Failing test on CI needs fixing: Test_printWorkflowHelperNudges/InsecureWorkflow

**Comment by TheSwarnim** [comment]
HI @alexec, should I remove the testing of the `PrintSecurityNudges` function from everywhere because otherwise, it will fail because of not printing the correcting output at :
-  https://github.com/argoproj/argo-workflows/blob/e24ecd6c4b81a169cb1259895f11a5249d164471/cmd/argo/commands/common/get_test.go#L415
- https://github.com/argoproj/argo-workflows/blob/e24ecd6c4b81a169cb1259895f11a5249d164471/cmd/argo/commands/common/get_test.go#L432

**Comment by tczhao** [comment]
> HI @alexec, should I remove the testing of the `PrintSecurityNudges` function from everywhere because otherwise, it will fail because of not printing the correcting output at :
> 
> * https://github.com/argoproj/argo-workflows/blob/e24ecd6c4b81a169cb1259895f11a5249d164471/cmd/argo/commands/common/get_test.go#L415
> * https://github.com/argoproj/argo-workflows/blob/e24ecd6c4b81a169cb1259895f11a5249d164471/cmd/argo/commands/common/get_test.go#L432

I will go with what you suggested, fix the get_test

**Comment by TheSwarnim** [comment]
HI @alexec, seems like the issue is resolved now. Please review it

**Comment by alexec** [comment]
LGTM

**Pull request merged**
