### PR TITLE
chore: update `manifests` to remove deprecation warnings

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- `kustomize` was giving deprecation warnings:
  - `patchesStratetgicMerge` and `patchesJson6902` have been deprecated and replaced by `patches`
  - `commonLabels` is deprecated and replaced by `labels`
  
As an example, see the "Install manifests" step of this [recent CI run](https://github.com/argoproj/argo-workflows/actions/runs/5971449396/job/16210737547):
```sh
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

### Modifications

- run `kustomize edit fix` on all `kustomization.yaml` in `manifests` and `tests/e2e/manifests`
  - then manually update to match the already used style/formatting in these files (e.g. reordering, indentation)
- split `tests/e2e/manifests/mixins/cluster-workflow-template-rbac.yaml` into two files, one for each manifest
  - this is to workaround https://github.com/kubernetes-sigs/kustomize/issues/5049

### Verification

- `make manifests` / `make install` runs without deprecation warnings.
- Resulting generated manifests are identical, see [below comment](https://github.com/argoproj/argo-workflows/pull/11675#issuecomment-1693930353)
- E2E tests pass

### Notes to Reviewers

~Titled this as a `build`, but I'm not entirely sure what it _should_ be~ **EDIT**: used `chore` instead

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Can you check if the generated manifests match the current ones?

**Comment by agilgur5** [comment]
Oh like the release ones which are `gitignore`'d. Good point, let me double-check that to make sure.

**Comment by agilgur5** [comment]
Also there are `kustomization.yaml` I missed in the tests as well. Will update those too in this PR

**Comment by agilgur5** [comment]
Yep no diff in the generated manifests. The `quick-start-*.yaml` ones are still in the codebase too.

See check with no diff:
```sh
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (fix-update-kustomize-patches) $ git checkout master
# [...]
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (master) $ make manifests
# [...]
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (master) $ cp manifests/install.yaml ../
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (master) $ cp manifests/namespace-install.yaml ../

vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (master) $ git checkout fix-update-kustomize-patches
# [...]
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (fix-update-kustomize-patches) $ make manifests
# [...]
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (fix-update-kustomize-patches) $ diff manifests/install.yaml ../install.yaml 
vscode ➜ ~/go/src/github.com/argoproj/argo-workflows (fix-update-kustomize-patches) $ diff manifests/namespace-install.yaml ../namespace-install.yaml
```

**Comment by agilgur5** [comment]
Ah, converting tests is failing due to multiple manifests in one file (i.e. `---` syntax), which is not supported yet: https://github.com/kubernetes-sigs/kustomize/issues/5049.

Guess I'll have to partially revert the test changes and we'll just have deprecation warnings there until it is resolved upstream

**Comment by agilgur5** [comment]
> Ah, converting tests is failing due to multiple manifests in one file (i.e. `---` syntax), which is not supported yet: [kubernetes-sigs/kustomize#5049](https://github.com/kubernetes-sigs/kustomize/issues/5049).

There was only one file like this, so I just split that file instead, which should result in no errors and no deprecation warnings!

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
