### PR TITLE
feat: Enable local docker ip in for communication with outside k3d

### PR DESCRIPTION
**Pull request by devops-42**
### Motivation

This PR introduces the possibility to connect to services outside the `k3d` cluster used in DevContainer by setting up a distinct hostname. 

### Modifications

The magic hostname `host.docker.internal` is re-used and injected in the `devcontainer.json` and the CoreDNS configmap.

### Verification

Within the same Docker environment a Web container running `nginx` has been created. After that, VSCode with DevContainer is started. When DevContainer is up and running, exec a shell in a pod and issue:

```
kubectl exec -ti deploy/minio -- curl -v telnet://host.docker.internal:80
* Rebuilt URL to: telnet://host.docker.internal:80/
*   Trying 172.17.0.1...
* TCP_NODELAY set
* Connected to host.docker.internal (172.17.0.1) port 80 (#0)

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
@Joibel @tczhao Could you help review this?

**Comment by devops-42** [comment]
@terrytangyuan Commits are signed off now.

**Comment by terrytangyuan** [comment]
Thanks. Let's wait for others to review.

**Comment by devops-42** [comment]
@Joibel Thanks for your comments! I have added some documentation which hopefully should clarify the use-case.

**Review by Joibel — APPROVED** [review]
LGTM

**Comment by Joibel** [comment]
@devops-42 thank you for contributing.

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
