### PR TITLE
docs: update doc links to readthedocs/release-3.5

### PR DESCRIPTION
**Pull request by jmeridth**
Formerly #12460

Relates to #12414

### Modifications

- [x] updated docs links to https://argo-workflows.readthedocs.io/en/release-3.5
- [x] updated github issues config (like we did in main) to point to latest

### CODE REVIEW

**Comment by jmeridth** [comment]
😢 my one commit (docs links changes) is signed (passes DCO).  others seems to not have signed thiers and they were merged into release-3.5.2.

**Comment by agilgur5** [comment]
Most of them have sign-offs, just that they have changed over time based on [the logs](https://github.com/argoproj/argo-workflows/pull/12462/checks?check_run_id=20171589895)? Some of the merge commits appear to not have them though (their source PRs do have them though).

@terrytangyuan maybe it makes sense if you just fast-forward the `release-3.5` branch to match `release-3.5.2`? and then JM can rebase on top of that.
We also may want to create a `release-3.5.0` branch or tag since that doesn't currently exist

**Comment by jmeridth** [comment]
@agilgur5 @terrytangyuan either way.  I'm good.  I await response.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Can you do a rebase? I updated the release branch

**Comment by jmeridth** [comment]
@terrytangyuan on it

**Comment by jmeridth** [comment]
@terrytangyuan done

**Comment by jmeridth** [comment]
https://argo-workflows.readthedocs.io/en/release-3.5/ is live

**Pull request merged**
