### PR TITLE
build: Add containerized make commands. Resolves #6519

### LINKED ISSUE #6519: Make it easier to “make pre-commit”
This is one of the biggest barriers to getting good PR done. How can we make this easier? Maybe running the tools in a container?

### PR DESCRIPTION
**Pull request by JPZ13**
This PR:
- Adds containerized versions of make commands that are commonly run while developing

It works by spinning up a container that holds tooling dependencies and volume mounting it on the user's filesystem.
The goal is to allow for development without having to spend as much time configuring your host machine.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Just tried this out on a Mac M1 and got `qemu: uncaught target signal 11 (Segmentation fault) - core dumped`.

**Comment by JPZ13** [comment]
> Just tried this out on a Mac M1 and got `qemu: uncaught target signal 11 (Segmentation fault) - core dumped`.

It seems docker bind mounts are pretty [spotty on M1 Macs](https://github.com/docker/for-mac/issues/3677). @terrytangyuan, have you used [docker-sync](https://github.com/EugenMayer/docker-sync) on your M1? I'm on an Intel based Mac and can't reproduce. I'll port it over to docker sync if it's a smooth M1 experience

**Comment by terrytangyuan** [comment]
I tried docker-sync once but I remember it was stuck somewhere waiting for the sync forever so I gave up.

**Comment by JPZ13** [comment]
Running into the docker-sync problems @terrytangyuan mentioned above. Closing for now

**Pull request closed without merging**
