### PR TITLE
fix(docs): render Mermaid diagrams in docs

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- `docs/retries.md` has a Mermaid diagram that renders out-of-the-box on GH but not on the docs site itself
  - needs a Mermaid renderer for `mkdocs`
  
follow-up to #11005, https://github.com/argoproj/argo-workflows/issues/11390#issuecomment-1876274288, and [Nov 21st Contributor Meeting](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.kx3ajuyqr2ry)

### Modifications

- add a `pymdownx.superfences` config to render out Mermaid diagrams in `mkdocs` per https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration

### Verification

Ran `make docs` followed by `open site/retries/index.html` to view in the browser.

Screenshots:

Before:
Screenshot 2024-01-04 at 3 03 00 PM

After:
Screenshot 2024-01-04 at 2 34 36 PM

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
I am curious - is this reactive? Can you try resizing your browser?

**Review by jmeridth — APPROVED** [review]

**Comment by agilgur5** [comment]
> I am curious - is this reactive? Can you try resizing your browser?

I think you mean [responsive](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design). Technically speaking, yes, it's a percentage of the screen:
Screenshot 2024-01-04 at 3 51 59 PM

That's a variant of responsive design (it used to be called adaptive design back in the day (~2014), but that now means something different). In full responsive design, you may want to render a different image for different screen sizes.

GitHub has the fancy mouse gestures that let you zoom and scroll the diagram which this does not. Those are nice, but I think this is good enough. Users can click the image to see it full screen if they want to and then zoom from there etc

**Comment by terrytangyuan** [comment]
Great thanks! Yes I meant responsive.

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
Rendering properly on RTD now 🙂 : https://argo-workflows.readthedocs.io/en/latest/retries/#retry-policies

**Pull request merged**
