### PR TITLE
workflow-controller: use parentId instead of parentname

### LINKED ISSUE #5830: nodeAffinity retryStrategy children node lookup is done on name while 'Children(parentId)' expects ID
## Summary 

Using retryStrategy nodeAntiAffinity to work as example describes 
```yaml
    retryStrategy:
      limit: 10
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
```

## Diagnostics

Seen on private K8S cluster

tested on v3.0.1 (but checked master branch as well)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
  name: wf-test
spec:
  entrypoint: workflow-example
  templates:
  - name: workflow-example
    steps:
    - - name: run
        template: sleepabit
        continueOn:
          failed: true
  - name: sleepabit
    retryStrategy:
      limit: 1
      retryPolicy: "Always"
      affinity:
        nodeAntiAffinity: {}
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: [sleep 15 && false"]
```

logs of controller with some extra prints shoul that the lookup of the children fails, and so hostNames is empty:
```
time="2021-05-05T12:51:38.776Z" level=info msg="Get leases 200"
time="2021-05-05T12:51:38.782Z" level=info msg="Processing workflow" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.783Z" level=info msg="Pod failed: Error (exit code 1)" displayName="run(0)" namespace=default pod=wf-test-73877493 templateName=sleepabit workflow=wf-test
[...]
time="2021-05-05T12:51:38.789Z" level=info msg="jheylen: retry" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.789Z" level=info msg="1 child nodes of wf-test[0].run failed. Trying again..." namespace=default workflow=wf-test
time="2021-05-05T12:51:38.789Z" level=info msg="jheylen: create an new child" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.789Z" level=info msg="jheylen: retry on different host" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.790Z" level=info msg="seen retryStrategy: {1 Always nil &RetryAffinity{NodeAntiAffinity:&RetryNodeAntiAffinity{},}}"
time="2021-05-05T12:51:38.790Z" level=info msg="jheylen: seen nodes: map[]"
time="2021-05-05T12:51:38.790Z" level=info msg="jheylen: seen failNodes: map[]"
time="2021-05-05T12:51:38.790Z" level=info msg="seen hostNames: []"
time="2021-05-05T12:51:38.790Z" level=info msg="Pod node wf-test-2020228392 initialized Pending" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.795Z" level=info msg="Create events 201"
time="2021-05-05T12:51:38.800Z" level=info msg="Create pods 201"
time="2021-05-05T12:51:38.801Z" level=info msg="Created pod: wf-test[0].run(1) (wf-test-2020228392)" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.801Z" level=info msg="Workflow step group node wf-test-4187779359 not yet completed" namespace=default workflow=wf-test
time="2021-05-05T12:51:38.860Z" level=info msg="Update workflows 200"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by heyleke**
Fixes #5830

### CODE REVIEW

**Comment by goock** [comment]
@alexec I can try to help with this.

**Comment by alexec** [comment]
bump! @goock did you have any feedback?

**Comment by goock** [comment]
> bump! @goock did you have any feedback?

yes, I tested this PR, it works perfectly, `woc.wf.NodeID()` ensures that we always get ID.

**Review by alexec — CHANGES_REQUESTED** [review]
please add a test

**Comment by heyleke** [comment]
well, there is actually on a test in operator_test.go for it, but it uses 'nodeID' ;-) :

```go
5804 func TestRetryOnDiffHost(t *testing.T) {
[...]
5812     // Add the parent node for retries.
5813     nodeName := "test-node"
5814     nodeID := woc.wf.NodeID(nodeName)
5815     node := woc.initializeNode(nodeName, wfv1.NodeTypeRetry, "", &wfv1.WorkflowStep{}, "", wfv1.NodeRunning)
[...]
5854 
5855     tmpl := &wfv1.Template{}
5856     tmpl.RetryStrategy = &retries
5857     RetryOnDifferentHost(nodeID)(*woc.retryStrategy(tmpl), woc.wf.Status.Nodes, tmpl)
5858     assert.NotNil(t, tmpl.Affinity)
5859 
```
but the usage in executeTemplate was wrong IMHO, but I'm not sure how I can add a test for that, should it be some e2e test instead of a unittest?
ut-vs-e2e

**Review by alexec — APPROVED** [review]

**Pull request merged**
