### PR TITLE
fix(ui): strip inner quotes from argoToken

### LINKED ISSUE #4991: "token not valid for running mode" after SSO authentication
## Summary 

Argo UI comes back to login page with error `{"code":16,"message":"token not valid for running mode”}` after completing SSO user authentication.

## Diagnostics

argo version:
argo: v2.12.3
  BuildDate: 2021-01-05T00:49:48Z
  GitCommit: 93ee530126cc1fc154ada84d5656ca82d491dc7f
  GitTreeState: clean
  GitTag: v2.12.3
  GoVersion: go1.13
  Compiler: gc
  Platform: darwin/amd64

I have added sso configuration in  the config map "workflow-controller-configmap"
```yaml
sso: |
      issuer: https://cloudsso-test.xxx.com
      clientId:
        name: argo-server-sso
        key: clientID
      clientSecret:
        name: argo-server-sso
        key: clientSecret
      redirectUrl: http://argo-code.xxx.com/workflows/argo
      scopes:
       - groups
       - email
      rbac:
        enabled: false
```
I have added the required secrets for SSO and also starting argo-server  in "--auth-mode sso"

argo-server logs :
```
time="2021-02-02T07:34:01.198Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-02-02T07:34:01Z" grpc.time_ms=0.34 span.kind=server system=grpc
time="2021-02-02T07:34:01.218Z" level=info msg="finished unary call with code Unauthenticated" error="rpc error: code = Unauthenticated desc = token not valid for running mode" grpc.code=Unauthenticated grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-02-02T07:34:01Z" grpc.time_ms=0.065 span.kind=server system=grpc
```

**Please note we use JWT token for SSO and not JWE.** 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by mruoss**
closes #4991

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
Could I please ask for a screenshotot?

**Comment by mruoss** [comment]
A screenshot? Of what? The token is redacted in the UI!

**Comment by alexec** [comment]
Of the page. You may redact any secrets.

**Comment by mruoss** [comment]
What I was trying to tell you is that visually nothing changes with my commit. I testes my code in my browser's console while being on a live instance. I was relying on tests but realized now that there is not really a test suite for the ui. Guess Screenshots are your test suite? 

So if you want me to set up the local env and send you a screenshot, it might take a while.

**Comment by mruoss** [comment]
where should I put the screenshot?

**Review by alexec — APPROVED** [review]

**Pull request merged**
