### PR TITLE
chore: Add goimports -local to make lint

### PR DESCRIPTION
**Pull request by simster7**
Signed-off-by: Simon Behar <simbeh7@gmail.com>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Comment by alexec** [comment]
doesn't `gci` fix the imports?

**Comment by simster7** [comment]
> doesn't gci fix the imports?

Not on my machine. In fact I don't see `gci` on the Makefile and it's also not installed on my machine (hinting that `make lint` does not use it).

**Comment by alexec** [comment]
Are these files some how omitted from golangci?

https://github.com/argoproj/argo-workflows/blob/78dd747c600541c7ae2e71b473c0652fdd105c66/.golangci.yml#L33

**Comment by simster7** [comment]
I'll close this while I investigate

**Pull request closed without merging**
