### PR TITLE
fix: remove code for Workflows search box is useless. Fixes #8648

### LINKED ISSUE #8648: Workflows search box is useless (faster to use browser search)
Remove the workflow search box.

https://github.com/argoproj/argo-workflows/blob/3e678b6cac42635588f04b22908f01693a95265a/ui/src/app/workflows/components/workflows-list/workflows-list.tsx#L168

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
Fixes #8648

### CODE REVIEW

**Comment by alexec** [comment]
TS6133: 'renderQuery' is declared but its value is never read.

**Comment by alexec** [comment]
Run “yarn build” locally once fixed to verify.

**Review by alexec — CHANGES_REQUESTED** [review]
see comments

**Comment by alexec** [comment]
This PR needs some small changes. I think it is a good idea.

**Comment by agilgur5** [comment]
Replaced by #9208

**Pull request closed without merging**
