### PR TITLE
chore: Upgrade gjson to allow extract values from stringified json

### PR DESCRIPTION
**Pull request by tooptoop4**
fixes https://github.com/argoproj/argo-workflows/discussions/7550
see https://github.com/tidwall/gjson/issues/260#issuecomment-1012294762

### CODE REVIEW

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
Please fix codegen. You might just need to run `go mod tidy`.

**Comment by tooptoop4** [comment]
@terrytangyuan fixed

**Comment by terrytangyuan** [comment]
Could you fix the DCO check?

**Comment by blkperl** [comment]
We just merged a change to enable dependabot for the repo and it will keep gjson up to date going forward once we get through the queue.

**Comment by blkperl** [comment]
This has been merged in https://github.com/argoproj/argo-workflows/pull/7992

**Pull request closed without merging**
