### PR TITLE
docs: Rename back upgrading guide

### PR DESCRIPTION
**Pull request by terrytangyuan**
The new location breaks existing release notes https://github.com/argoproj/argo-workflows/releases/tag/v3.3.6

Renaming back so we can also use it to document anything that's worth attention to our users, e.g. https://github.com/argoproj/argo-workflows/pull/8860.

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by terrytangyuan** [comment]
@alexec ` >> 22 spelling errors found in 126 files` I don't think those are easy fixes. Not sure why this didn't complain earlier. I propose to remove the spelling check completely since it's tedious to keep adding stuff like usernames, release prefixes, etc. to this list: https://github.com/argoproj/argo-workflows/blob/master/.spelling

**Comment by terrytangyuan** [comment]
Ok noticed that the file name is hard-coded in `make docs-spellcheck`. It should be fixed now.

**Comment by terrytangyuan** [comment]
Getting false positives like these:
```
FILE: docs/metrics.md

  [✖] https://prometheus.io/docs/concepts/metric_types/

  8 links checked.
  ERROR: 1 dead links found!
  [✖] https://prometheus.io/docs/concepts/metric_types/ → Status: 403
  
   FILE: docs/use-cases/data-processing.md
  [✖] https://towardsdatascience.com/running-a-data-replication-pipeline-on-kubernetes-with-argo-and-singer-io-2fab5b0bad?utm_source=argo-docs

  ERROR: 1 dead links found!
```

@alexec Should we remove the spell check?

**Comment by tczhao** [comment]
> Getting false positives like these:
> 
> ```
> FILE: docs/metrics.md
> 
>   [✖] https://prometheus.io/docs/concepts/metric_types/
> 
>   8 links checked.
>   ERROR: 1 dead links found!
>   [✖] https://prometheus.io/docs/concepts/metric_types/ → Status: 403
>   
>    FILE: docs/use-cases/data-processing.md
>   [✖] https://towardsdatascience.com/running-a-data-replication-pipeline-on-kubernetes-with-argo-and-singer-io-2fab5b0bad?utm_source=argo-docs
> 
>   ERROR: 1 dead links found!
> ```
> 
> @alexec Should we remove the spell check?

I think this error is from the `docs-linkcheck` rather than `spellcheck`.
The `linkcheck` can be flaky on git actions

**Comment by terrytangyuan** [comment]
Alright I re-ran the tests and now they passed.

**Pull request merged**
