### PR TITLE
fix(server): mutex calls to sqlitex

### LINKED ISSUE #13140: 3.5.7 Server pods are crashing after upgrade
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

After upgrading from 3.5.5 to 3.5.7 argo server pods crashed with two types of errors
<details>
  <summary>Recovered from panic: runtime error: invalid memory address or nil pointer dereference</summary>

_edited by agilgur5_: reformatted to make it more readable
```
{"level":"error","msg":"
Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 94056 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.PanicLoggerUnaryServerInterceptor.func4.1()
	/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:22 +0x4e
panic({0x28f9d80?, 0x54d4f70?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
//                       extra new line added by agilgur5 for readability
modernc.org/sqlite/lib._sqlite3OsRead(...)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:16239
modernc.org/sqlite/lib._read32bits(0xc0007f8dc0, 0x7fc15b2006a0, 0xc0007f8dc0?, 0x7fc15ba00888)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:35366 +0x82
modernc.org/sqlite/lib._readJournalHdr(0xc0007f8dc0, 0x7fc15b200428, 0x0, 0xf278, 0x554ced0?, 0xc00103ba98?)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:35847 +0x1c7
modernc.org/sqlite/lib._pager_playback(0xc0007f8dc0, 0x7fc15b200428, 0x0)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:37114 +0x437
modernc.org/sqlite/lib._sqlite3PagerRollback(0xc0007f8dc0?, 0x7fc15b200428)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:40864 +0x65
modernc.org/sqlite/lib._sqlite3BtreeRollback(0xc0007f8dc0, 0x7fc15b600228, 0x0, 0x1)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:51547 +0x125
modernc.org/sqlite/lib._sqlite3RollbackAll(0x196119b?, 0x7fc15b200028, 0x5b200028?)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:164759 +0xd9
modernc.org/sqlite/lib._sqlite3VdbeHalt(0x7fc15ba007e0?, 0x7fc15af05c28)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:64500 +0x3bd
modernc.org/sqlite/lib._sqlite3VdbeExec(0xc0007f8dc0, 0x7fc15af05c28)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:77403 +0x545
modernc.org/sqlite/lib._sqlite3Step(0xc0007f8dc0?, 0x7fc15af05c28)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:67274 +0x6c
modernc.org/sqlite/lib.Xsqlite3_step(0x2876300?, 0x7fc15af05c28)
	/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:67339 +0xab
//                       extra new line added by agilgur5 for readability
zombiezen.com/go/sqlite.(*Stmt).step(0xc000a01bc0)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlite.go:799 +0xac
zombiezen.com/go/sqlite.(*Stmt).Step(0xc000a01bc0)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlite.go:785 +0xb6
zombiezen.com/go/sqlite/sqlitex.exec(0xc000a01bc0, 0x3, 0xc00103c860)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlitex/exec.go:293 +0x308
zombiezen.com/go/sqlite/sqlitex.Execute(0x2d769c0?, {0xc000bce820?, 0xc001258e10?}, 0x12?)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlitex/exec.go:123 +0x45
//                       extra new line added by agilgur5 for readability
github.com/argoproj/argo-workflows/v3/server/workflow/store.(*SQLiteStore).ListWorkflows(0xc000700a38, {0xc000589360?, 0x0?}, {0xc001258e10?, 0x0?}, {0x0?, 0x0?}, {{{0x0, 0x0}, {0x0, ...}}, ...})
	/go/src/github.com/argoproj/argo-workflows/server/workflow/store/sqlite_store.go:105 +0x2ab
github.com/argoproj/argo-workflows/v3/server/workflow.(*workflowServer).ListWorkflows(0xc000c3f620, {0x3d0fdd0, 0xc001713110}, 0xc00018b270)
	/go/src/github.com/argoproj/argo-workflows/server/workflow/workflow_server.go:202 +0x3d2
github.com/argoproj/argo-workflows/v3/pkg/apiclient/workflow._WorkflowService_ListWorkflows_Handler.func1({0x3d0fdd0, 0xc001713110}, {0x2c43be0?, 0xc00018b270})
	/go/src/github.com/argoproj/argo-workflows/pkg/apiclient/workflow/workflow.pb.go:1826 +0x72
github.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.RatelimitUnaryServerInterceptor.func5({0x3d0fdd0, 0xc001713110}, {0x2c43be0, 0xc00018b270}, 0xc0002f5760, 0xc0015b47b0)\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:65 +0x133\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc001713110?}, {0x2c43be0?, 0xc00018b270?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/server/auth.(*gatekeeper).UnaryServerInterceptor.func1({0x3d0fdd0?, 0xc0013d18f0?}, {0x2c43be0, 0xc00018b270}, 0xc000819230?, 0xc0002f57a0)\n\t/go/src/github.com/argoproj/argo-workflows/server/auth/gatekeeper.go:98 +0x63\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc0013d18f0?}, {0x2c43be0?, 0xc00018b270?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/util/grpc.glob..func1({0x3d0fdd0?, 0xc0013d18f0?}, {0x2c43be0?, 0xc00018b270?}, 0x2d8a829?, 0xf?)\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:45 +0x2a\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc0013d18f0?}, {0x2c43be0?, 0xc00018b270?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.PanicLoggerUnaryServerInterceptor.func4({0x3d0fdd0?, 0xc0013d18f0?}, {0x2c43be0?, 0xc00018b270?}, 0x0?, 0x0?)\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:26 +0x8c\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc0013d18f0?}, {0x2c43be0?, 0xc00018b270?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x3d0fdd0, 0xc0013d1740}, {0x2c43be0, 0xc00018b270}, 0xc0002f5760, 0xc0002f5820)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/logrus/server_interceptors.go:31 +0xf6\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc0013d1740?}, {0x2c43be0?, 0xc00018b270?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x3d0fdd0, 0xc0013d1740}, {0x2c43be0, 0xc00018b270}, 0x29d5e00?, 0xc0002f5860)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x83\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc0013d1740?}, {0x2c43be0?, 0xc00018b270?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6({0x3d0fdd0, 0xc0013d1740}, {0x2c43be0, 0xc00018b270}, 0xc0000429f8?, 0x28fb280?)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xb5\ngithub.com/argoproj/argo-workflows/v3/pkg/apiclient/workflow._WorkflowService_ListWorkflows_Handler({0x2ca24a0?, 0xc000c3f620}, {0x3d0fdd0, 0xc0013d1740}, 0xc0015c5b80, 0xc00093b710)\n\t/go/src/github.com/argoproj/argo-workflows/pkg/apiclient/workflow/workflow.pb.go:1828 +0x135\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc00097e1e0, {0x3d0fdd0, 0xc0013d16b0}, {0x3d1cf40, 0xc0026611e0}, 0xc0005fbe60, 0xc00093bb00, 0x54f3fb0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03\ngoogle.golang.org/grpc.(*Server).handleStream(0xc00097e1e0, {0x3d1cf40, 0xc0026611e0}, 0xc0005fbe60)\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1()\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 236\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145\n
//                       extra new line added by agilgur5 for readability
", "time":"2024-05-29T07:23:45.611Z"}

```

</details>

<details>
  <summary>Recovered from panic: runtime error: index out of range [70437463654405] with length 64</summary>

_edited by agilgur5_: reformatted to make it more readable
```
{"level":"error","msg":"
Recovered from panic: runtime error: index out of range [70437463654405] with length 64
goroutine 69107 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.PanicLoggerUnaryServerInterceptor.func4.1()\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:22 +0x4e\npanic({0x2b8f600?, 0xc0018d4000?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f
//                       extra new line added by agilgur5 for readability
modernc.org/memory.(*Allocator).UintptrFree(0xc001c857c8?, 0xc001c85808?)\n\t/go/pkg/mod/modernc.org/memory@v1.7.2/memory.go:201 +0x138\nmodernc.org/libc.Xfree(0x1902b00?, 0x5518be0?)\n\t/go/pkg/mod/modernc.org/libc@v1.41.0/mem.go:98 +0x8e\nmodernc.org/sqlite/lib._sqlite3MemFree(0x1903756?, 0xc0005cc760?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:16853 +0x17\nmodernc.org/sqlite/lib.Xsqlite3_free(0xc000870780?, 0x1927cd0?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:17828 +0xb8\nmodernc.org/sqlite/lib._pcache1ResizeHash(0x7f08ee2ce488?, 0x7f08ef7ff8a8?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:33108 +0x145\nmodernc.org/sqlite/lib._pcache1FetchStage2(0x1903756?, 0x7f08ef7ff8a8, 0x101, 0x1)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:33469 +0xb6\nmodernc.org/sqlite/lib._pcache1FetchNoMutex(0xc000870780?, 0xc001c85930?, 0x19268d5?, 0x0?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:33594 +0xac\nmodernc.org/sqlite/lib._pcache1FetchWithMutex(0x7f08edfdf0b0?, 0x7f08ef7ff8a8, 0x1c85960?, 0xc0?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:33607 +0x59\nmodernc.org/sqlite/lib._pcache1Fetch(0x19333c5?, 0x100?, 0x870780?, 0xc0?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:33624 +0x1f\nmodernc.org/sqlite/lib._sqlite3PcacheFetch(0xc0005cc760?, 0x7f08ef3fec28?, 0x100?, 0xc0?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:31810 +0x2a\nmodernc.org/sqlite/lib._getPageNormal(0xc000870780, 0x7f08ef3fec28, 0x101, 0x7f08efb00270, 0x1)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:39726 +0xa8\nmodernc.org/sqlite/lib._sqlite3PagerGet(...)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:39889\nmodernc.org/sqlite/lib._btreeGetPage(0xc000870780, 0x7f08eff2b028, 0x101, 0x7f08efb00248, 0x870780?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:49324 +0xa6\nmodernc.org/sqlite/lib._btreeGetUnusedPage(0xc000870780?, 0x7f08edcfc044?, 0x1916c94?, 0x7f08efb00248, 0x1c85ac0?)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:49452 +0x25\nmodernc.org/sqlite/lib._allocateBtreePage(0xc000870780, 0x7f08eff2b028, 0x7f08efb00248, 0x7f08efb00244, 0x100, 0x0)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:53819 +0x489\nmodernc.org/sqlite/lib._fillInCell(0xc000870780, 0x7f08edf7d0b0, 0x7f08edcf802c, 0x7f08efafff68, 0x7f08efb001a8)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:54224 +0x615\nmodernc.org/sqlite/lib._sqlite3BtreeInsert(0xc000870780, 0x7f08eef07140, 0x7f08efafff68, 0x0, 0x0)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:56763 +0x68e\nmodernc.org/sqlite/lib._sqlite3VdbeExec(0xc000870780, 0x7f08ef005428)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:75229 +0x98ab\nmodernc.org/sqlite/lib._sqlite3Step(0xc000870780?, 0x7f08ef005428)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:67274 +0x6c\nmodernc.org/sqlite/lib.Xsqlite3_step(0x2876300?, 0x7f08ef005428)\n\t/go/pkg/mod/modernc.org/sqlite@v1.29.1/lib/sqlite_linux_amd64.go:67339 +0xab
//                       extra new line added by agilgur5 for readability
zombiezen.com/go/sqlite.(*Stmt).step(0xc0007020c0)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlite.go:799 +0xac
zombiezen.com/go/sqlite.(*Stmt).Step(0xc0007020c0)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlite.go:785 +0xb6
zombiezen.com/go/sqlite/sqlitex.exec(0xc0007020c0, 0x3, 0xc001c86860)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlitex/exec.go:293 +0x308
zombiezen.com/go/sqlite/sqlitex.Execute(0x2d769c0?, {0xc00100a4e0?, 0xc00147ec90?}, 0x12?)
	/go/pkg/mod/zombiezen.com/go/sqlite@v1.2.0/sqlitex/exec.go:123 +0x45
//                       extra new line added by agilgur5 for readability
github.com/argoproj/argo-workflows/v3/server/workflow/store.(*SQLiteStore).ListWorkflows(0xc0009c3698, {0xc0006aea00?, 0x0?}, {0xc00147ec90?, 0x0?}, {0x0?, 0x0?}, {{{0x0, 0x0}, {0x0, ...}}, ...})
	/go/src/github.com/argoproj/argo-workflows/server/workflow/store/sqlite_store.go:105 +0x2ab
github.com/argoproj/argo-workflows/v3/server/workflow.(*workflowServer).ListWorkflows(0xc000921e60, {0x3d0fdd0, 0xc001306600}, 0xc0013e4e60)
	/go/src/github.com/argoproj/argo-workflows/server/workflow/workflow_server.go:202 +0x3d2
github.com/argoproj/argo-workflows/v3/pkg/apiclient/workflow._WorkflowService_ListWorkflows_Handler.func1({0x3d0fdd0, 0xc001306600}, {0x2c43be0?, 0xc0013e4e60})
	/go/src/github.com/argoproj/argo-workflows/pkg/apiclient/workflow/workflow.pb.go:1826 +0x72
github.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.RatelimitUnaryServerInterceptor.func5({0x3d0fdd0, 0xc001306600}, {0x2c43be0, 0xc0013e4e60}, 0xc001bd8120, 0xc001b84b88)\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:65 +0x133\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc001306600?}, {0x2c43be0?, 0xc0013e4e60?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/server/auth.(*gatekeeper).UnaryServerInterceptor.func1({0x3d0fdd0?, 0xc000e6e2a0?}, {0x2c43be0, 0xc0013e4e60}, 0xc000bdd830?, 0xc001bd8140)\n\t/go/src/github.com/argoproj/argo-workflows/server/auth/gatekeeper.go:98 +0x63\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc000e6e2a0?}, {0x2c43be0?, 0xc0013e4e60?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/util/grpc.glob..func1({0x3d0fdd0?, 0xc000e6e2a0?}, {0x2c43be0?, 0xc0013e4e60?}, 0x2d8a829?, 0xf?)\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:45 +0x2a\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc000e6e2a0?}, {0x2c43be0?, 0xc0013e4e60?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.PanicLoggerUnaryServerInterceptor.func4({0x3d0fdd0?, 0xc000e6e2a0?}, {0x2c43be0?, 0xc0013e4e60?}, 0x0?, 0x0?)\n\t/go/src/github.com/argoproj/argo-workflows/util/grpc/interceptor.go:26 +0x8c\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc000e6e2a0?}, {0x2c43be0?, 0xc0013e4e60?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x3d0fdd0, 0xc001843f50}, {0x2c43be0, 0xc0013e4e60}, 0xc001bd8120, 0xc001bd81a0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/logrus/server_interceptors.go:31 +0xf6\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc001843f50?}, {0x2c43be0?, 0xc0013e4e60?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x3d0fdd0, 0xc001843f50}, {0x2c43be0, 0xc0013e4e60}, 0x29d5e00?, 0xc001bd81c0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x83\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6.1.1({0x3d0fdd0?, 0xc001843f50?}, {0x2c43be0?, 0xc0013e4e60?})\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x37\ngithub.com/argoproj/argo-workflows/v3/server/apiserver.(*argoServer).newGRPCServer.ChainUnaryServer.func6({0x3d0fdd0, 0xc001843f50}, {0x2c43be0, 0xc0013e4e60}, 0xc0009609f8?, 0x28fb280?)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xb5\ngithub.com/argoproj/argo-workflows/v3/pkg/apiclient/workflow._WorkflowService_ListWorkflows_Handler({0x2ca24a0?, 0xc000921e60}, {0x3d0fdd0, 0xc001843f50}, 0xc000d34800, 0xc000706ab0)\n\t/go/src/github.com/argoproj/argo-workflows/pkg/apiclient/workflow/workflow.pb.go:1828 +0x135\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0001521e0, {0x3d0fdd0, 0xc001843e60}, {0x3d1cf40, 0xc000740b60}, 0xc00139f560, 0xc0007076e0, 0x54f3fb0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0001521e0, {0x3d1cf40, 0xc000740b60}, 0xc00139f560)\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1()\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 296\n\t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145
//                       extra new line added by agilgur5 for readability
","time":"2024-05-29T07:47:53.387Z"}

```
</details>
Screenshot 2024-06-03 at 10 29 29

<hr>

_edited by Joibel and agilgur5_: The below split into a separate issue - see #13149

and argo controllers are flooded with

```
{"level":"warning","msg":"Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"workflow-6gndn\": the object has been modified; please apply your changes to the latest version and try again Conflict","namespace":"customer-workflows","time":"2024-05-29T11:47:22.010Z","workflow":"workflow-6gndn"}
```

Logz io 2024-06-03 10-26-18

### Version

3.5.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

we have dynamic load, average 1-1,5 pods per second, max 50 running in parallel, up to 100 in pending status, workflows are persisted in postgres database.

Here is part of our config:

```yaml
parallelism: 50
resourceRateLimit:
  limit: 100
  burst: 3
mainContainer:
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.3
      memory: 256M
    requests:
      cpu: 0.1
      memory: 128M
executor:
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 0.3
      memory: 256M
    requests:
      cpu: 0.1
      memory: 128M
artifactRepository:
  archiveLogs: true
  s3:
    bucket: argo-wf
    endpoint: s3.eu-west-1.amazonaws.com
    keyFormat: "{{workflow.labels.customer-id}}/{{workflow.name}}/{{pod.name}}"
    region: eu-west-1
persistence:
  archive: true
  nodeStatusOffLoad: true
  connectionPool:
    connMaxLifetime: 300s
  postgresql:
    host: argo-rds
    port: 5432
    database: argo_production
    tableName: argo_workflows
    userNameSecret:
      key: username
      name: db-secret
    passwordSecret:
      key: password
      name: db-secret
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### LINKED ISSUE #13154: 3.5.7 Server keeps restarting, panicking
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

we have several hundred workflows in our environment, doing listing workflows 20 req/s to check memory utilization i am getting container restarts with panic for argo-server pod, prior to this i see slow query warnings
[argo-trace.zip](https://github.com/user-attachments/files/15740437/argo-trace.zip)

### Version

v3.5.7

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
any simple workflow, create 1000 workflows and try to list 20req/s e.g. with firefox tab reloader
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by Joibel**
Fixes #13154
Fixes #13140

### Motivation

[zombiezen/go-sqlite](https://github.com/zombiezen/go-sqlite/blob/main/doc.go#L32) is not thread safe when used through a single connection. The current code is provably racing (run the server with `-race` and a few workflows being run) and it will tell you this if you `argo list` via the server a few times. Unless it crashes first.

### Modifications

This change doesn't attempt to move to a multiple connection model, it's a minimal change to stop the server crashing all the time, by mutexing the use of the sql connection.

### Verification

Running v3.5.7

Inject 200 `example/dag-diamond.yaml`s into your cluster. Run `argo list -s <server>` to list the workflows. It will crash within a few attempts, usually

With this change it didn't crash in 200 attempts at `argo list`.

`-race` build of the server doesn't complain any more either.

### CODE REVIEW

**Comment by agilgur5** [comment]
cc @jiachengxu for review

**Review by jiachengxu — APPROVED** [review]
The change looks good to me, thanks for the work @Joibel!

**Comment by Joibel** [comment]
@agilgur5, @tczhao, @isubasinghe, @terrytangyuan - could someone take a look at this one so we can prep a 3.5.8 with it in?

**Review by terrytangyuan — APPROVED** [review]

**Comment by sarabala1979** [comment]
good catch @Joibel

**Comment by agilgur5** [comment]
Nice work figuring out the root cause @Joibel!
Since we hadn't found any nil pointers in our own code, I was suspecting it might be within the SQLite library, although I definitely did not expect that it wasn't thread-safe. Those GoDoc comments really belong in the README of the library IMO 😕 

Will you or @jiachengxu be taking up the full fix with thread pooling?

> so we can prep a 3.5.8 with it in?

Would like to get a fix for #13177 in as well and then release it ASAP

**Comment by agilgur5** [comment]
> Will you or @jiachengxu be taking up the full fix with thread pooling?

Wrote up a follow-up issue to track this in #13638

**Pull request merged**
