### PR TITLE
docs: Added example of CI-CD workflow

### LINKED ISSUE #8591: Add an example of CI/CD - one that builds Argo Workflows, using Argo Workflows
Users want a more detailed example of doing CI and CD. We should have one that builds Argo Workflows (so it is Argo all the way down):

CI:

* Use webhook to start build (i.e. `WorkflowEventBinding`).
* Build the CLI.
* Build images using Buildkit (see [template](https://github.com/argoproj/argo-workflows/blob/master/examples/buildkit-template.yaml)).
* Run test and collect test report.
* Run coverage and collect report.
* Deploy to a cluster.
* Run basic E2E tests and collect report.

CD:

* Tag and push tag.
* Update deployment manifests using `kustomize edit set image`.
* Commit deployment manifests.
* Start Argo CD sync step (should this use a plugin?).

Pipline:

* Combine CI and CD jobs with an approval step.

### PR DESCRIPTION
**Pull request by surbhiahuja**
Fixes #8591

### CODE REVIEW

**Comment by sarabala1979** [comment]
@juliev0 can you quick look?

**Review by juliev0 — COMMENTED** [review]
Sorry, I just want to make sure this PR is for argo-workflows and not argo-cd ?

**Comment by alexec** [comment]
Thank you for raising this PR, yet I think we have docs for CI already.

**Comment by agilgur5** [comment]
For posterity, looks like this was supposed to address #8591 but did not quite match the requirements. It is looking for examples. See https://github.com/argoproj/argo-workflows/issues/8591#issuecomment-1413600564 for part of such an example

**Pull request closed without merging**
