### PR TITLE
ci: reduce test & CI flakes with retries + longer waits & timeouts

### PR DESCRIPTION
**Pull request by agilgur5**
Partial fix for #10807

### Motivation

- signal_test.go was flaking quite a bit in CI
   - examples (all same test, same error): [1](https://github.com/argoproj/argo-workflows/actions/runs/6090397163/job/16525212870?pr=11752), [2](https://github.com/argoproj/argo-workflows/actions/runs/6090397163/job/16525214144?pr=11752), [3](https://github.com/argoproj/argo-workflows/actions/runs/6057348108/job/16438451395?pr=11727), [4](https://github.com/argoproj/argo-workflows/actions/runs/6024154407/job/16342412510?pr=11716), [5](https://github.com/argoproj/argo-workflows/actions/runs/5910880044/job/16032931699?pr=11568), [6](https://github.com/argoproj/argo-workflows/actions/runs/5910880485/job/16032933770?pr=11567), [7](https://github.com/argoproj/argo-workflows/actions/runs/6066706542/job/16457612480), [8](https://github.com/argoproj/argo-workflows/actions/runs/6008824810/job/16297128151), [9](https://github.com/argoproj/argo-workflows/actions/runs/6076177904/job/16483849857), [10](https://github.com/argoproj/argo-workflows/actions/runs/5979752022/job/16224632564?pr=11637), [11](https://github.com/argoproj/argo-workflows/actions/runs/5922167534/job/16055845745), [12](https://github.com/argoproj/argo-workflows/actions/runs/6092222043/job/16530030316), [13](https://github.com/argoproj/argo-workflows/actions/runs/6088747445/job/16520226969), [14](https://github.com/argoproj/argo-workflows/actions/runs/6019750405/job/16330112382), [15](https://github.com/argoproj/argo-workflows/actions/runs/6005141116/job/16287356878), [16](https://github.com/argoproj/argo-workflows/actions/runs/5980829119/job/16227812975), [17](https://github.com/argoproj/argo-workflows/actions/runs/5959534969/job/16165466761), [18](https://github.com/argoproj/argo-workflows/actions/runs/5898116342/job/15998761453), [19](https://github.com/argoproj/argo-workflows/actions/runs/5886793569/job/15965217053)
     - the most frequent test flake I've seen by a good margin (~20x (?) more than any other one, anecdotally)

- the rest are incidental, but related, fixes for flakes that occurred in CI runs for this PR _itself_ (and that have been seen in CI runs elsewhere too)

<details>
  <summary> <code>signals_test</code> failure logs for posterity </summary>

```  
  stop-terminate-4lf2q : Failed Stopped with strategy 'Stop'
    signals_test.go:44: 
        	Error Trace:	/home/runner/work/argo-workflows/argo-workflows/test/e2e/signals_test.go:44
        	            				/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:68
        	            				/home/runner/work/argo-workflows/argo-workflows/test/e2e/fixtures/then.go:43
        	            				/home/runner/work/argo-workflows/argo-workflows/test/e2e/signals_test.go:36
        	Error:      	Not equal: 
        	            	expected: "Succeeded"
        	            	actual  : "Running"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(v1alpha1.NodePhase) (len=9) "Succeeded"
        	            	+(v1alpha1.NodePhase) (len=7) "Running"
        	            	 
        	Test:       	TestSignalsSuite/TestStopBehavior
=== FAIL: SignalsSuite/TestStopBehavior
```
  
</details>

### Modifications

- `TestStopBehavior` in particular was flaking in checking onExit (all examples above are on the exact same line), so bumped that specifically
  - did not bump `killDuration` entirely (as #11064 did) as that bumps lots of other waits and makes the whole test suite a good bit longer
    - we may want to reduce this in some places and have more targeted wait times in order to reduce total test time
    - and may want to have a different wait on CI vs. local as well

- `TestStatusCondition` flaked on this PR (see [below comment](https://github.com/argoproj/argo-workflows/pull/11753#issuecomment-1707712532)), so bumped its wait as well

- `make codegen` flaked on this PR (see [below comment](https://github.com/argoproj/argo-workflows/pull/11753#issuecomment-1709026360)), so fixed that as well

- and bumped a timeout for another E2E flake on `make wait`
  - it's timed out a few times, so bump it up one minute to 5m
    - examples: [1](https://github.com/argoproj/argo-workflows/actions/runs/6101699486/job/16558698083?pr=11766)
      - can't seem to find another example but I've definitely seen it more than once before

### Verification

This is only reproducible on CI unfortunately 

### Future Work

As mentioned above:
1. More granular `killDuration` / wait per test as they increase total test time
1. Different wait times on CI vs local

Also:
1. Bump k8s swagger as mentioned [below](https://github.com/argoproj/argo-workflows/pull/11753#issuecomment-1709026360)
1. Authenticate some of the GH requests to get rate limited less? It would be great if GH recognized it was coming from itself and increased limits without needing to re-auth

### CODE REVIEW

**Comment by agilgur5** [comment]
Ya gotta be kidding me, a _different_ test [flaked](https://github.com/argoproj/argo-workflows/actions/runs/6091465134/job/16528122001?pr=11753) 😭 

also looks to be a timeout issue though, but in a completely different E2E test suite

**Comment by agilgur5** [comment]
adjfklas;dfk, `StopBehavior` failed [again](https://github.com/argoproj/argo-workflows/actions/runs/6093861532/job/16534290978?pr=11753) despite the bump... 😐 

Gonna bump it once more...

**Comment by agilgur5** [comment]
so all the tests passed.... and then [Codegen failed](https://github.com/argoproj/argo-workflows/actions/runs/6094143833/job/16535230915?pr=11753)......... the whack-a-mole is real....

<details>
  <summary> Test logs for posterity </summary>
  
```
go run ./hack/swagger kubeifyswagger dist/swaggifed.swagger.json dist/kubeified.swagger.json
panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main.getKubernetesSwagger()
	/home/runner/work/argo-workflows/argo-workflows/hack/swagger/kubeifyswagger.go:90 +0xe5
main.kubeifySwagger({0x7ffc2e045c59?, 0x1704f78?}, {0x7ffc2e045c75, 0x1b})
	/home/runner/work/argo-workflows/argo-workflows/hack/swagger/kubeifyswagger.go:28 +0x3ca
main.main()
	/home/runner/work/argo-workflows/argo-workflows/hack/swagger/main.go:10 +0x85
exit status 2
make: *** [Makefile:651: dist/kubeified.swagger.json] Error 1
```

</details>

From the test logs, it is failing on [`make dist/kubeified.swagger.json`](https://github.com/argoproj/argo-workflows/blob/595ab4bdecd57844120f401af4797d4be09698ca/Makefile#L650) with [this line](https://github.com/argoproj/argo-workflows/blob/595ab4bdecd57844120f401af4797d4be09698ca/hack/swagger/kubeifyswagger.go#L88) specifically erroring on decoding k8s JSON.
It's erroring on a `<` -- i.e. the [`curl`](https://github.com/argoproj/argo-workflows/blob/595ab4bdecd57844120f401af4797d4be09698ca/Makefile#L633) for this got back HTML instead of JSON. The full HTML is not output but it's likely from a rate limit error or something from GitHub. Some 400+ HTTP status code probably.

The `recurl.sh` script [does not handle](https://github.com/argoproj/argo-workflows/blob/595ab4bdecd57844120f401af4797d4be09698ca/hack/recurl.sh#L9) `curl` getting a bad status code, so will need to modify that slightly to account not just for `curl` failing but for the response being a bad status code as well.

**Comment by agilgur5** [comment]
All green checks has never looked so good 😭 🎉 🚀

**Review by jmeridth — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
For reference, my hypothesis is that we're getting some of these test flakes in CI specifically perhaps because the CI runner is bottlenecking on CPU or memory. The standard runner is [2 core CPU + 7 GB RAM](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).
Given that CI is running DinD with a k3d cluster and parallelized tests, I would be surprised if CPU _isn't_ maxed out and memory might be close to max. I typically give my `devcontainer` up to 6 CPU cores and 8GB RAM, as an anecdotal comparison.

With max CPU, everything takes longer and I/O is waiting on CPU. There would also be more CPU pre-emption and switching (although I don't quite know how the goroutine implementation handles this).

With both of those scenarios, it would roughly make sense why CI needs longer waits etc, as the CPU just can't get to everything timely.

Just a hypothesis. Either way, we can't increase the runner size in default OSS. Though I wonder if GitHub might grant an exception a large CNCF project.

**Pull request merged**
