### PR TITLE
chore: bump github.com/Azure/azure-sdk-for-go/sdk/storage/azblob from 1.2.1 to 1.3.0

### PR DESCRIPTION
**Pull request by roelarents**
Bumps [github.com/Azure/azure-sdk-for-go/sdk/storage/azblob](https://github.com/Azure/azure-sdk-for-go) from 1.2.1 to 1.3.0.
- [Release notes](https://github.com/Azure/azure-sdk-for-go/releases)
- [Changelog](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/release.md)
- [Commits](https://github.com/Azure/azure-sdk-for-go/compare/sdk/storage/azblob/v1.2.1...sdk/storage/azblob/v1.3.0)

Fix for [a data race issue in azure azblob sdk](https://github.com/Azure/azure-sdk-for-go/issues/22156#issuecomment-1893121130).

### Motivation

Update azure-sdk-for-go/sdk/storage/azblob to the latest version.

Dependabot would normally do this, but it has been explicitly [disabled](https://github.com/argoproj/argo-workflows/pull/10509#issuecomment-1427081626) once and cannot be enabled again.

### Modifications

A version update in go.mod. Ran `go mod tidy`.

### Verification

Tested by:
* make test

### CODE REVIEW

**Comment by agilgur5** [comment]
Replaces #12532

**Review by agilgur5 — COMMENTED** [review]
> Tested by:

Were you able to test that this fixed the issue you were having?

**Comment by roelarents** [comment]
not yet. i intend to patch 3.5.4 tomorrow or next week and run it in production. since it is not easily reproducible

**Comment by roelarents** [comment]
A requirement for https for azure blob connections with shared key credentials was added In 1.3.0, which breaks our test setup.
It [will be reverted in the next release](https://github.com/Azure/azure-sdk-for-go/issues/21841#issuecomment-1948041513). I will wait for that.

**Comment by agilgur5** [comment]
Superseded by #12915

**Pull request closed without merging**
