### PR TITLE
fix: Add readiness check to controller. Fixes #8283

### LINKED ISSUE #8283: v3.3.1: only the leader workflow-controller pod can expose metrics.
## Checklist

 

* [ ] Double-checked my configuration.
* [ ] Tested using the latest version.
* [ ] Used the Emissary executor.

## Summary

We upgraded argo to 3.3.1 from 3.1.3, There are 2  workflow-controller replica pods 
somehow after upgrade, only the leader workflow-controller pod can expose metrics. 

What version are you running? v3.3.1

## Diagnostics

From our prometheus server UI, it shows one of the workflow-controller pod's metrics target DOWN  with error: Get "http://10.127.217.135:9090/metrics": dial tcp 10.127.217.135:9090: connect: connection refused
While the other pod(the leader pod) shows UP, status is ok. 

We tried run "wget" to service endpoint workflow-controller-metrics port 9090 (from a testing pod), it could intermittently get metrics result back, and half the time it returns error "wget: can't connect to remote host (172.20.116.209): Connection refused"

no related errors found in pod log.

```bash

# sometimes it can get result back
 $ wget http://workflow-controller-metrics.argo:9090/metrics
Connecting to workflow-controller-metrics.argo:9090 (172.20.116.209:9090)
saving to 'metrics'
metrics              100% |*************************************************************************************************************************| 23326  0:00:00 ETA
'metrics' saved

# sometimes connection refused
$ wget http://workflow-controller-metrics.argo:9090/metrics
Connecting to workflow-controller-metrics.argo:9090 (172.20.116.209:9090)
wget: can't connect to remote host (172.20.116.209): Connection refused

```
Argo runs in our multiple eks clusters, we upgraded argo to v3.3.1 in two clusters, both have the same issue. the rest clusters with argo v3.1.3 does not have this problem.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Fixes #8283

### CODE REVIEW

**Review by sarabala1979 — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
This can go in v3.3.2

**Comment by jakubtomiak97** [comment]
Should this be deployed everywhere or reverted? As I can see this PR still present just on the v3.3.2.

**Comment by agilgur5** [comment]
> Should this be deployed everywhere or reverted?

It looks like this was reverted in #8454

**Pull request merged**
