### PR TITLE
build(cli): add riscv64 support

### PR DESCRIPTION
**Pull request by mengzhuo**
### Motivation

As riscv growing popularity and being adopted by more projects
https://github.com/carlosedp/riscv-bringup 

and commercial Cloud provider like Scaleway https://www.scaleway.com/en/news/scaleway-launches-its-risc-v-servers-in-the-cloud-a-world-first-and-a-firm-commitment-to-technological-independence/

It's possible to run argo workflow by riscv users.

### Modifications

Adds riscv64 support

### Verification

 ```
make dist/argo-linux-riscv64 && ./dist/argo-linux-riscv64
```
argo prints help verbose.

### CODE REVIEW

**Comment by Joibel** [comment]
This will only support the CLI on riscV, but that's the only component we support on non amd64/arm64 for other less popular architectures.
It will not allow the workflow's kubernetes components to run on riscV.
Anyway, LGTM

**Review by Joibel — APPROVED** [review]

**Comment by Joibel** [comment]
@mengzhuo, you will need to sign your commits according to https://github.com/argoproj/argoproj/blob/main/community/CONTRIBUTING.md. You will need to rewrite this commit to make the DCO check pass.

**Comment by agilgur5** [comment]
> This will only support the CLI on riscV, but that's the only component we support on non amd64/arm64 for other less popular architectures.

^This, see also #12067 for the rest

**Review by agilgur5 — APPROVED** [review]
LGTM. There is existing precedent for CLI binaries, as Alan noted

**Pull request merged**
