### PR TITLE
docs: Add Bytedance, Determined, and Pipekit to USERS.md

### PR DESCRIPTION
**Pull request by terrytangyuan**
These are additional organizations I have been working with that use [Couler](https://github.com/couler-proj/couler) [(complete list here)](https://github.com/couler-proj/couler/blob/master/ADOPTERS.md) and should be added here as well.

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Review by simster7 — APPROVED** [review]
LGTM, although I'm thinking @alexec or @edlee2121 might have thoughts on adding orgs that the submitter is not directly a part of, so I'll wait to merge

**Comment by terrytangyuan** [comment]
No problem. Note that the current open sourced version of Couler only supports Argo Workflows so these are "semi-direct" users of Argo Workflows as well.

**Comment by alexec** [comment]
I think we should really have the users within those orgs add them. I think it is polite.

**Comment by terrytangyuan** [comment]
They may be unaware of the existence of this doc but they all have signed off either on the PR or offline with me when they adopted Couler. I can either tag/cc them here if needed or we can close this one for now and see if they will add themselves when they get a chance. Please let me know what to proceed from here.

**Comment by terrytangyuan** [comment]
Closing this for now as otherwise the orgs are not “officially” added as the users. Thanks for your thoughts on this! Let’s wait for others to add themselves then.

**Pull request closed without merging**
