### PR TITLE
fix: for pod that's been GC'ed we need to get the log from the artifact

### LINKED ISSUE #9434: 3.4-rc2 - Workflows UI can no longer get logs (s3)
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary
This occurs following an upgrade from workflows 3.3.9 to 3.4-rc2.

Logs are still correctly sent to s3 by argo workflows, I can see main.log in s3 and the contents of the log file are correct.

However, once the workflow has finished the pod has been archived, the logs field is now empty in the UI.
Clicking `Try getting logs from the artifacts` results in `Internal Server Error`

The argo-server logs show this error, only when trying to clikc the 'try getting logs from artifacts' link.: `level=error msg="Artifact Server returned internal error" error="artifact not found: main-logs"`

No errors at all when just trying to view in the UI. None on the controller either.

Note, as I'm using IRSA, I have the following patch on my argo-server:
```
    spec:
      securityContext:
        fsGroup: 65534
```

What version are you running? 3.4-rc2

Config summary:
controller-configmap:
```yaml
  artifactRepository: |
    # archiveLogs will archive the main container logs as an artifact
    archiveLogs: true

    s3:
      endpoint: s3.amazonaws.com
      bucket: my-bucket-name
      region: us-east-1
      insecure: false
      keyFormat: "my-artifacts\
        /{{workflow.creationTimestamp.Y}}\
        /{{workflow.creationTimestamp.m}}\
        /{{workflow.creationTimestamp.d}}\
        /{{workflow.name}}\
        /{{pod.name}}"
      useSDKCreds: true
```

The argo-server ServiceAccount has the `eks.amazonaws.com/role-arn` annotation as always.

---

**Message from the maintainers**:

Impacted by this regression? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by juliev0**
Signed-off-by: Julie Vogelman <julie_vogelman@intuit.com>

Fixes #9434 

This fixes the use case that a Pod has been GC'ed and enables the UI to get the log from the artifact in this case.

This reverts a change made to this function [here](https://github.com/argoproj/argo-workflows/commit/3fdf30d9f9181d74d81ca3184b53bbe661ecb845#).

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by juliev0** [comment]
Note there's a very rare case in which isPendingOrRunning=true and the Pod gets deleted immediately after, such that by the time we make the call on line 216 it fails because the Pod's been deleted. Seems rare enough that I'm not sure we want to worry about it, though.

**Comment by juliev0** [comment]
converting to draft for the moment just so I can do testing with different types of Workflows just to make sure no issues

**Comment by juliev0** [comment]
> converting to draft for the moment just so I can do testing with different types of Workflows just to make sure no issues

done. tested under various different circumstances different workflows

**Comment by juliev0** [comment]
@terrytangyuan Thank you for being so on top of these PRs!

**Comment by terrytangyuan** [comment]
> @terrytangyuan Thank you for being so on top of these PRs!

Sure. Thanks for your fixes!

**Pull request merged**
