### PR TITLE
feat(server)!: Remove managed fields and self-link for APIs. Fixes #5741

### LINKED ISSUE #5741: Hide managed fields in the UI
They are quite annoying.

### PR DESCRIPTION
**Pull request by alexec**
The primary benefit of managed fields is that they allow server-side apply (SSA) to understand who owns which field and therefore perform conflict resolution and potentially support auditing/blame.

But:

* It is only useful if you have v1.18. 
* Does not support sub-resources (as of v1.21).
* It's a beta feature.
* It's only useful if you use SSA. 
* It's only useful if you have a concept of field ownership AND you plan to implement code related to it.
* It creates a lot of visual noise that's terrible UX.
* 2x API payload size.
* 2x memory usage.
* Stripping them is easily reversible..

**It provides no benefits and incurs significant cost.**

Note - I would not say this for Argo CD - where it will definitely needs to be supported.

References:

* https://kubernetes.io/blog/2020/04/01/kubernetes-1.18-feature-server-side-apply-beta-2/
* https://www.youtube.com/watch?v=P12z8X-qhis
* https://github.com/kubernetes/kubernetes/issues/90066
* https://www.reddit.com/r/kubernetes/comments/ixnf05/hide_managed_fields/
* https://stackoverflow.com/questions/62077977/kubectl-get-o-yaml-is-it-posible-to-hide-metadata-managedfields

### CODE REVIEW

**Comment by alexec** [comment]
Re-running due to failed lint

**Review by terrytangyuan — COMMENTED** [review]
If we are creating workflows in resource templates, there will be issues since currently executor for resource type templates depends on selfLinks of the created objects.

**Comment by alexec** [comment]
@jessesuen you wanted me to do some more research on this. I actually now feel more strongly about removing managed fields. The cost is high, there is not benefit, the decision is reversible.

**Comment by alexec** [comment]
Before:

image

After:

**Comment by alexec** [comment]
Closing:

* No evidence it is faster. Maybe slower.
* Poor risk vs benefit ratio (high risk this breaks stuff vs small benefit of hiding managed fields).

Lets see if we can come up with a UI only solution.

**Pull request closed without merging**
