### PR TITLE
docs: add a README to the Nixfiles, improve formatting

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

There is already documentation for this, so just link to [the existing docs](https://argoproj.github.io/argo-workflows/running-nix/)
- just handy to have a back-link for those less familiar with Nix and who stumble upon it
- Similar to #10969

### Modifications

- add a README with a one-line link to `dev/nix/`

- also improve some grammar and formatting in the Nix docs
  - use code backticks for all commands
  - use markdown convention of using `1.` for all items of an ordered list and having the renderer determine the numbering
  - use the name of the doc (Running Locally) instead of "this"
    - more consistent with the rest of the docs, as well as k8s style guide: https://kubernetes.io/docs/contribute/style/style-guide/#links
    - also merge 1 and 2 as they're both mentioned in Running Locally
  - separate run-on sentence

### Verification

Double-checked that the relative link worked locally

### CODE REVIEW

**Comment by terrytangyuan** [comment]
cc @isubasinghe

**Review by sarabala1979 — APPROVED** [review]

**Comment by sarabala1979** [comment]
@isubasinghe  sorry I didn't realize Terry tagged you. Please review and comment it.

**Comment by agilgur5** [comment]
I didn't change any content, so thought it'd be ok for anyone to review, otherwise would cc @isubasinghe myself who knows Nix better than I currently do

**Comment by isubasinghe** [comment]
LGTM since its just markdown

**Pull request merged**
