### PR TITLE
chore: Show description for intermediate parameters - #11353 ui enhan…

### LINKED ISSUE #11353: UI: Show description for intermediate parameters
# Summary

UI: Show description for intermediate parameters

# Use Cases

We have users of our Argo workflows that will only interact with it through the UI. They won't be writing workflows and won't be familiar with the yaml source of these workflows. They'll only be submitting new workflows from workflow templates in the UI.

I have created a workflow template with a suspend template and intermediate parameters, like so:

```yaml
    - name: wait-for-approval
      inputs:
        parameters:
          - name: approve
            default: 'NO'
            enum:
              - 'YES'
              - 'NO'
            description: >-
              Choose YES to continue workflow and activate on the
              production network
      outputs:
        parameters:
          - name: approve
            valueFrom:
              supplied: {}
      metadata: {}
      suspend:
        duration: 12h
```

I was hoping the description would show up in the dialog box to resume the workflow, but it does not. It would be useful if the UI displayed the description in a tooltip like it does for the parameters you see when you submit a new workflow from a workflow template.

intermediate parameters screenshot

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by sonbui00**
Fixes #11353

### Motivation
Show useful information for the approver

### Modifications
- Show description tooltip

### Verification
Tested locally/manually

#### Example
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: suspend-template-
spec:
  entrypoint: suspend
  templates:
  - name: suspend
    steps:
    - - name: build
        template: whalesay
    - - name: approve
        template: approve
    - - name: wait-for-approval
        template: wait-for-approval
    - - name: delay
        template: delay
    - - name: release
        template: whalesay

  - name: approve
    suspend: {}

  - name: wait-for-approval
    inputs:
      parameters:
        - name: approve
          default: 'NO'
          enum:
            - 'YES'
            - 'NO'
          description: >-
            Choose YES to continue workflow and activate on the
            production network
    outputs:
      parameters:
        - name: approve
          valueFrom:
            supplied: {}
    metadata: {}
    suspend:
      duration: 12h


  - name: delay
    suspend:
      duration: "20"    # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"

  - name: whalesay
    container:
      image: alpine
      command: [echo]
      args: ["hello world"]
```

### CODE REVIEW

**Comment by toyamagu-2021** [comment]
Great!
I've checked these changes working in #11532.
image

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Thank you!

**Comment by artem-zherdiev-ingio** [comment]
Hi, is the fix already on v3.5.5? Because it seems not.

**Comment by agilgur5** [comment]
> Hi, is the fix already on v3.5.5?

> feat(ui): Show description for intermediate parameters in tooltip. Fixes #11353 

It's not a fix, it's a feature, so it'll be out in the next minor release.

**Pull request merged**
