### PR TITLE
feat: Support ListObjects() for Alibaba OSS artifact driver

### PR DESCRIPTION
**Pull request by terrytangyuan**
This is to support data sourcing and transformation with the `data` template implemented in https://github.com/argoproj/argo-workflows/pull/4958. 

cc @simster7 @alexec 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
yes please, @simster7 can we create a v1.1 ticket for GCP too please?

**Comment by simster7** [comment]
We have intentionally left this off as we want to keep the scope of `data` v1.0 small. I will add this once I add the rest of the drivers on v1.1

**Comment by simster7** [comment]
Thanks for submitting thought

**Comment by terrytangyuan** [comment]
We cannot test out this feature for OSS though without this implementation.

**Comment by alexec** [comment]
@simster7 I think we should accept this PR. The onus would be on @terrytangyuan to implement and test because we do not run OSS ourselves.

**Comment by simster7** [comment]
> The onus would be on @terrytangyuan to implement and test because we do not run OSS ourselves.

Sure, fair point. I had wanted to add all the drivers in one atomic request, but this makes sense

**Comment by simster7** [comment]
@terrytangyuan Do you plan on testing `data` off of master/latest soon? Otherwise I will delay merging this until I have written the rest of the drivers

**Comment by terrytangyuan** [comment]
Yes I was planning to test it out once merged anyways.

**Review by simster7 — APPROVED** [review]

**Pull request merged**
