### PR TITLE
fix(controller): fix pod stuck in running when using podSpecPatch and emissary

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes https://github.com/argoproj/argo-workflows/issues/7406
I tested via unit test.

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

### CODE REVIEW

**Comment by Bobgy** [comment]
I might need some help understanding the test failure: https://github.com/argoproj/argo-workflows/runs/4517399752?check_suite_focus=true

The error message is not very intuitive:

```
    agent_test.go:83: 
        	Error Trace:	agent_test.go:83
        	            				then.go:66
        	            				then.go:41
        	            				agent_test.go:64
        	Error:      	Should be true
        	Test:       	TestAgentSuite/TestParallel
=== FAIL: AgentSuite/TestParallel
FAIL	github.com/argoproj/argo-workflows/v3/test/e2e	13.146s
FAIL
make: *** [Makefile:490: test-functional] Error 1
Error: Process completed with exit code 2.
```

**Comment by Bobgy** [comment]
OK, after a new push, all tests are passing!

**Review by alexec — CHANGES_REQUESTED** [review]
failing test due to new bug, please fix

**Comment by Bobgy** [comment]
Hmm, I guess I fixed the failure.
However, I believe my change makes the test https://github.com/argoproj/argo-workflows/blob/master/test/e2e/testdata/sidecar-injected-kill-annotation-workflow.yaml useless, because now podSpecPatch is no longer a good way to simulate injected sidecars.

Any suggestions?

**Review by alexec — DISMISSED** [review]

**Comment by alexec** [comment]
> However, I believe my change makes the test https://github.com/argoproj/argo-workflows/blob/master/test/e2e/testdata/sidecar-injected-kill-annotation-workflow.yaml useless, because now podSpecPatch is no longer a good way to simulate injected sidecars.

This is as important test, do you have any other suggestions?

**Comment by Bobgy** [comment]
I understand it's very complex to set up a webhook for e2e tests, so the best solution I came up with is adding a special annotation for test purposes only, which will have equivalent behavior of pod spec patch, but applied at the very end.

What do you think? Any easier ways to do this?

**Comment by alexec** [comment]
Just refreshing, we need to apply the patch before we modify the command to insert the emissary. Otherwise, the patch mangles the command - removing emissary binary from it and preventing it from running. 

But, we use patch in the test. 

So clearly your code change is correct, and the test needs fixing. But question is - how?

**Comment by alexec** [comment]
Coming back to this. Can you skip the tests in the PR? Create a new tech debt issue to fix the tests.

**Comment by Bobgy** [comment]
Thank you for the flexibility!
I created https://github.com/argoproj/argo-workflows/issues/7422 to track the tech debt.

**Comment by alexec** [comment]
Please sync with master.

**Comment by Bobgy** [comment]
Everything ready : )

**Comment by Bobgy** [comment]
Hi @alexec, is there anything else you want for this PR?

**Review by alexec — APPROVED** [review]

**Pull request merged**
