### PR TITLE
docs: Conditionals example improved with complex syntax

### PR DESCRIPTION
**Pull request by sylock**
Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by sylock** [comment]
Related to #860

**Review by simster7 — APPROVED** [review]
Thanks!

**Comment by simster7** [comment]
@sylock Looks like you'll need to run `make docs`. Also, please make sure to sign your commits by using the `-s` flag: `git commit -asm "message"`

**Review by alexec — CHANGES_REQUESTED** [review]
`make codegen` needs running

**Comment by sylock** [comment]
I'm sorry but make codegen is still not working from my side:
- Do you have some documentation about how to setup properly a dev environment
- It would be nice to have an easier entry barrier to contributing, especially for documentation (I'm not a golang dev)

```
make codegen
error: current-context is not set
# GIT_TAG=v2.10.0-rc1, GIT_BRANCH=master, GIT_TREE_STATE=clean, VERSION=latest, DEV_IMAGE=true, K3D=false
go mod vendor
warning: ignoring symlink /home/sylock/dev/argo/docs/examples
go install ./vendor/github.com/go-swagger/go-swagger/cmd/swagger
go install ./vendor/github.com/gogo/protobuf/protoc-gen-gogo
go install ./vendor/github.com/gogo/protobuf/protoc-gen-gogofast
go install ./vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
go install ./vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
go install ./vendor/k8s.io/code-generator/cmd/go-to-protobuf
go install ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
go install ./vendor/sigs.k8s.io/controller-tools/cmd/controller-gen
rm -Rf vendor
go get golang.org/x/tools/cmd/goimports@v0.0.0-20200630154851-b2d8b0336632
go: found golang.org/x/tools/cmd/goimports in golang.org/x/tools v0.0.0-20200630154851-b2d8b0336632
./hack/generate-proto.sh
+ go mod vendor
warning: ignoring symlink /home/sylock/dev/argo/docs/examples
./hack/generate-proto.sh: line 7: GOPATH: unbound variable
make: *** [Makefile:277: proto] Error 1
``

**Comment by alexec** [comment]
> I'm sorry but make codegen is still not working from my side:

I tend to copy the patch and use `git apply` to update codegen when the CI prints the diffs.

**Comment by simster7** [comment]
@sylock I ran `codegen` for you

**Review by alexec — APPROVED** [review]

**Pull request merged**
