### PR TITLE
docs: change from v.3.5.2 suffix to release-3.5.2

### PR DESCRIPTION
**Pull request by jmeridth**
Relates to #12414 

### Motivation

Backport doc changes

### Modifications

change from tag to branch since backported changes will be to the branch and also this matches what ArgoCD is doing to help keep our projects in sync

grep command I ran locally (OSX) to update the urls

```bash
 grep -ilr 'https:\/\/argo-workflows.readthedocs.io\/en\/v3.5.2' * | xargs -I@ sed -i '' 's/https:\/\/argo-workflows.readthedocs.io\/en\/v3.5.2/https:\/\/argo-workflows.readthedocs.io\/en\/release-3.5.2/g' @
```

### CODE REVIEW

**Review by agilgur5 — COMMENTED** [review]
Should we rather use `release-3.5` with just the minor? As discussed in https://github.com/argoproj/argo-workflows/pull/12450#issuecomment-1876232049 and https://github.com/argoproj/argo-workflows/issues/12414#issuecomment-1876216461

**Comment by jmeridth** [comment]
I thought we realized those pointed to 3.5.0 and 3.4.0. So not the latest docs on the minor version. Right?

**Comment by jmeridth** [comment]
Ah. If we sync the branch we'll be good. Ok. Will close this PR and do one to release-3.5 branch.

**Comment by jmeridth** [comment]
@agilgur5 continued in #12462

**Pull request closed without merging**
