### PR TITLE
chore(controller): remove a Go 1.15 env var that no longer exists

### PR DESCRIPTION
**Pull request by agilgur5**
Follow-up to #6471, stumbled upon this while writing #12609

### Motivation

- per the in-line linked issues (#5563, https://github.com/golang/go/issues/39568), this was a temporary workaround in Go 1.15 that was removed in Go 1.16
  - we are currently [on Go 1.21](https://github.com/argoproj/argo-workflows/blob/6a39edf366319a40d37ccf406fe27dcee3d15705/go.mod#L3)
  - this was missed in #6471

### Modifications

Remove no longer existent `GODEBUG="x509ignoreCN=0"` env var

### Verification

The flag no longer exists, not really sure how to test that actually 🤔 You would think the build would break with a no longer existent env var 🤷 But this env var is injected into the Executor container, so maybe Go just ignores it at run-time (vs. build-time)
Per the Go issue, the workaround env var was for a very specific cert: the 2019 AWS RDS CA. The cert was fixed on [AWS's side as well](https://github.com/golang/go/issues/39568#issuecomment-665863345), so shouldn't be an issue anymore on either side (Go or AWS RDS). That's specific enough that there isn't a way to add an E2E for that either without running in an outdated AWS env

### CODE REVIEW

**Comment by agilgur5** [comment]
Unrelated E2E test [failure](https://github.com/argoproj/argo-workflows/actions/runs/7762627421/job/21173452403?pr=12610) seems to be due to #12413, c.f. #12596

**Review by Joibel — APPROVED** [review]
LGTM

**Comment by agilgur5** [comment]
Merged `main` to fix E2Es as #12596 is now merged

**Review by isubasinghe — APPROVED** [review]
simple enough! ship it

**Comment by isubasinghe** [comment]
Welp, test is failing

**Comment by agilgur5** [comment]
@isubasinghe is there a reason you've been merging `main` as you did in this PR and a few others? There were/are no merge conflicts, so it can be approved and merged without being rebased etc. Merging `main` first also causes CI to re-run (which failed this time around but didn't before, so I imagine is a flake) and modifies the history as well.

**Comment by agilgur5** [comment]
> (which failed this time around but didn't before, so I imagine is a flake)

Passed on retry, so indeed was a flake

**Comment by isubasinghe** [comment]
> @isubasinghe is there a reason you've been merging `main` as you did in this PR and a few others? There were/are no merge conflicts, so it can be approved and merged without being rebased etc. Merging `main` first also causes CI to re-run (which failed this time around but didn't before, so I imagine is a flake) and modifies the history as well.

Honestly, just to be uber sure that the test will still pass. Probably just a tad too paranoid though hahaha

**Comment by agilgur5** [comment]
> Honestly, just to be uber sure that the test will still pass.

If you're concerned about that, there's another feature that [a contributor brought up before](https://cloud-native.slack.com/archives/C0510EUH90V/p1701288620675009?thread_ts=1700702475.578759&cid=C0510EUH90V), merge queues, that handle automatically rebasing before a PR is merged. We'd need an admin to enable it for the repo though

**Comment by isubasinghe** [comment]
> > Honestly, just to be uber sure that the test will still pass.
> 
> If you're concerned about that, there's another feature that [a contributor brought up before](https://cloud-native.slack.com/archives/C0510EUH90V/p1701288620675009?thread_ts=1700702475.578759&cid=C0510EUH90V), merge queues, that handle automatically rebasing before a PR is merged. We'd need an admin to enable it for the repo though

Oh that would be a great idea, I guess that would be @terrytangyuan or @sarabala1979 ?

**Comment by terrytangyuan** [comment]
We tried it before and it was buggy.

**Comment by agilgur5** [comment]
> it was buggy.

Can you elaborate?

**Comment by agilgur5** [comment]
Thanks for the details.
The feature is supposed to not merge if the PR fails tests, which I imagine may have happened a lot more frequently in the past due to flakes (but correct me if I'm wrong, I'm not sure what the situation was at the time you tried it).
The incorrect ordering for a, er, queue, does seem like a problem 😕 How long ago was it last tried? I'm hoping GitHub has fixed any bugs in the interim (especially correctness ones like that, but who knows, GH certainly has years old issues). I also wonder if flakes might have changed ordering

**Comment by agilgur5** [comment]
Hmm I was thinking we can make the queue optional, then Approver+ could use them if they wanted extra safety. So that limits its scope and potential issues/bugs. I think it can be made optional since [this section of the docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue) says you can add it as a required check, but it doesn't have to be required if enabled

**Pull request merged**
