### PR TITLE
chore: Add agilgur5 and isubasinghe to approvers

### PR DESCRIPTION
**Pull request by terrytangyuan**
Based on membership meeting discussions this month.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
cc @argoproj/argo-workflows-approvers

**Comment by agilgur5** [comment]
> Based on membership meeting discussions this month.

For reference: https://github.com/argoproj/argoproj/pull/280

> docs:

Should this be a `chore:`? The previous Reviewer PR was one #12154 
It's technically not part of the rendered docs (I think CNCF might use it though? I remember that being mentioned somewhere in the `argoproj` issues or something)

**Review by agilgur5 — APPROVED** [review]
LGTM other than the `chore:` part. 🚀

**Comment by terrytangyuan** [comment]
Oops auto merged. I don't think it's a big deal though

**Pull request merged**
