### PR TITLE
fix: Switch InsecureSkipVerify to true

### PR DESCRIPTION
**Pull request by simster7**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
I'm still getting 


```
{"code":14,"message":"connection closed"}
```

**Comment by simster7** [comment]
Yeah, same. Looking into it

**Comment by alexec** [comment]
It works for me if I revert this:

```
        dialOpts := []grpc.DialOption{
                grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(MaxGRPCMessageSize)),
-               grpc.WithInsecure(),
        }
+       if as.tlsConfig != nil {
+               dialOpts = append(dialOpts, grpc.WithTransportCredentials(credentials.NewTLS(as.tlsConfig)))
+       } else {
+               dialOpts = append(dialOpts, grpc.WithInsecure())
+       }
+

``

**Comment by alexec** [comment]
And I run this

```
./dist/argo server --secure --port 2345
```

I don't seem to need GODEBUG=x509ignoreCN=0.

**Comment by simster7** [comment]
@alexec I reverted #5550 and it works. I had done so in my local from an earlier test bud hadn't noticed. I just tested and it also works for me. We should be good to go.

**Review by alexec — APPROVED** [review]

**Pull request merged**
