### PR TITLE
test: Manual Retry (CLI) Failed Workflow

### PR DESCRIPTION
**Pull request by Garett-MacGowan**
### Motivation

~As part of my investigation and testing for https://github.com/argoproj/argo-workflows/pull/12574, I noticed that workflow update conflicts did not result in the workflow being marked as errored. I believe workflows should be marked as errored upon an update conflict. Additionally, marking workflows with conflicting updates as errored makes it easier to test the issue described in #12574.~

**Edit:** 
As Joibel pointed out, I was mistaken in marking the workflow as errored upon conflict. I didn't notice the `!` infront of `apierr.IsConflict()`, so I interpreted it wrong.

I think the test is still useful.

### Modifications

~Added `persistWorkflowConflictErr(ctx, wfClient, err)` and a call to it in `persistUpdates`~

### Verification

Added test for manual workflow retry (in attempt to reproduce the issue described in #12574). This test is unable to reproduce the issue, though it is still a useful test.

### CODE REVIEW

**Comment by Garett-MacGowan** [comment]
@juliev0 Let me know what you think of this.

@shuangkun This may be of use in your investigation.

**Comment by Joibel** [comment]
This doesn't feel correct. A conflict is an expected event in our scenario where we have both the argo-server and workflow-controller potentially writing to the same Workflow object concurrently. Marking those workflows as errored feels likely to cause inadvertant errors.

The most obvious case to me would be a Stop or Terminate from the argo-server.

**Comment by Garett-MacGowan** [comment]
> This doesn't feel correct. A conflict is an expected event in our scenario where we have both the argo-server and workflow-controller potentially writing to the same Workflow object concurrently. Marking those workflows as errored feels likely to cause inadvertant errors.
> 
> The most obvious case to me would be a Stop or Terminate from the argo-server.

Thanks for the feedback. I'll look into this.

**Comment by shuangkun** [comment]
> @juliev0 Let me know what you think of this.
> 
> @shuangkun This may useful in your investigation.


I think there is a problem with this. This change cannot solve my current problem. The best way is that the workflow has been truly completed when the customer can retry.

**Comment by Garett-MacGowan** [comment]
> > @juliev0 Let me know what you think of this.
> > @shuangkun This may useful in your investigation.
> 
> I think there are something wrong with this. This change cannot solve my current problem. The best way is that the workflow has been truly completed when the customer can retry.

I'm not suggesting that this fixes your issue. The test came however, attempts to reproduce your issue. I haven't been able to so far.

**Comment by shuangkun** [comment]
> > > @juliev0 Let me know what you think of this.
> > > @shuangkun This may useful in your investigation.
> > 
> > 
> > I think there are something wrong with this. This change cannot solve my current problem. The best way is that the workflow has been truly completed when the customer can retry.
> 
> @shuangkun I'm not suggesting that this fixes your issue. The test case attempts to reproduce your issue. I haven't been able to so far.

Okay, thanks. I'll take a look

**Comment by Garett-MacGowan** [comment]
@Joibel Oops, I missed the `!` In `!apierr.IsConflict(err)`. What you're saying makes sense now. I see it performs a retry. Will remove.

@shuangkun's

**Comment by shuangkun** [comment]
> @Joibel Oops, I missed the `!` In `!apierr.IsConflict(err)`. What you're saying makes sense now. I see it performs a retry. Will remove.
> 
> @shuangkun update retry is limited. Are you seeing a `woc.log.Warnf("Update retry attempt %d failed: %v", attempt, err)` log

Yes, I have

**Comment by Garett-MacGowan** [comment]
> It's very creative to run the CLI in a Workflow. But is there something about what you're testing that it makes more sense to run it in a Workflow as opposed to testing the CLI directly? (which I notice we do in various tests [here](https://github.com/argoproj/argo-workflows/blob/main/test/e2e/cli_test.go#L829))

Apologies for being slow to respond. Been busy.

There's no reason other than it was the easiest for me to do since I didn't see the CLI testing utilities you've pointed out here. I can change if you think it makes sense to do so.

**Comment by juliev0** [comment]
> > It's very creative to run the CLI in a Workflow. But is there something about what you're testing that it makes more sense to run it in a Workflow as opposed to testing the CLI directly? (which I notice we do in various tests [here](https://github.com/argoproj/argo-workflows/blob/main/test/e2e/cli_test.go#L829))
> 
> Apologies for being slow to respond. Been busy.
> 
> There's no reason other than it was the easiest for me to do since I didn't see the CLI testing utilities you've pointed out here. I can change if you think it makes sense to do so.

I hate to bug you with that but I guess there is something to be said for consistency. Would you be up for that?

**Comment by Garett-MacGowan** [comment]
> > > It's very creative to run the CLI in a Workflow. But is there something about what you're testing that it makes more sense to run it in a Workflow as opposed to testing the CLI directly? (which I notice we do in various tests [here](https://github.com/argoproj/argo-workflows/blob/main/test/e2e/cli_test.go#L829))
> > 
> > 
> > Apologies for being slow to respond. Been busy.
> > There's no reason other than it was the easiest for me to do since I didn't see the CLI testing utilities you've pointed out here. I can change if you think it makes sense to do so.
> 
> I hate to bug you with that but I guess there is something to be said for consistency. Would you be up for that?

No problem. I'll make the change. Might not be for a little bit, but I'll get around to it!

**Comment by Garett-MacGowan** [comment]
@juliev0 `retry_test.go:168: You cannot use RunCli for tests that are not in TestCLISuite`. Permission to run CLI inside the container?

**Comment by Garett-MacGowan** [comment]
@juliev0 Let me know if this test works for you now. It has been greatly simplified.

**Review by juliev0 — APPROVED** [review]

**Comment by juliev0** [comment]
that works, thanks for this!

**Pull request merged**
