### PR TITLE
fix(server): Support validating template of exit hook. Fixes #13245

### LINKED ISSUE #13245: Template of `ExitHook` failed to resolve `{{workflow.failures}}`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Template of `ExitHook` failed to resolve `{{workflow.failures}}` as below: 
image

The same template works well if using `onExit`, but it is `DEPRECATED`.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-exit-handler-demo
spec:
  entrypoint: main
  onExit: exit-handler
  templates:
  - name: main
    steps:
    - - name: hello
        template: hello
  - name: hello
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo hello"]
  - name: exit-handler
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo {{workflow.failures}}"]
```

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-exit-handler-demo
spec:
  entrypoint: main
  hooks:
    exit:
      template: exit-handler
  templates:
  - name: main
    steps:
    - - name: fail
        template: fail
  - name: fail
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo hello > /dev/termination-log;exit 1"]
  - name: exit-handler
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo {{workflow.failures}}"]
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

### PR DESCRIPTION
**Pull request by jswxstw**
Fixes #13245

### Motivation

Template of `ExitHook` failed to resolve `{{workflow.failures}}`

### Modifications

Validate template of `OnExit` and `Hooks[exit]`

### Verification

Test submitting workflow  demo, and it succeeded.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-exit-handler-demo
spec:
  entrypoint: main
  hooks:
    exit:
      template: exit-handler
  templates:
  - name: main
    steps:
    - - name: hello
        template: hello
  - name: hello
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo hello"]
  - name: exit-handler
    container:
      image: alpine:3.18
      command: [sh, -c]
      args: ["echo {{workflow.failures}}"]
```

### CODE REVIEW

**Comment by agilgur5** [comment]
@jswxstw can you describe why the PR was closed too?

**Comment by jswxstw** [comment]
#13245 is duplicate with #12330 and it will be fixed by #12798.

**Comment by agilgur5** [comment]
The approaches are different though 🤔 I suppose let's continue in #12798 then since it has some tests

**Comment by jswxstw** [comment]
> The approaches are different though 🤔 I suppose let's continue in #12798 then since it has some tests

Sure, there are still many issues with this PR that I haven't considered.

**Pull request closed without merging**
