### PR TITLE
docs: Add link to Argo LinkedIn page

### PR DESCRIPTION
**Pull request by terrytangyuan**
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by terrytangyuan** [comment]
The LinkedIn page is something we are using officially for marketing. I believe it's managed by Argo SIG Marketing team.

**Review by hblixt — APPROVED** [review]
The LinkedIn ArgoProj page/account is managed by the Argo SIG marketing committee and posting there follows the same guidelines as for our other social accounts (e.g. twitter) with the goal of spreading information by and for the project. 
Vendor pitches/marketing are explicitly not allowed, so adding the link should be fine.

**Comment by alexec** [comment]
OK. That was my 1st objection addressed. My second concern is that it clutters docs the toolbar with a link most users won't want.

**Comment by alexec** [comment]
image

**Comment by hblixt** [comment]
> image

Can you group Blog/Slack/Twitter/LinkedIn under a "Social" drop-down?

**Comment by alexec** [comment]
Today, if we want it, I'd leave it where it is. Putting it in the nav will drive traffic there. It'll do so at the cost of other options. I'm not sure what the benefit is.

**Comment by terrytangyuan** [comment]
The nav bar indeed looks pretty long. Perhaps we can merge user/operator/developer guide into one dropdown for guide. Then another dropdown for socials like Slack/Twitter/LinkedIn.

**Review by alexec — APPROVED** [review]

**Pull request merged**
