### PR TITLE
feat: Support semaphore selectors. Fixes #7272

### LINKED ISSUE #7272: Add support for more granular and flexible synchronization mechanism of the workflows
# Summary

Add support for more granular and flexible synchronization mechanism of the workflow

# Use Cases

Today you can enforce your workflow concurrency only by 2 levels: workflow or template.
The proposal is to add an ability to create custom levels of synchronization based on workflow fields like labels or parameter values. It would be great to have an ability to enforce concurrently by some workflow specific fields like labels or params.

The interface can be the following: 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-wf-level-
spec:
  entrypoint: whalesay
  synchronization:
    semaphore:
      configMapKeyRef:
        name: my-config
        key: workflow
        parameters:
          - name: repo
            value: '{{ workflow.parameters.GIT_REPO }}'
          - name: sensor
            value: '{{ workflow.lables.events.argoproj.io/sensor }}'
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```

It should also fit well into the current implementation of semaphore synchronization.
I have checked and it looks like currently semaphore lock names are created in this way:
```go
fmt.Sprintf("%s/%s/%s/%s", ln.Namespace, ln.Kind, ln.ResourceName, ln.Key)
```
We can add an additional variable here that will hold the value of provided parameters concatenated together:
```go
// ln.Parameters = "repo=argoproj/argo-workflows&sensor=sensor-name"
fmt.Sprintf("%s/%s/%s/%s/%s", ln.Namespace, ln.Kind, ln.ResourceName, ln.Key, ln.Parameters)
```

I would like to submit a PR if you think it's good to have these synchronization capabilities.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by denis-codefresh**
Signed-off-by: Denis <denis@codefresh.io>

Fixes #7272

Introducing an extension to the current synchronization mechanism that allows concurrency enforcement by workflow fields like labels, params, annotations, etc. Can be applied to semaphore and mutex.

NOTE: The interface is not final and can be discussed

CRD example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: sync-wft-by-params
  labels: 
    argo.sensor: github
    argo.sensor-event: push
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
      - - name: main1
          template: sync-by-params
          arguments:
            parameters:
              - name: REPO_OWNER
                value: argoproj
              - name: REPO_NAME
                value: argo-workflows
              - name: GIT_BRANCH
                value: master
        - name: main2
          template: sync-by-params
          arguments:
            parameters:
              - name: REPO_OWNER
                value: denis-codefresh
              - name: REPO_NAME
                value: argo-workflows
              - name: GIT_BRANCH
                value: feature

    - name: sync-by-params
      inputs:
        parameters:
          - name: REPO_OWNER
          - name: REPO_NAME
          - name: GIT_BRANCH
      synchronization:
        semaphore:
          configMapKeyRef:
            name: my-config
            key: workflow
          selectors:
            - name: repoName
              template: "{{ inputs.parameters.REPO_OWNER }}/{{ inputs.parameters.REPO_NAME }}"
            - name: branch
              template: "{{ inputs.parameters.GIT_BRANCH }}"
      container:
        image: docker/whalesay:latest
        command: [sleep]
        args: ["5000"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-config
data:
  workflow: "1"
```

After applying the workflow has the following status:

```yaml
  nodes:
    sync-wft-by-params:
      children:
      - sync-wft-by-params-794660955
      displayName: sync-wft-by-params
      finishedAt: null
      id: sync-wft-by-params
      name: sync-wft-by-params
      phase: Running
      progress: 0/1
      startedAt: "2021-11-30T17:22:32Z"
      templateName: main
      templateScope: local/sync-wft-by-params
      type: Steps
    sync-wft-by-params-794660955:
      boundaryID: sync-wft-by-params
      children:
      - sync-wft-by-params-2114540733
      - sync-wft-by-params-2064207876
      displayName: '[0]'
      finishedAt: null
      id: sync-wft-by-params-794660955
      name: sync-wft-by-params[0]
      phase: Running
      progress: 0/1
      startedAt: "2021-11-30T17:22:32Z"
      templateScope: local/sync-wft-by-params
      type: StepGroup
    sync-wft-by-params-2064207876:
      boundaryID: sync-wft-by-params
      displayName: main2
      finishedAt: null
      id: sync-wft-by-params-2064207876
      inputs:
        parameters:
        - name: REPO_OWNER
          value: argoproj
        - name: REPO_NAME
          value: argo-workflows
        - name: GIT_BRANCH
          value: master
      message: 'Waiting for argo/ConfigMap/sync-config/workflow?repoName=argoproj/argo-workflows&branch=master
        lock. Lock status: 0/1 '
      name: sync-wft-by-params[0].main2
      phase: Pending
      startedAt: "2021-11-30T17:22:32Z"
      synchronizationStatus:
        waiting: argo/ConfigMap/sync-config/workflow?repoName=argoproj/argo-workflows&branch=master
      templateName: sync-by-params
      templateScope: local/sync-wft-by-params
      type: Pod
    sync-wft-by-params-2114540733:
      boundaryID: sync-wft-by-params
      displayName: main1
      finishedAt: null
      hostNodeName: k3d-argo-workflows-sandbox-server-0
      id: sync-wft-by-params-2114540733
      inputs:
        parameters:
        - name: REPO_OWNER
          value: argoproj
        - name: REPO_NAME
          value: argo-workflows
        - name: GIT_BRANCH
          value: master
      name: sync-wft-by-params[0].main1
      phase: Running
      progress: 0/1
      startedAt: "2021-11-30T17:22:32Z"
      templateName: sync-by-params
      templateScope: local/sync-wft-by-params
      type: Pod
  phase: Running
  progress: 0/1
  startedAt: "2021-11-30T17:22:32Z"
  synchronization:
    semaphore:
      holding:
      - holders:
        - sync-wft-by-params-2114540733
        semaphore: argo/ConfigMap/sync-config/workflow?repoName=argoproj/argo-workflows&branch=master
      waiting:
      - holders:
        - argo/sync-wft-by-params/sync-wft-by-params-2114540733
        semaphore: argo/ConfigMap/sync-config/workflow?repoName=argoproj/argo-workflows&branch=master
```

### CODE REVIEW

**Comment by jessesuen** [comment]
Rather than adding specific support for label selectors and parameter support in semaphores, I feel we should leverage our existing parameter substitution feature and enhance the semaphore feature to meet the requirements of the use case. The syntax I am proposing is:

```yaml
    - name: sync-by-params
      inputs:
        parameters:
          - name: REPO_OWNER
          - name: REPO_NAME
          - name: GIT_BRANCH
      synchronization:
        semaphore:
          configMapKeyRef:
            name: my-config
            key: workflow-"{{ inputs.parameters.REPO_OWNER }}/{{ inputs.parameters.REPO_NAME }}/{{ inputs.parameters.GIT_BRANCH }}"
            sizeKey: my-semaphore-size  # an independent reference to a ConfigMap key containing a numeric value which get's synced to the normal semaphore key.
```

The changes we would need would be:
1. Introduce a `sizeKey` field. This is a numeric value which would get synchronized to the dynamic/parameterized key
2. auto create the semaphore key if it does not exist

**Comment by sarabala1979** [comment]
@denis-codefresh I like the @jessesuen proposal.  We should make sure if `sizekey` is not present then. it should work as existing call flow to support the backward compatibility.

**Comment by denis-codefresh** [comment]
@jessesuen Thanks for sharing your thoughts here. I understood your idea but there are some points that I disagree with:
1. During the weekly sync, you said that you would like to see the semaphore keys updated (according to the chosen synchronization “selectors”) inside of the config map. I personally don’t see a value in this kind of observability. In config map we store the configured “weigth” of semaphore, not the current. So to understand the live state of locks and see how many holders it has, user still needs to go through the workflows and see what locking keys they are holding.
2. What is more crucial is that with this approach we need to update config map that was created BY USER, not by argo-workflows. It completely ruins the GitOps approach that might be taken to deploy argo workflows to the cluster.
3. Not a big deal, but IMHO it’s nice to have the separation between the config map key and sync “selectors” in the manifest. It looks more clear for me and makes the configuration more transparent. + it also utilises the same parameter substitution feature.

---

And I also thought about the "bucket" approach that @alexec has suggested. The one that we currently use to control ns/cluster parallelism.
I took a look at the current parallelism implementation and yes, it can be used for this purpose, but I don’t see any pros or cons in comparison with the synchronization mechanism.
But for me, it looks like it will be harder to implement it with a parallelism approach.
This is how I see it:

1. We need to introduce the new fields to workflow status to save a ref to acquired key and maintain it during the workflow lifetime.
2. We need to introduce new fields for workflow spec in order to configure the “bucket” size. It can’t be taken from controller config like in case with ns/cluster parallelism.
3. Not sure how it will overlap with existing synchronisation feature. It may be confusing to define workflow specific concurrency settings in 2 different places.
4. As a user I think I would like to expect “selector based” concurrency to be a part of synchronisation that I am already familiar with. The way how sync “selectors” implemented right now is fully compatible with “master” version.

And probably there are things that I missed.

Form the other hand is the implementation using synchronization that looks much more painless. We are not reinventing the wheel and utilizing the tool we already have.

Looking forward for further discussion!

**Comment by alexec** [comment]
@jessesuen @dinesh-rajaveeran , @sarabala1979 originally implemented this feature. Therefore, how about he works with Denis to come up with a design for this?

**Comment by tooptoop4** [comment]
this would be very useful! ie argo-events is starting workflows for each message where the message contains target tablename that the workflow writes to and you want to specify max 4 parallel workflows running per tablename

**Pull request closed without merging**
