### PR TITLE
feat: adding support for getting tls certificates from kubernetes secret (e.g.

### PR DESCRIPTION
**Pull request by ChaosInTheCRD**
Note: Continuation of #6542 (commit signing issues)

This PR allows a user to specify a secret name as a command-line parameter (--tls-certificate-secret-name) on the argo-server. Said secret would contain keys tls.key and tls.crt in order to provide a mechanism by which they can bring their own certificates (e.g. from cert-manager, Bitnami Sealed Secrets, generic Kubernetes secret).

This PR tries to follow a similar implementation to what is seen in Argo CD (argoproj/argo-cd#6071), for maintainability.

### CODE REVIEW

**Comment by ChaosInTheCRD** [comment]
@alexec I have addressed the requests that you made [here](https://github.com/argoproj/argo-workflows/pull/6542#pullrequestreview-856985031). Apologies for the creation of a separate PR but my many attempts to sign my commits did not succeed.

**Review by alexec — COMMENTED** [review]
Looks fine. You'll need to address the failing build jobs before merge.

**Review by alexec — APPROVED** [review]

**Comment by paul42** [comment]
hey all, sorry but I'm still learning - I see this is merged but when I run the latest version of `argo server --help` I don't see this option of `--tls-certificate-secret-name` do I have to wait longer for a release with this version / is there  a way I can watch for that? I love the project and bringing my own TLS secret would be super helpful.

thanks for the great work all!

**Comment by edevash** [comment]
Any reason, why the new flag is not exposed  as command-line parameter (--tls-certificate-secret-name).
This part available in https://github.com/argoproj/argo-workflows/pull/6542.
// Missing.
command.Flags().StringVar(&tlsCertificateSecretName, "tls-certificate-secret-name", "", "The name of a Kubernetes secret that contains the server certificates")
///

**Comment by agilgur5** [comment]
> Any reason, why the new flag is not exposed as command-line parameter (`--tls-certificate-secret-name`).
> This part available in #6542.

Seems like that was an accident and #9423 / #9789 added it

**Pull request merged**
