### PR TITLE
fix: Avoid hitting etcd limit for workflow pod with large parameters

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes https://github.com/argoproj/argo-workflows/issues/8790.

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by tooptoop4** [comment]
🙏

**Comment by juliev0** [comment]
added a [comment](https://github.com/argoproj/argo-workflows/issues/8790#issuecomment-1743614552) to the original issue on how we're relying on the ARGO_TEMPLATE inputs

**Comment by tooptoop4** [comment]
@terrytangyuan could we have an env flag to enable omitting this?

**Comment by tooptoop4** [comment]
would line 325 break as it expects inputs? 
```pod, err = substitutePodParams(pod, woc.globalParams, tmpl)```

**Comment by terrytangyuan** [comment]
There are certainly things breaking because of this change. The tests were not passing. If someone wants to pick this up, feel free to do so.

**Pull request closed without merging**
