### PR TITLE
chore(deps)!: bump k8s dependencies to 1.27

### PR DESCRIPTION
**Pull request by blkperl**
### Motivation

* Breaking change: Drops support for Kubernetes 1.23 clients
* K8s 1.26 EOL was 2024-02-28

### Modifications

* updated go.mod to K8s 1.27
* updated dist/kubernetes.swagger.json version to 1.27
* updated workflow/executor/resource.go to non deprecated functions to appease the linter
* changed getEvents test helper to truncate annotations from events so that TestEventNodeEvents passes

### Verification

Existing test coverage is sufficient

### CODE REVIEW

**Comment by blkperl** [comment]
E2E failed due to https://github.com/argoproj/argo-workflows/issues/12836

**Comment by blkperl** [comment]
@terrytangyuan can you review please?

**Review by terrytangyuan — COMMENTED** [review]
These separate PRs for each version bump did not help review at all (for me at least).

**Comment by blkperl** [comment]
closing in favor of https://github.com/argoproj/argo-workflows/pull/13413

**Pull request closed without merging**
