### PR TITLE
Remove hardcoded namespace in kustomize file #8250

### PR DESCRIPTION
**Pull request by tiwarisanjay**
Fixes #TODO
Please refer to https://github.com/argoproj/argo-workflows/issues/8250 for more information.

### CODE REVIEW

**Comment by alexec** [comment]
Please run `make pre-commit -B`

**Comment by tiwarisanjay** [comment]
@alexec `make pre-commit -B`  is giving me too many issues

**Comment by alexec** [comment]
manually apply the diffs?


diff --git a/manifests/install.yaml b/manifests/install.yaml
[8](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:8)
index 65308b7..c75c1f0 100644
[9](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:9)
--- a/manifests/install.yaml
[10](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:10)
+++ b/manifests/install.yaml
[11](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:11)
@@ -981,7 +981,6 @@ roleRef:
[12](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:12)
 subjects:
[13](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:13)
 - kind: ServiceAccount
[14](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:14)
   name: argo
[15](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:15)
-  namespace: argo
[16](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:16)
 ---
[17](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:17)
 apiVersion: rbac.authorization.k8s.io/v1
[18](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:18)
 kind: ClusterRoleBinding
[19](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:19)
@@ -994,7 +993,6 @@ roleRef:
[20](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:20)
 subjects:
[21](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:21)
 - kind: ServiceAccount
[22](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:22)
   name: argo-server
[23](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:23)
-  namespace: argo
[24](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:24)
 ---
[25](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:25)
 apiVersion: v1
[26](https://github.com/argoproj/argo-workflows/runs/5722733448?check_suite_focus=true#step:9:26)
 kind: ConfigMap

**Comment by tiwarisanjay** [comment]
@alexec  Seems like I was out of sync. I have rebase have pushed the changes again

**Comment by tiwarisanjay** [comment]
@alexec  https://github.com/argoproj/argo-workflows/actions/runs/2066265885 
This one seems to be fine. One of the test got failed with timeout.

**Review by alexec — APPROVED** [review]

**Pull request merged**
