### PR TITLE
fix(ui): unauthorized login screen doesn't clarify require…

### PR DESCRIPTION
**Pull request by dtcsai**
My teammate @bulbul-ismail and I faced with an UNAUTH error while bring up our new argo-workflow-server pod in the internal network and after that tested the same template in our systems. Resolved the issue quickly and after that, we realized it would be a better instruction to print "provide the $ARGO_SERVER_ID via kubectl exec" in the login fail screen.

### CODE REVIEW

**Comment by alexec** [comment]
Interesting. I did not think about this solution. I like it, but we should give users both options as suggestions.

**Review by terrytangyuan — COMMENTED** [review]
Would it be better to link to auth documentation which provides both options?

**Review by alexec — CHANGES_REQUESTED** [review]
This is a good idea, but could you please:

* Show both options.
* Sign-off your commit to pass the DCO check.

**Comment by dogukantuna** [comment]
Thanks for your feedback.
Documentation changed and linked into login.tsx.

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
LGTM

**Review by alexec — CHANGES_REQUESTED** [review]
needs `yarn lint`

**Comment by dogukantuna** [comment]
Added. Changes waiting approvel.

**Comment by bulbul-ismail** [comment]
Rebased & other issues commit deleted from the pr. Workflow waiting for approval.

**Comment by dogukantuna** [comment]
@alexec Why these two failing checks are not successful?

**Comment by alexec** [comment]
`yarn lint` please.

**Review by alexec — CHANGES_REQUESTED** [review]
Needs `yarn lint`

**Pull request closed without merging**
