### PR TITLE
chore: Update CODEOWNERS file

### PR DESCRIPTION
**Pull request by terrytangyuan**
This has not been useful and redundant to approvers.

### CODE REVIEW

**Comment by sarabala1979** [comment]
@terrytangyuan Can you help me to understand for this deletion?

**Comment by sarabala1979** [comment]
I remember Alex and Jessie added this for Proto change needs to be reviewed by leads. Is the configure broken?

**Comment by agilgur5** [comment]
> I remember Alex and Jessie added this for Proto change needs to be reviewed by leads. Is the configure broken?

No it works, but as Terry is currently the only one actively approving, it is not particularly useful right now. It can also give a false impression that there are more active approvers than there actually are.
Also, others are getting notifications despite not responding to them -- that may dilute notifications where we may actually want their input more in a direct mention, for instance.

**Review by agilgur5 — APPROVED** [review]

**Comment by terrytangyuan** [comment]
I was thinking we don't need this since only approvers have permission to merge PRs and all of the ones listed in CODEOWNERS are already approvers. Also neither Alex nor Jesse is lead now.

**Comment by sarabala1979** [comment]
> I am not sure if it's a good idea to distinguish proto changes from other changes. There are other changes that are important and might be breaking.
All CRD changes will be changed in the proto. The main idea is to get two approvers(approver and  Leads) for any CRD and API changes. I think it is needed for core files.

**Comment by terrytangyuan** [comment]
@sarabala1979 I changed the PR to update the file instead of deleting it. I removed non-leads from the file.

**Review by sarabala1979 — APPROVED** [review]

**Pull request merged**
