### PR TITLE
ci: increase sleep time for very flaky hook test

### PR DESCRIPTION
**Pull request by toyamagu-2021**
Signed-off-by: toyamagu-2021 <toyamagu2021@gmail.com>

Partial fix for #10807

### Motivation

* Address to https://github.com/argoproj/argo-workflows/issues/10807#issuecomment-1728685887
* Increase sleep time to give enough time to trigger the running hook
* Add `Progress` assertion to understood problem

### CODE REVIEW

**Review by agilgur5 — COMMENTED** [review]
Should this be added to the DAG variant also, which similarly flakes a good bit?

**Comment by toyamagu-2021** [comment]
Simply forgotten, thanks!

**Review by agilgur5 — APPROVED** [review]

**Comment by agilgur5** [comment]
Oh boy, [the](https://github.com/argoproj/argo-workflows/actions/runs/6364238795/job/17280383581?pr=11921) [failures](https://github.com/argoproj/argo-workflows/actions/runs/6364238795/job/17280384075?pr=11921) in this CI run are confusing me even more as the output is even more different than I expected 😖

**Comment by toyamagu-2021** [comment]
Irritating, but very interesting :)
Close this PR and I'll investigate further.

**Pull request closed without merging**
