### PR TITLE
docs(cli): correct headings in `argo` command's `Long` description

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- these were H1s before, and there can only be 1 H1 per page
  - they also _should_ be H4s, because these are under the "Synopsis", which is an H3 
    - this fixes some very wacky formatting in the docs as well as HTML semantic errors

### Modifications

- h1 -> h4 in `argo` root command's `Long` description

### Verification

Before:
Screenshot 2023-10-10 at 2 39 08 PM --before

After:
Screenshot 2023-10-10 at 2 40 35 PM --after

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
This should be docs instead of fix?

**Comment by terrytangyuan** [comment]
Generated docs are docs change.

**Comment by agilgur5** [comment]
Sure, but it also changes the source code / metadata of the CLI. nbd either way to be fair, but we're not currently cherry-picking docs PRs, which we will need to do for [versioned docs](https://github.com/argoproj/argo-workflows/issues/11390). so we'll need some way to decipher docs PRs that are for new features vs docs PRs for existing features (most will fall into the latter, I imagine). semantically, it's pretty quick to tell from the PR, but there's no way to do that automatically right now unless we differentiate in some way

**Comment by agilgur5** [comment]
fixed codegen

**Comment by agilgur5** [comment]
Merged `master` to get new status checks / actions from #12006 to run

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
