### PR TITLE
fix: fix swagger error. Fixes #8830

### LINKED ISSUE #8830: Have errors for swagger.json when opening with https://editor.swagger.io
I found there are some errors when opening swagger.json with https://editor.swagger.io like below, I am new to GitHub, can you please help to assign this bug to me?  I want to work on this
image
Structural error at paths./artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}.get.parameters
should NOT have duplicate items (items ## 4 and 6 are identical)
i: 6
j: 4
Jump to line 5861
Semantic error at paths./artifact-files/{namespace}/{idDiscriminator}/{id}/{nodeId}/{artifactDiscriminator}/{artifactName}.get.parameters.6
Sibling parameters must have unique name + in values
Jump to line 5890
Semantic error at paths./input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}.get.parameters.0.name
Path parameter "namespace" must have the corresponding {namespace} segment in the "/input-artifacts-by-uid/{uid}/{nodeId}/{artifactName}" path
Jump to line 5971

What change needs making?
Update swagger.json file to fix the issue 

# Use Cases

When would you use this?
See API details

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by JessieTeng89**
fix: fix swagger error. Fixes #8830

### CODE REVIEW

**Review by tczhao — CHANGES_REQUESTED** [review]
I think you need to modify `pkg/apiclient/_.primary.swagger.json`
then run `make pre-commit -B` (https://argoproj.github.io/argo-workflows/running-locally/)
so all generated files are updated

**Comment by JessieTeng89** [comment]
> I think you need to modify `pkg/apiclient/_.primary.swagger.json`
> then run `make pre-commit -B` (https://argoproj.github.io/argo-workflows/running-locally/)
> so all generated files are updated

@tczhao Thanks for your reply, I tried to modify `pkg/apiclient/_.primary.swagger.json` instead follow the guide to run `make pre-commit -B`, but I got below error, any idea?

2022/05/26 18:22:40 Unable to generate protoc on k8s.io.apimachinery.pkg.util.intstr: exit status 1
make: *** [pkg/apis/workflow/v1alpha1/generated.proto] Error 1

**Comment by dpadhiar** [comment]
@JessieTeng89 Hi Jessie, could you post the whole error log when you run `make pre-commit -B`? The error may be that your PATH is not set correctly. Check that you have GOPATH and set PATH like so: `export PATH=$PATH:$GOPATH/bin`.

**Comment by JessieTeng89** [comment]
> @JessieTeng89 Hi Jessie, could you post the whole error log when you run `make pre-commit -B`? The error may be that your PATH is not set correctly. Check that you have GOPATH and set PATH like so: `export PATH=$PATH:$GOPATH/bin`.

@dpadhiar Thanks for your response, I tried to configure the GOPATH and PATH, the error seems gone, but I met another error like below:

`# These files are generated on a v3/ folder by the tool. Link them to the root folder
[ -e ./v3 ] || ln -s . v3
/Users/a715260/go/bin/openapi-gen \
          --go-header-file ./hack/custom-boilerplate.go.txt \
          --input-dirs github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 \
          --output-package github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 \
          --report-filename pkg/apis/api-rules/violation_exceptions.list
# Delete the link
[ -e ./v3 ] && rm -rf v3
# These files are generated on a v3/ folder by the tool. Link them to the root folder
[ -e ./v3 ] || ln -s . v3
bash /Users/a715260/go/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh \
            "deepcopy,client,informer,lister" \
            github.com/argoproj/argo-workflows/v3/pkg/client github.com/argoproj/argo-workflows/v3/pkg/apis \
            workflow:v1alpha1 \
            --go-header-file ./hack/custom-boilerplate.go.txt
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
make: *** [pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go] Error 1`

**Comment by JessieTeng89** [comment]
@JessieTeng89 Hi Jessie, could you post the whole error log when you run `make pre-commit -B`? The error may be that your PATH is not set correctly. Check that you have GOPATH and set PATH like so: `export PATH=$PATH:$GOPATH/bin`.
 
@dpadhiar Thanks for your response, I tried to configure the GOPATH and PATH, the error seems gone, but I met another error like below:
# These files are generated on a v3/ folder by the tool. Link them to the root folder
[ -e ./v3 ] || ln -s . v3 /Users/a715260/go/bin/openapi-gen --go-header-file ./hack/custom-boilerplate.go.txt --input-dirs github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --output-package github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --report-filename pkg/apis/api-rules/violation_exceptions.list

# Delete the link
[ -e ./v3 ] && rm -rf v3

# These files are generated on a v3/ folder by the tool. Link them to the root folder
[ -e ./v3 ] || ln -s . v3 bash /Users/a715260/go/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh "deepcopy,client,informer,lister" github.com/argoproj/argo-workflows/v3/pkg/client github.com/argoproj/argo-workflows/v3/pkg/apis workflow:v1alpha1 --go-header-file ./hack/custom-boilerplate.go.txt error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. make: *** [pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go] Error 1

**Comment by JessieTeng89** [comment]
> @dpadhiar Thanks for your response, I tried to configure the GOPATH and PATH, the error seems gone, but I met another error like below: These files are generated on a v3/ folder by the tool. Link them to the root folder [ -e ./v3 ] || ln -s . v3 /Users/a715260/go/bin/openapi-gen --go-header-file ./hack/custom-boilerplate.go.txt --input-dirs github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --output-package github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --report-filename pkg/apis/api-rules/violation_exceptions.list
> 
> Delete the link [ -e ./v3 ] && rm -rf v3
> 
> These files are generated on a v3/ folder by the tool. Link them to the root folder [ -e ./v3 ] || ln -s . v3 bash /Users/a715260/go/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh "deepcopy,client,informer,lister" github.com/argoproj/argo-workflows/v3/pkg/client github.com/argoproj/argo-workflows/v3/pkg/apis workflow:v1alpha1 --go-header-file ./hack/custom-boilerplate.go.txt error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. make: *** [pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go] Error 1

**Comment by dpadhiar** [comment]
> > @JessieTeng89 Hi Jessie, could you post the whole error log when you run `make pre-commit -B`? The error may be that your PATH is not set correctly. Check that you have GOPATH and set PATH like so: `export PATH=$PATH:$GOPATH/bin`.
> 
> @dpadhiar Thanks for your response, I tried to configure the GOPATH and PATH, the error seems gone, but I met another error like below:
> 
> These files are generated on a v3/ folder by the tool. Link them to the root folder [ -e ./v3 ] || ln -s . v3 /Users/a715260/go/bin/openapi-gen --go-header-file ./hack/custom-boilerplate.go.txt --input-dirs github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --output-package github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --report-filename pkg/apis/api-rules/violation_exceptions.list Delete the link [ -e ./v3 ] && rm -rf v3 These files are generated on a v3/ folder by the tool. Link them to the root folder [ -e ./v3 ] || ln -s . v3 bash /Users/a715260/go/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh "deepcopy,client,informer,lister" github.com/argoproj/argo-workflows/v3/pkg/client github.com/argoproj/argo-workflows/v3/pkg/apis workflow:v1alpha1 --go-header-file ./hack/custom-boilerplate.go.txt error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. make: *** [pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go] Error 1

This is a version control system error. Check that you don't have anything conflicting with your git commits or setup. When I encountered this issue for example, I had a script for automatic signoffs that was failing. 

 If you cannot find an appropriate fix, you can try `git clean` followed by `make pre-commit -B`.

**Comment by JessieTeng89** [comment]
> > > @JessieTeng89 Hi Jessie, could you post the whole error log when you run `make pre-commit -B`? The error may be that your PATH is not set correctly. Check that you have GOPATH and set PATH like so: `export PATH=$PATH:$GOPATH/bin`.
> > 
> > 
> > @dpadhiar Thanks for your response, I tried to configure the GOPATH and PATH, the error seems gone, but I met another error like below:
> > These files are generated on a v3/ folder by the tool. Link them to the root folder [ -e ./v3 ] || ln -s . v3 /Users/a715260/go/bin/openapi-gen --go-header-file ./hack/custom-boilerplate.go.txt --input-dirs github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --output-package github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1 --report-filename pkg/apis/api-rules/violation_exceptions.list Delete the link [ -e ./v3 ] && rm -rf v3 These files are generated on a v3/ folder by the tool. Link them to the root folder [ -e ./v3 ] || ln -s . v3 bash /Users/a715260/go/pkg/mod/k8s.io/code-generator@v0.21.5/generate-groups.sh "deepcopy,client,informer,lister" github.com/argoproj/argo-workflows/v3/pkg/client github.com/argoproj/argo-workflows/v3/pkg/apis workflow:v1alpha1 --go-header-file ./hack/custom-boilerplate.go.txt error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. error obtaining VCS status: exit status 128 Use -buildvcs=false to disable VCS stamping. make: *** [pkg/apis/workflow/v1alpha1/zz_generated.deepcopy.go] Error 1
> 
> This is a version control system error. Check that you don't have anything conflicting with your git commits or setup. When I encountered this issue for example, I had a script for automatic signoffs that was failing.
> 
> If you cannot find an appropriate fix, you can try `git clean` followed by `make pre-commit -B`.

Thanks! I tried to run `git clean` then `make pre-commit -B` but I met the same error, let me check and try later

**Comment by JessieTeng89** [comment]
@dpadhiar @tczhao 
The issue was resolved and I created another pull request instead, so close this pull request
https://github.com/argoproj/argo-workflows/pull/8886

**Pull request closed without merging**
