### PR TITLE
feat(workflow-controller): add timeout of WaitForCacheSync

### PR DESCRIPTION
**Pull request by sxllwx**
Fixes #TODO

### Motivation

add a timeout for Workflow-Controller `WaitForCacheSync`. if it cannot be completed within the specified time(1m) controller exit and output logs to help user locate the bug.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
What issue is this PR trying to address?

**Comment by sxllwx** [comment]
ahha, thank you for your quick reply.

Sorry, I didn't provide the full relevant background.

This is what I encountered during the upgrade from v3.1.1 to v3.4.6. At that time, after the workflow was submitted, the workflow-controller did not drive the workflow for a long time, and there was no output in the log that could help locate the fault [our log level was not adjusted to a high level]. Finally, it was found through pprof because it was blocked in With `WaitForCacheSync`, although we control it through ctx, the timeout of waitForCacheSync. But unfortunately this ctx never ends. [The more fundamental reason is that we added a new CRD `workflowartifactgctasks`, but it is not installed in our cluster]

**Comment by terrytangyuan** [comment]
>The more fundamental reason is that we added a new CRD workflowartifactgctasks, but it is not installed in our cluster

That should be included in the upgrade.

**Comment by sxllwx** [comment]
Do we still need this PR to fix this problem?

**Comment by terrytangyuan** [comment]
If missing `workflowartifactgctasks` CRD is the root cause, then we probably don't need it.

**Comment by sxllwx** [comment]
Thanks for your review. I close this PR.

**Pull request closed without merging**
