### PR TITLE
fix: don't mount SA token when `automountServiceAccountToken: false`. Fixes #12848

### LINKED ISSUE #12848: `resource` template getting duplicate `exec-sa-token` volume mounts with `automountServiceAccountToken: false`
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

Running a [workflow of workflows](https://argo-workflows.readthedocs.io/en/latest/workflow-of-workflows/) with `automountServiceAccountToken: false` results in a repeated `exec-sa-token` volume mount in the child pod spec.

When trying to run the child workflow, the pod spec validation fails with 

```
Pod "my-workflow-id-sub-id" is invalid: spec.containers[1].volumeMounts[1].mountPath: Invalid value: "/var/run/secrets/kubernetes.io/serviceaccount": must be unique
```

It appears that the [code in `workflowpod.go`](https://github.com/argoproj/argo-workflows/blob/v3.5.2/workflow/controller/workflowpod.go#L225-L238) is running multiple times for the same container in these cases.

### Version

v3.5.2

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  automountServiceAccountToken: false # 👈
  executor:
    serviceAccountName: workflow-executor
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-of-workflows-
spec:
  automountServiceAccountToken: false # 👈
  executor:
    serviceAccountName: workflow-executor
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: workflow1
            template: resource-without-argument
            arguments:
              parameters:
              - name: workflowtemplate
                value: "workflow-template-submittable"

    - name: resource-without-argument
      inputs:
        parameters:
          - name: workflowtemplate
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-1-
          spec:
            workflowTemplateRef:
              name: {{inputs.parameters.workflowtemplate}}
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
```

### Logs from the workflow controller

```text
{
  "level": "warning",
  "msg": "Non-transient error: Pod \"my-workflow-id-sub-id\" is invalid: spec.containers[1].volumeMounts[1].mountPath: Invalid value: \"/var/run/secrets/kubernetes.io/serviceaccount\": must be unique",
  "time": "..."
}
```

### Logs from in your workflow's wait container

```text
n/a
```

### PR DESCRIPTION
**Pull request by MinyiZ**
Fixes #12848

### Motivation

https://github.com/argoproj/argo-workflows/pull/10945 introduced a regression as it is mounting a serviceaccount token on the main container when `automountServiceAccountToken: false`. 

The [security docs](https://argo-workflows.readthedocs.io/en/release-3.5/security/#workflow-pod-permissions) say 

> The main container will have the service account token mounted, allowing the main container to patch pods (among other permissions). Set `automountServiceAccountToken` to false to prevent this.

https://github.com/argoproj/argo-workflows/issues/10937 was not a bug. It is possible to explicitly mount a token to container and script template workflows even if `automountServiceAccountToken: false` so the code change was not needed.

### Modifications

- Reverts https://github.com/argoproj/argo-workflows/pull/10945
- Add test for `resource` template with `automountServiceAccountToken: false` and `executor.serviceAccountName` set

### Verification

Tests passed

### CODE REVIEW

**Review by agilgur5 — COMMENTED** [review]
Regarding the tests here and from #10945, a `resource` template should correctly fail if `automountServiceAccountToken: false` since, well, there is no SA token for it to use

**Comment by MinyiZ** [comment]
> Regarding the tests here and from #10945, a `resource` template should correctly fail if `automountServiceAccountToken: false` since, well, there is no SA token for it to use

I've fixed the tests from https://github.com/argoproj/argo-workflows/pull/10945 to demonstrate that it is possible to explicitly mount a token to container and script template workflows even if `automountServiceAccountToken: false` so the code change was not needed.

I believe `resource` templates shouldn't fail if `automountServiceAccountToken: false` because the exec token is mounted at [mainCtr := woc.newExecContainer(common.MainContainerName, tmpl)](https://github.com/argoproj/argo-workflows/blob/25bbb71cced32b671f9ad35f0ffd1f0ddb8226ee/workflow/controller/operator.go#L3453C13-L3453C33) and I've added an e2e test to demonstrate that.

**Comment by MinyiZ** [comment]
All e2e tests are passing now. I'm not sure why the unit test `TestConfigMapCacheSaveOperate` in `operator.go` is failing. I will take a look later.

**Comment by agilgur5** [comment]
> I believe `resource` templates shouldn't fail if `automountServiceAccountToken: false` because the exec token is mounted at

Ah nice, I wasn't sure if `resource` templates handled `executor.serviceAccountName` since they use a `main` container.

> I've fixed the tests from #10945 to demonstrate that it is possible to explicitly mount a token to container and script template workflows even if `automountServiceAccountToken: false` so the code change was not needed.

I saw that, but I don't think that test is very functional / necessary. Basically you're manually mounting the token instead of `automount`ing it. A user shouldn't really ever do that manually though, they should just `automount`. I think both those tests should just be removed

> [MinyiZ](https://github.com/MinyiZ) changed the title ~fix: don't mount SA token when automountServiceAccountToken: false. Fixes #12848~ fix: resource template getting duplicate exec-sa-token volume mounts with automountServiceAccountToken: false. Fixes #12848 [5 hours ago](https://github.com/argoproj/argo-workflows/pull/13820#event-14913607990)

Regarding the PR title, my change was intentional. The PR title should summarize what the PR does, not what the issue is. The PR title and issue title should not be equivalent.

**Comment by MinyiZ** [comment]
> I think both those tests should just be removed.
Yep agreed done.

> Regarding the PR title, my change was intentional.
Ooops sorry about that. I unintentionally reverted your change when I was fixing up a typo. I've changed it back now.

**Review by agilgur5 — APPROVED** [review]
LGTM, thanks for taking a look and fixing this!

**Pull request merged**
