### PR TITLE
documentation changes

### PR DESCRIPTION
**Pull request by Yh010**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=260wWuS)
Fixes #TODO

### CODE REVIEW

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
The changes look unnecesary. What was your reasoning behind these changes? This file is also autogenerated and you'll need to modify the Go files in commands instead.

**Comment by Yh010** [comment]
> The changes look unnecesary. What was your reasoning behind these changes? This file is also autogenerated and you'll need to modify the Go files in commands instead.

Felt like there were grammatical errors and the code seemed quite congested so modified that✌.

**Comment by alexec** [comment]
These files are generated from the source code.  You can edit the correct file (e.g. terminate.go) and then run `make codegen`

**Comment by Yh010** [comment]
Ok sir will do the necessary

**Pull request closed without merging**
