### PR TITLE
fix: evaluated debug env vars value

### PR DESCRIPTION
**Pull request by GoshaDo**
Useful when passing debug flag to a pipeline as a parameter. 

Fixes #evulated debug env vars value

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [X] Github checks are green.
* [X] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Review by alexec — CHANGES_REQUESTED** [review]
Thank you for your PR.

* I'm not clear what issue you're trying to fix. Could you please like to it from the PR title?
* I've suggested an simplification.

**Comment by GoshaDo** [comment]
> Thank you for your PR.
> 
> * I'm not clear what issue you're trying to fix. Could you please like to it from the PR title?
> * I've suggested an simplification.

I haven't open an issue for that one, but it enables to set the env var and check the value of it.
The problem with you suggested fix is that the value "True" or "TRUE" not evaluated. also if anything that non boolean value injected, it's false.. that not bad, but don't covers all the edge cases

**Comment by alexec** [comment]
I see. I don't think that we should support variations of "true" here when we do not do so elsewhere. That would result in inconsistent and unexpected behaviour.

**Comment by GoshaDo** [comment]
@alexec ok, so lets leave it like that.

**Review by alexec — APPROVED** [review]

**Pull request merged**
