### PR TITLE
fix: http template doesn't update progress. Fixes #7239

### LINKED ISSUE #7239: HTTP template always reports progress as zero
It should be 0/1 when pending/running and 1/1 when complete.

image

### PR DESCRIPTION
**Pull request by softwarebloat**
To me the PR is ready but i'm not able to try it locally as stated in #7436 
That's why i left it as Draft

### CODE REVIEW

**Comment by sarabala1979** [comment]
@softwarebloat is it ready to review?

**Comment by softwarebloat** [comment]
@sarabala1979 yes it is. only thing is that i wasn't able to try it locally but, if the test i wrote is correct, it should work :crossed_fingers:

**Comment by sarabala1979** [comment]
> @sarabala1979 yes it is. only thing is that I wasn't able to try it locally but, if the test I wrote is correct, it should work 🤞

Sure, have you tried `make start`? I will try it on my env

**Comment by softwarebloat** [comment]
> > @sarabala1979 yes it is. only thing is that I wasn't able to try it locally but, if the test I wrote is correct, it should work 🤞
> 
> Sure, have you tried `make start`? I will try it on my env

Yes I tried `make start` but seems like my fix has no effect. So I don't understand if it's not loaded or not working.
Another strange thing is that I don't have the controller pod in my cluster 🤷‍♂️

**Review by simster7 — APPROVED** [review]

**Comment by softwarebloat** [comment]
@sarabala1979 were you able to test it locally?

**Pull request merged**
