### PR TITLE
docs: add missing quote

### PR DESCRIPTION
**Pull request by Sebast1aan**

### CODE REVIEW

**Comment by Sebast1aan** [comment]
Not sure why one of the tests is failing, seems unrelated to this PR.

**Review by agilgur5 — APPROVED** [review]
thanks!

**Comment by agilgur5** [comment]
> Not sure why one of the tests is failing, seems unrelated to this PR.

Yes, you're correct. The hooks tests are a bit flakey on CI specifically right now. A few contributors have been trying to fix them (including me) with limited success

**Review by terrytangyuan — APPROVED** [review]
Thanks!

**Pull request merged**
