### PR TITLE
feat: Include node.name as a field for interpolation

### PR DESCRIPTION
**Pull request by RyanCopley**
Signed-off-by: Ryan Copley <rcopley@newrelic.com>

Adds a feature to where you can reference the fully qualified node name. We plan on using this for a testing framework.

I used this PR as a foundation for making this change: https://github.com/argoproj/argo-workflows/pull/9387

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: this-is-part-1
            template: main2
    - name: main2
      steps:
        - - name: this-is-part-2
            template: main3
    - name: main3
      dag:
        tasks:
          - name: this-is-part-3
            template: whalesay
    - name: whalesay
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{ node.name }}"]
```

Results in:

```W
time="2022-09-21T03:48:12.053Z" level=info msg="capturing logs" argo=true
 _________________________________________
/ hello-world-nm8lw.this-is-part-1[0].thi \
\ s-is-part-2.this-is-part-3              /
 -----------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

### CODE REVIEW

**Comment by RyanCopley** [comment]
@sarabala1979, would you be able to review this PR for me please? I apologize if this isn't the correct way to ask for a review, I didn't see any information about how to obtain one. Thank you

**Comment by sarabala1979** [comment]
@RyanCopley Can you add a test for this?

**Comment by RyanCopley** [comment]
@sarabala1979 I will have to research to see how to do soo for this project; however this PR is very similar and didn't include any: https://github.com/argoproj/argo-workflows/pull/9387/files

**Comment by RyanCopley** [comment]
@sarabala1979 After researching the codebase I have discovered that none of this functionality related to localParams has any form of tests. I attempted to add some, but ran into significant complexity that I don't really quite have the knowledge of how to write. With this the case, do we absolutely need tests for this PR? It seems a bit much to write tests around code that I didn't write, as I don't have that first-hand knowledge. It seems like a much more complex PR, that I used to base mine off of, did not require tests for merging.

**Comment by RyanCopley** [comment]
@alexec @sarabala1979 see updated pr please

**Comment by RyanCopley** [comment]
@alexec @sarabala1979 Is there a process for formally asking for a review?

**Review by sarabala1979 — APPROVED** [review]

**Review by alexec — APPROVED** [review]

**Pull request merged**
