### PR TITLE
 fix: More informative error message when artifact repository is not configured. 

### LINKED ISSUE #7372: Improve "artifact repo not configured" error message
# Summary

When you run a workflow which uses artifacts, but you do not have an artifact repo configured (like with the default install.yaml), the workflow will fail with `key unsupported: cannot get key for artifact location, because it is invalid`.

This message doesn't effectively convey the real problem: the user needs an artifact repo. I know of at least two [goose](https://cloud-native.slack.com/archives/C01QW9QSSSK/p1638825025074900) [chases](https://github.com/argoproj/argo-workflows/issues/6497#issuecomment-894350506) caused by the misleading error message.

To reproduce: 
1. install default install.yaml
2. run the [artifact passing example](https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-passing.yaml)

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by thatGreekGuy96**
Fixes #7372 . 
Adds some a more informative error message when the artifact storage configuration is missing + updates relevant unit tests. 

PS: This is my first PR to an open source Go project so apologies for any silly mistakes I may have made and looking forward to comments and contributing more! 
Many thanks to @sarabala1979 for his help with this!

### CODE REVIEW

**Comment by thatGreekGuy96** [comment]
Seems like the PR is stuck on this check 
image
@terrytangyuan @sarabala1979 what do I need to do?

**Comment by terrytangyuan** [comment]
Yes, try pushing a new commit.

**Comment by thatGreekGuy96** [comment]
@terrytangyuan @sarabala1979 PR is ready for review :)

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
🚀 LGTM!

**Pull request merged**
