### PR TITLE
feat: List UID with 'argo archive list'

### PR DESCRIPTION
**Pull request by simster7**
When running `argo arhive get`, you must have a workflow's UID to query. If `argo archive list` does not show this UID, you cannot get a workflow (to, e.g., get its UID). Catch-22.

Signed-off-by: Simon Behar <simbeh7@gmail.com>

Don't bother creating a PR until you've done this:

* [ ] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Review by alexec — COMMENTED** [review]
lint

**Comment by simster7** [comment]
> lint

@alexec It's an issue with the "log checker". It passes for me locally and I can't see from reading the code why it's failing here. Can you take a look?

**Comment by alexec** [comment]
Hypothesis:

* Fprintf is banned somehow.
* Other issue

Could you remove `Fprintf`?

**Comment by simster7** [comment]
> Fprintf is banned somehow.

It isn't though 🤔  this count returns 0 when I do it manually

https://github.com/argoproj/argo-workflows/blob/8d552fbf6b3752025955b233a9462b34098cedf1/hack/check-logging.sh#L23

> Could you remove Fprintf?

I could, but it's prior art and deeply integrated into how the CLI printer works. So if we go this route it's a larger refactor.

**Comment by simster7** [comment]
Apparently no fix required??

**Pull request merged**
