### PR TITLE
fix: Reduce argoexec size by 25Mb. Fixes #6196

### LINKED ISSUE #6196: argoexec images is 130Mb
This is larger than expected. I think that `setpcap` adds 24Mb, and can be moved to the

### PR DESCRIPTION
**Pull request by alexec**
Fixes #6196

### CODE REVIEW

**Comment by alexec** [comment]
See:

feat(executor): Support accessing output parameters by PNS executor running as non-root (#5564)

**Comment by alexec** [comment]
@vladlosev could you please comment on this? Can we run `setcap` in the build stage, or does it need to be in the packaging stage.

**Comment by vladlosev** [comment]
It looks like the `RunAsNonRootSuite/TestRunAsNonRootWithOutputParams` test is still [passing](https://github.com/argoproj/argo-workflows/pull/6197/checks?check_run_id=2896940817#step:15:332), so capability bits must be preserved while copying between the images. Looks like there are no issues with this change.

**Comment by alexec** [comment]
https://hub.docker.com/layers/argoproj/argoexec/dev-cap/images/sha256-e25387345ebc5867e8aba23860308d9f58cf97476f18d84ff73fbd2c76df3f8e?context=explore

**Review by whynowy — APPROVED** [review]

**Pull request merged**
