### PR TITLE
chore(deps): remove unneeded Yarn resolutions

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- removing these has no impact on resolution, as can be seen in the `yarn.lock`
  - any bumps in these deps will produce either the same minor or same major version (most are same minor version) -- i.e. no breaking changes
  - basically, these are extraneous as of this time
  
Related to #11630, which removes unused deps; this removes unneeded `resolutions`

### Modifications

- remove resolutions for `@types/react`, `autolinker`, `fast-json-patch`, `lodash`, and `prismjs`

- did _not_ touch `semver` or `react-toastify`
  - the `semver` resolution currently forces _all versions_ to the same as the resolution (including different majors, which can be seen [in the `yarn.lock`](https://github.com/argoproj/argo-workflows/blob/8a52da5e8ee6eeabffb6c7e5858702129b37b525/ui/yarn.lock#L8959))
  - ~the `react-toastify` resolution was needed for #11585 and it is removed as part of build upgrades in #11628~
    - **EDIT**: rebased on top so this is no longer present

### Verification

Install succeeds, build passes.
Spot check on render.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
I remember these resolutions were added to resolve security issues.

**Comment by agilgur5** [comment]
Per the first line of the PR, removing these has no impact on resolution. I imagine that those resolutions are either outdated or were used incorrectly to update a version in `yarn.lock`. Looking at #10842, that was indeed used to update a version `yarn.lock`.

`yarn.lock` can just be updated independently if the bump is within the SemVer range; it does not need a resolution.
You will need to comment out the `--frozen-lockfile` flag temporarily in [the `.yarnrc` though](https://github.com/argoproj/argo-workflows/blob/d74929a69130fdefed0608f708767025b2de90a7/ui/.yarnrc#L3). Normally that flag is only set in CI and not during development (it was made as a default [here](https://github.com/argoproj/argo-workflows/pull/3009/files#r423909775), seemingly so that it doesn't have to be individually set in multiple CI builds?)

**Review by terrytangyuan — APPROVED** [review]
We can merge and see if Snyk check passes

**Comment by agilgur5** [comment]
It [did](https://github.com/argoproj/argo-workflows/actions/runs/5980065079/job/16225432786) 😉 .
This is basically a no-op as all the versions in the `yarn.lock` don't change.

**Pull request merged**
