### PR TITLE
feat: add description field. Fixes #2871

### LINKED ISSUE #2871: Add descriptions for steps that can show up in ui
# Summary

Add step description field that can add human readable descriptions about the step. 

# Motivation

We make the ui available for others on our teams to view, but they do not necessarily have the full technical understanding of what the workflow is doing. It would be great if instead we could offer them a description of a step when they click on it to get a summary of what the step is doing. 

# Proposal
Not sure, but I'd imagine the end result would be an additional field within templates.steps when designing a workflow.

### PR DESCRIPTION
**Pull request by yokishava**
Signed-off-by: yokishava <aihasayahukoma7@gmail.com>

Fixes #2871

I saw [this issue](#2871) and added a desctiption field.
I added description fields to DAGTask, NodeStatus and WorkflowStep so I can see them on the UI.
A screenshot of the UI changes is pasted below.

##### manifest
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello
  templates:
  - name: hello 
    steps:
    - - name: hello-1
        description: hello step 1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello1"}]
    - - name: hello-2
        description: hello step 2
        template: whalesay 
        arguments:
          parameters: [{name: message, value: "hello2"}]
  - name: whalesay 
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```
##### screenshot
image

##### manifest
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        description: A task
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        depends: "A"
        description: B task
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        depends: "A"
        description: C task
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        description: D task
        depends: "B && C"
        template: echo
        arguments:
          parameters: [{name: message, value: D}]
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
```

##### screenshot
image

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
LGTM

**Review by alexec — COMMENTED** [review]
This is a big change so should be bought to the community meeting to be discussed?

**Comment by yokishava** [comment]
Thank you for comment.
As you say, it is a big change. Can we throw this out to the slack channel instead of the meeting?

**Comment by alexec** [comment]
The addition of any field to `NodeStatus` cause the size of the Workflow object in Kubernetes to increase. This field is unlimited in length. It could easily 2x or 3x the storage needed. We should not add this without limiting it's max length.

Is this field intended to be templated? If not, we don't need to add it to `NodeStatus`. That reduces the risk.

**Review by alexec — CHANGES_REQUESTED** [review]
Please address my comments.

**Comment by yokishava** [comment]
Thank you for comments. I'm sorry to late reply.
As you say, the object size is easily inflated.
I will close this PR and see if I can add a description field in another way.

**Comment by yokishava** [comment]
Or how about closing the Issue itself?

**Pull request closed without merging**
