### PR TITLE
feat: Workflow/WorkflowTemplate/CronWorkflow write operation audit log

### PR DESCRIPTION
**Pull request by krrrr38**
Signed-off-by: krrrr38 <k.kaizu38@gmail.com>

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

ref https://github.com/argoproj/argo-workflows/issues/4271

- Add util/audit package which support audit logger
- Implement WRITE operation server audit info log for Workflow/WorkflowTemplate/CronWorkflow which includes who do it.

example info logs like followings.

```sh
argo-server | time="2022-01-30T20:40:07.267Z" level=info msg="CronWorkflow Resume" name=my-cronworkflow-template-1 namespace=argo
argo-server | time="2022-01-30T20:40:07.866Z" level=info msg="CronWorkflow Suspend" name=my-cronworkflow-template-1 namespace=argo
argo-server | time="2022-01-30T20:40:19.198Z" level=info msg="Workflow Submit" cronWorkflow= name=jsonlog-wcgdk namespace=argo phase= workflowTemplate=jsonlog
argo-server | time="2022-01-30T20:40:22.413Z" level=info msg="Workflow Terminate" cronWorkflow= name=jsonlog-wcgdk namespace=argo phase=Running workflowTemplate=jsonlog
```

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
I think we should log all HTTP requests in the logs. This can be done with an interceptor.

**Comment by krrrr38** [comment]
@alexec For example, interceptor SumitWorkflow log has following information.

```
time="2022-02-01T04:49:21.289Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=SubmitWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2022-02-01T04:49:21Z" grpc.time_ms=66.435 span.kind=server system=grpc
```

I think this log doesn't have following information.
- Who kick this api
- Which workflows/workflowtemplate/cronworkflow are generated/edited.

**Comment by krrrr38** [comment]
I'll try another PR. So close this one. Thanks.

**Comment by krrrr38** [comment]
I found gatekeeper log which is used for audit log. https://github.com/argoproj/argo-workflows/pull/7748 try to add more information.

**Comment by tooptoop4** [comment]
where @krrrr38

**Pull request closed without merging**
