### PR TITLE
chore: fix small typos: NowWait -> NoWait

### PR DESCRIPTION
**Pull request by Sebast1aan**
Fixing small typos in the doc: NowWait should be NoWait

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
You are modifying the generated file. You’ll need to modify the original source and run codegen

**Comment by Sebast1aan** [comment]
Oops, my bad. Can you elaborate a bit on what the codegen step takes as input and output? I currently don't have a development machine available, so I cannot run codegen. Feel free to take over the PR. (although I should give codespaces a try after the fix in #11981)

For reference, the NowWait is present at least once in following files:
[argoproj/argo-events](https://github.com/argoproj/argo-events) · [api/event-source.md](https://github.com/argoproj/argo-events/blob/75a2512413cb0b59e80882264c98a58089e505b8/api/event-source.md?plain=1#L98)

[argoproj/argo-events](https://github.com/argoproj/argo-events) · [api/event-source.html](https://github.com/argoproj/argo-events/blob/75a2512413cb0b59e80882264c98a58089e505b8/api/event-source.html#L88)

[argoproj/argo-schema-generator](https://github.com/argoproj/argo-schema-generator) · [schema/argo_events_kustomize_schema.json](https://github.com/argoproj/argo-schema-generator/blob/abfc3413799e4946f8793300d526c892231699b4/schema/argo_events_kustomize_schema.json#L582)

[argoproj/argo-events](https://github.com/argoproj/argo-events) · [pkg/apis/eventsource/v1alpha1/types.go](https://github.com/argoproj/argo-events/blob/75a2512413cb0b59e80882264c98a58089e505b8/pkg/apis/eventsource/v1alpha1/types.go#L453)

[argoproj/argo-events](https://github.com/argoproj/argo-events) · [pkg/apis/eventsource/v1alpha1/generated.proto](https://github.com/argoproj/argo-events/blob/75a2512413cb0b59e80882264c98a58089e505b8/pkg/apis/eventsource/v1alpha1/generated.proto#L52)

Not sure which of those are relevant.

**Comment by agilgur5** [comment]
> [argoproj/argo-events](https://github.com/argoproj/argo-events) · [pkg/apis/eventsource/v1alpha1/types.go](https://github.com/argoproj/argo-events/blob/75a2512413cb0b59e80882264c98a58089e505b8/pkg/apis/eventsource/v1alpha1/types.go#L453)

This is the only source file from the list, the rest are generated from that comment. You can see some compiler directive inside and around that struct for the codegen

> I currently don't have a development machine available, so I cannot run codegen.

For reference, you will need to run codegen on any PR that will result in changing generated code. `pre-commit` and CI will fail without it as they are committed to the repo currently

**Comment by Sebast1aan** [comment]
> > [argoproj/argo-events](https://github.com/argoproj/argo-events) · [pkg/apis/eventsource/v1alpha1/types.go](https://github.com/argoproj/argo-events/blob/75a2512413cb0b59e80882264c98a58089e505b8/pkg/apis/eventsource/v1alpha1/types.go#L453)
> 
> This is the only source file from the list, the rest are generated from that comment. You can see some compiler directives for the codegen inside and around that struct
> 
> > I currently don't have a development machine available, so I cannot run codegen.
> 
> For reference, you will need to run codegen on any PR that will result in changing generated code. `pre-commit` and CI will fail without it as they are committed to the repo currently

I'm currently not seeing how to link the pieces together: what would be the flow to get the typos fixed?
1. Checkout the Argo-Events repo to fix the typos in the source file
2. Run codegen on the Argo-Events repo checkout and commit any output files + the source files
3. Open a PR in the Argo-Events repo
4. When Argo-Workflows updates the version number of Argo-Events, run codegen again for the Argo-Workflows repo and commit any changes in the output files
5. Open a PR in the Argo-Workflows repo
(In which 4-5 are performed by the maintainer upgrading the version Argo-Events)

**Comment by agilgur5** [comment]
Yep, that flow sounds about right to me, so I think you inferred correctly! 🙂

**Comment by Sebast1aan** [comment]
Ok, this PR can thus be closed.

**Pull request closed without merging**
