### PR TITLE
feat: Improve schema validation. Fixes #11021

### LINKED ISSUE #11021: Improve schema by utilizing "additionalProperties": false
# Summary

Many definitions are missing `additionalProperties`, and by default JSON Schema assumes additional properties are allowed if `additionalProperties` is missing. Consequently, mistyped properties are easily missed as validators considers those valid additional properties even if an object actually doesn't allow additional properties.

Basically only need to add `"additionalProperties": false` to each definition that doesn't permit additional properties.

Reference:
https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties
https://github.com/argoproj/argo-workflows/blob/master/api/jsonschema/schema.json

# Use Cases

Better validation, particularly catching mistyped properties early on.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by Kitanotori**
See #11021 for details

`"additionalProperties": false` applied in following way:

```
yq -i -o=json '(.. | select(has("type") and .type == "object" and has("properties") and (has("additionalProperties") | not))).additionalProperties |= false' swagger.json

make
```

i.e., for each object that has "properties" but no existing "additionalProperties" set. In case there are no "properties" (i.e. no defined structure) the change would prevent any properties being passed, so wanted to avoid that.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
These are generated files so you may want to modify the original source and run codegen.

**Comment by Kitanotori** [comment]
@terrytangyuan Do you know which are all the files I should modify, or if there's some documentation regarding how to modify the definitions?

**Comment by terrytangyuan** [comment]
I think the ones you are modifying belong in Argo Events repo.

**Comment by tooptoop4** [comment]
dis 🔥 @nakamorichi

**Pull request closed without merging**
