### PR TITLE
fix: Fix kill sidecar timeout issue. Fixes ##6693

### PR DESCRIPTION
**Pull request by henrywangx**
Fixes ##6693

### CODE REVIEW

**Comment by alexec** [comment]
Please can you sign-off your commits to pass the DCO check?

**Review by alexec — APPROVED** [review]
Please can you sign-off your commits to pass the DCO check?

**Comment by sarabala1979** [comment]
@henrywangx Please can you sign-off your commits to pass the DCO check?

**Comment by henrywangx** [comment]
> @henrywangx Please can you sign-off your commits to pass the DCO check?

@sarabala1979 done. Meanwhile I'm wondering how we cherry pick this fix into other releases after merged(sorry, I'm new to open source contribution).

**Review by alexec — APPROVED** [review]

**Pull request merged**
