### PR TITLE
feat: DAG/TASK Custom Metrics Example

### PR DESCRIPTION
**Pull request by everton-nasc**
DAG/TASK custom metrics example.
1. Emit custom metrics per each tasks using `withItems`.
2. Emit custom metric per task workflow.

### Results
```bash
# HELP argo_workflows_playground_workflow_duration_task_seconds Duration gauge by name in seconds - task level
# TYPE argo_workflows_playground_workflow_duration_task_seconds gauge
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-A",status="Succeeded"} 7
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-B",status="Succeeded"} 7
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-ONE-A",status="Succeeded"} 7
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-ONE-B",status="Succeeded"} 6
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-TWO-A",status="Succeeded"} 6
argo_workflows_playground_workflow_duration_task_seconds{playground_id_workflow="TEST-TWO-B",status="Succeeded"} 6
```

```bash
# HELP argo_workflows_playground_workflow_result_task_counter Count of workflow execution by result status  - task level
# TYPE argo_workflows_playground_workflow_result_task_counter counter
argo_workflows_playground_workflow_result_task_counter{playground_task_name_counter="TEST-ONE-A",status="Succeeded"} 1
argo_workflows_playground_workflow_result_task_counter{playground_task_name_counter="TEST-ONE-B",status="Succeeded"} 1
argo_workflows_playground_workflow_result_task_counter{playground_task_name_counter="TEST-TWO-A",status="Succeeded"} 1
argo_workflows_playground_workflow_result_task_counter{playground_task_name_counter="TEST-TWO-B",status="Succeeded"} 1
```
Signed-off-by: Everton <58737540+everton-nasc@users.noreply.github.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Review by alexec — COMMENTED** [review]
can you please comment on how you tested this example?

**Comment by everton-nasc** [comment]
> can you please comment on how you tested this example?

Sure thing.

I've used the argo workflow UI (`submit a new workflow`) button and pasted this example to create the test workflow.
Also, I've port-forwared the metrics service in order to check if the metrics were emitted properly.
`kubectl port-forward svc/workflow-controller-metrics 9090:9090 -n argo`

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
You'll probably need to run `make codegen`.

**Comment by everton-nasc** [comment]
> You'll probably need to run `make codegen`.

Yep, I'm trying to run, but facing a couple of issues:
```bash
❯ make codegen
GIT_COMMIT=d7178655c49e6ada71d2d515c538572eb90de00f GIT_BRANCH=dag-custom-metric GIT_TAG=untagged GIT_TREE_STATE=clean RELEASE_TAG=false DEV_BRANCH=true VERSION=latest
KUBECTX=xpto DOCKER_DESKTOP=false K3D=false DOCKER_PUSH=false
RUN_MODE=local PROFILE=minimal AUTH_MODE=hybrid SECURE=false STATIC_FILES=false ALWAYS_OFFLOAD_NODE_STATUS=false UPPERIO_DB_DEBUG=0 LOG_LEVEL=debug NAMESPACED=true
# protoc pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto
[ -e ./vendor ] || go mod vendor
protoc -I /usr/local/include -I /Users/evertonnascimento/projects/argo-workflows -I /Users/evertonnascimento/projects/argo-workflows/vendor -I /Users/evertonnascimento/go/src -I /Users/evertonnascimento/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto -I /Users/evertonnascimento/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.16.0/third_party/googleapis --gogofast_out=plugins=grpc:/Users/evertonnascimento/go/src --grpc-gateway_out=logtostderr=true:/Users/evertonnascimento/go/src --swagger_out=logtostderr=true,fqn_for_swagger_name=true:. pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto
/Users/evertonnascimento/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto: warning: directory does not exist.
github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/generated.proto: File not found.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:6:1: Import "github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/generated.proto" was not found or had errors.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:15:5: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:31:5: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:41:5: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:46:87: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:53:81: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:57:84: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplateList" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:61:87: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:72:83: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
make: *** [pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.swagger.json] Error 1
```

**Comment by alexec** [comment]
Try `make pre-commit -B`

**Comment by everton-nasc** [comment]
> Try `make pre-commit -B`

It seems the same error:
```bash
Generating deepcopy funcs
Generating clientset for workflow:v1alpha1 at github.com/argoproj/argo-workflows/v3/pkg/client/clientset
Generating listers for workflow:v1alpha1 at github.com/argoproj/argo-workflows/v3/pkg/client/listers
Generating informers for workflow:v1alpha1 at github.com/argoproj/argo-workflows/v3/pkg/client/informers
[ -e ./v3 ] && rm -rf v3
# protoc pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto
[ -e ./vendor ] || go mod vendor
protoc -I /usr/local/include -I /Users/evertonnascimento/projects/argo-workflows -I /Users/evertonnascimento/projects/argo-workflows/vendor -I /Users/evertonnascimento/go/src -I /Users/evertonnascimento/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto -I /Users/evertonnascimento/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.16.0/third_party/googleapis --gogofast_out=plugins=grpc:/Users/evertonnascimento/go/src --grpc-gateway_out=logtostderr=true:/Users/evertonnascimento/go/src --swagger_out=logtostderr=true,fqn_for_swagger_name=true:. pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto
/Users/evertonnascimento/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto: warning: directory does not exist.
github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/generated.proto: File not found.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:6:1: Import "github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/generated.proto" was not found or had errors.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:15:5: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:31:5: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:41:5: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:46:87: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:53:81: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:57:84: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplateList" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:61:87: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.proto:72:83: "github.com.argoproj.argo_workflows.v3.pkg.apis.workflow.v1alpha1.ClusterWorkflowTemplate" is not defined.
make: *** [pkg/apiclient/clusterworkflowtemplate/cluster-workflow-template.swagger.json] Error 1
```
Also double-checked the environment var for Go:
```bash
PATH=/Users/evertonnascimento/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/go/bin/go:/Users/evertonnascimento/go:/Users/evertonnascimento/go/bin:/usr/local/go:/Users/evertonnascimento/go:/Users/evertonnascimento/go/bin:/usr/local/go/bin:/Users/evertonnascimento/go/bin
GOPATH=/Users/evertonnascimento/go
GOROOT=/usr/local/go
GOBIN=/Users/evertonnascimento/go/bin
```

**Comment by alexec** [comment]
You could also copy and past the diffs from the job.

**Pull request merged**
