### PR TITLE
docs: add internal redirects for moved or renamed pages

### PR DESCRIPTION
**Pull request by agilgur5**
Follow-up to #11516, #12042, https://github.com/argoproj/argo-workflows/issues/11390#issuecomment-1876274288

### Motivation

- This will allow us to move and rename pages in the docs, with two existing uses:
  - `webhdfs.md` was under `use-cases/`, though that it is for generic things like "Machine Learning"
    - move it under `patterns` in the ToC instead, which is more appropriate

  - `manually-create-secrets.md` had a confusing sub-path name, renamed to match the heading: `service-account-secrets.md`
    - the new name matches its current heading

### Modifications

- add [`mkdocs-redirects`](https://github.com/mkdocs/mkdocs-redirects) plugin and configuration
  - also add the default plugin `search` to the list as it gets overridden (this is the first plugin we're using actually (vs theme or markdown extension))
    - as per the `mkdocs-redirects` [README](https://github.com/mkdocs/mkdocs-redirects/blob/3b36c72dc50c41da5fcf9604be845648d415db0d/README.md?plain=1#L29) and the `mkdocs` [config docs](https://www.mkdocs.org/user-guide/configuration/#plugins)
  
- convert `webhdfs.md` page's own links as it is no longer under a subdirectory (`../` -> ``)
- convert 1 link to `manually-create-secrets.md` to its new name

### Verification

1. `mkdocs build`
1. `open site/use-cases/webhdfs/index.html` causes a redirect (it uses both the `meta` `refresh` tag as well as a back-up `script`
    - new generated code from the plugin is:
    ```html
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Redirecting...</title>
        <link rel="canonical" href="../../webhdfs/">
        <meta name="robots" content="noindex">
        <script>var anchor=window.location.hash.substr(1);location.href="../../webhdfs/"+(anchor?"#"+anchor:"")</script>
        <meta http-equiv="refresh" content="0; url=../../webhdfs/">
    </head>
    <body>
    Redirecting...
    </body>
    </html>
    ```
      - interestingly, the back-up `script` does take into consideration anchors, which I mentioned in https://github.com/argoproj/argo-workflows/pull/12362#issuecomment-1871470972
1. same for `site/manually-create-secrets/index.html`

Screenshot of `webhdfs.md` correctly placed in the ToC under "Patterns" and _not_ "Use Cases":
Screenshot 2024-01-12 at 7 58 40 PM

### CODE REVIEW

**Comment by jmeridth** [comment]
> interestingly, the back-up script does take into consideration anchors, which I mentioned in https://github.com/argoproj/argo-workflows/pull/12362#issuecomment-1871470972

Do we want to add this to #12500 or a future PR or just stating an observation?

**Review by jmeridth — APPROVED** [review]
Nice find on the plugin.

**Comment by agilgur5** [comment]
> Do we want to add this to #12500 or a future PR or just stating an observation?

I haven't tested it yet, but if it does properly redirect anchors (i.e. if the JS goes first before the HTML redirect), I do think it would be good to add in a future PR.

**Review by isubasinghe — APPROVED** [review]

**Comment by agilgur5** [comment]
Backported cleanly to `release-3.5` as 72504d1466e9ebd47c51b66ea773d17571bd3f15

**Pull request merged**
