### PR TITLE
docs: fix broken links + add back check

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- `make docs-linkcheck` found two broken links
  - command runs fine on my local machine now, so maybe https://github.com/argoproj/argo-workflows/pull/10678 was due to an error that was patched

- while fixing that, noticed that the Nix folder got moved to `dev/nix/` in https://github.com/argoproj/argo-workflows/pull/10999/commits/c505e80f572242ebbbef850f6dbd36979ebb8c3d

### Modifications

- fixed both broken links by adding versioned permalinks to updated locations
- uncomment `docs-linkcheck` from `make docs`
- corrected Nix directory comment

### Verification

Ran `make docs`

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Where did you add the CI back?

**Comment by agilgur5** [comment]
I perhaps used the word "CI" a bit generically in the title; I meant the uncommenting of [`make docs-linkcheck`](https://github.com/argoproj/argo-workflows/pull/11301/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R663)

I'll remove that from the title so it's just "check"

**Comment by terrytangyuan** [comment]
I am disabling it again since it's flaky. https://github.com/argoproj/argo-workflows/pull/11305

**Comment by agilgur5** [comment]
aw dang. it is working now though, but as it does live checks on sites, depends on website availability and got a 503:
```
  [✖] https://www.jenkins.io/doc/pipeline/steps/pipeline-input-step/ → Status: 503
  ERROR: 1 dead links found in docs/intermediate-inputs.md !
```

guess it might be better to run as a weekly job. or preferably, to only run on changed docs. potentially not worth the effort to implement.

Related but separately, I was looking to optimize the CI pipeline with something like https://github.com/tj-actions/changed-files so that, primarily, E2E tests are skipped for docs-only changes (i.e. limited to the `docs/` folder).

**Comment by terrytangyuan** [comment]
That would be great. There's an existing issue for that I think

**Comment by agilgur5** [comment]
> There's an existing issue for that I think

I couldn't find this when you first mentioned it. Randomly stumbled upon it today and assigned myself:  #10265

**Pull request merged**
