### PR TITLE
chore(deps): use `docker/login-action` consistently instead of `Azure/docker-login`

### PR DESCRIPTION
**Pull request by agilgur5**
Follow-up to #12775

### Motivation

- `Azure/docker-login` seems to have been the first one to have been added in #3291, then `docker/login-action` was added after in #4127, but currently _both_ are being used without consistency

- [`Azure/docker-login`](https://github.com/Azure/docker-login) is not maintained much, with the [last release](https://github.com/Azure/docker-login/releases/tag/v1.0.1) ~1.5 years ago and no update to Node v20 as of yet, despite issues and PRs on it from a few months ago (https://github.com/Azure/docker-login/issues/63, https://github.com/Azure/docker-login/pull/64)

### Modifications

- consistently use [`docker/login-action`](https://github.com/docker/login-action), which is more maintained, more centralized, more commonly used, and not on EoL Node
    - [last release](https://github.com/docker/login-action/releases/tag/v3.0.0) a few months ago, [last commit](https://github.com/docker/login-action/commit/566711b9b940f3a4aea3c883c1efeb76ab18c145) a few weeks ago

### Verification

This only runs during releases, so a bit hard to test 😕

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Why not combining with https://github.com/argoproj/argo-workflows/pull/12775?

**Comment by agilgur5** [comment]
> Why not combining with #12775?

Well, to begin with, that one was made a few days beforehand (both made 2+ weeks ago), and has now been merged earlier too.

Otherwise there are purposes are different, per PR title and the "Motivation" section in each. That one is an update, this one is changing the action itself to a different one (which happens to be more updated). That also entails different risk levels for each.

Similar to mine and others' PRs in the past, they are also independent of each other and so don't need to be tied together.

**Comment by agilgur5** [comment]
Merged `main` for new PR checks per #13027

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
Huh so this did partially [fail](https://github.com/argoproj/argo-workflows/actions/runs/9409633233/job/25920972244) on release on `main`:

```
Run echo $(jq -c '. + { "experimental": "enabled" }' ${DOCKER_CONFIG}/config.json) > ${DOCKER_CONFIG}/config.json
jq: error: Could not open file /config.json: No such file or directory
/home/runner/work/_temp/3b2a11f7-f9e3-4c1e-8ab2-431101712831.sh: line 1: /config.json: Permission denied
```

All the builds and pushes of images worked, it's the manifest push that failed; i.e. [this line](https://github.com/argoproj/argo-workflows/blob/bda02806cdc27216cd0ce33418997bf5a4215ae1/.github/workflows/release.yaml#L175), which I didn't change in the PR.

It seems like `${DOCKER_CONFIG}` is empty per the error message 🤔 So it may have only been set by `Azure/docker-login`, which means the code was relying on an env var side effect, if I'm understanding correctly.
The default is `~/.docker/config.json` so this may be easily replaceable

**Comment by agilgur5** [comment]
> The default is `~/.docker/config.json` so this may be easily replaceable

Added this as a default in #13155

**Pull request merged**
