### PR TITLE
Create test.yml

### PR DESCRIPTION
**Pull request by MarkHarris21**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
Are you serious?!?!

**Comment by alexec** [comment]
User reported for crypto-mining scam.

**Comment by alexec** [comment]
@edlee2121 @jessesuen FYI, this user attempted to raise a PR that added blatant crypto-mining code. I'm reported and blocked them.

**Comment by pedrobaeza** [comment]
He has created several PRs in repositories like mine. I'm reporting to active contributors of the other ones to stop it. Probably it will be banned soon by GH, as I have already reported as well.

**Pull request closed without merging**
