### PR TITLE
fix: use upstream go-git. Fixes #10091

### LINKED ISSUE #10091: move away from go-git
# Summary

We changed the git library in v3.4 to [go-git](https://github.com/go-git/go-git/) which seems to have a lot of bugs and also is not actively maintained, the last release created for this project was on June 2, 2021, which was more than an year ago. Currently we are maintaining our own fork of go-git at [argoproj-labs/go-git](https://github.com/argoproj-labs/go-git). There's a similar package [git2go](https://github.com/libgit2/git2go) which has go bindings for [libgit2](https://libgit2.org/) and is also actively maintained and being used widely. Should we consider migrating to that package?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by weafscast**
Fixes #10091 

### Motivation

go-git is back to maintenance and active for a couple of months already so we should contribute any changes back to upstream and switch back to upstream go-git: [go-git/go-git](https://github.com/go-git/go-git)

### Modifications

Replace our own fork with upstream go-git

### Verification

CI Tests

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Any update on this?

**Comment by weafscast** [comment]
I wasn't able to dedicate a lot of time to this due to work commitments.

I will provide an update on this over the weekend. If I find that I cannot work on this, I will also communicate that in my update.

**Comment by weafscast** [comment]
It seems like I can find some time this week to fix this.

**Comment by terrytangyuan** [comment]
Closing in favor of https://github.com/argoproj/argo-workflows/pull/11149

**Comment by agilgur5** [comment]
Superseded by #12515

**Pull request closed without merging**
