### PR TITLE
feat: limit total number of pods created by the controller. Fixes #4561

### LINKED ISSUE #4561: Limit total number of pods created by the controller
# Summary

Kubernetes clusters often max out with a number of scheduled running pods.  For us, limiting this to 5k allow us to protect ourselves. 

# Use Cases

Prevent broken clusters. Protect other cluster users. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by weafscast**
Signed-off-by: weafscast <weafscast@proton.me>

Fork of #9878 with added test(weren't present in original pr).

The original pr has been stale since ~6 months

Fixes #4561

### CODE REVIEW

**Comment by weafscast** [comment]
@terrytangyuan the failing test is unrelated and is passing for me locally, could it be a flake?

**Comment by alexec** [comment]
Could you create a ResourceQuote directly?

**Comment by diegofd** [comment]
> Could you create a ResourceQuote directly?

@alexec could you clarify what do you mean?

**Comment by weafscast** [comment]
unstale, will resume.

**Comment by caelan-io** [comment]
Hi @weafscast , do you have plans to finish this PR? Thanks for the update so we can prioritize accordingly.

**Comment by shuangkun** [comment]
Very useful PR, will you complete it? @weafscast

**Comment by juliev0** [comment]
Closing this PR as it's been stale for awhile.

**Comment by tooptoop4** [comment]
where @weafscast

**Pull request closed without merging**
