### PR TITLE
feat(ui): add full workflow name in list details. Fixes #11949

### LINKED ISSUE #11949: UI: Show full (long) name of workflow in list
# Summary
So let say that you want to search (CNTRL+F) for workflow with generated id like `-zxy123` in `long-long-long-long-long-long-workflow-name-zxy123` 

But cannot pin point which is the worklow that we looking for

## Use Cases

When I go to the UI what i see is `long-long-long-lon...` (i dont know what the minimum character to make it have `...`) when search `-zxy123` it found 1 but i cannot point which is which (imagine 20-30 long-long-long-lon...) 

image

And I also expect if I opened `Show Details` it will show full name of the workflow. But it doesnt
image

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by polarbear567**
Fixes #11949

### Motivation

Issue 11949 want to add full name in details.

### Modifications

Added full name in details.

### Verification

I built argo in my local, and watched the change in ui.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Can you test the responsiveness and various lengths of names?

**Comment by polarbear567** [comment]
long
short
Hi @terrytangyuan 
This is screenshot. What else do I need to provide?

**Comment by agilgur5** [comment]
A screenshot on a small window width -- the browser devtools has options for this: https://developer.chrome.com/docs/devtools/device-mode

In this case, it's a full row, so not sure if it's possible for it to even overflow given the name size limit in k8s

**Review by agilgur5 — APPROVED** [review]
Code LGTM, this is exactly what I suggested in the issue

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
