### PR TITLE
fix(ui): Correctly show zero-state when CRDs not installed. Fixes #7001

### LINKED ISSUE #7001: Improve signposting for integrations
# Summary
As of v3.2.0, an integration with Argo Dataflow has been added to the Workflow UI, but the integration isn't really documented on the project page, and the errors that pop up when trying to access the new pipelines tab don't really give much indication of what is supposed to be providing the pipeline functionality.

Currently, if someone new to Workflow deploys the Workflow stack and clicks the Pipelines tab, all they'll see is an RBAC permission error, and if that's resolved, an error that the Pipeline CRD isn't found in the cluster. Only if Dataflow is installed on the cluster will they be shown a summary of the fact that Dataflow is providing the functionality, along with a link to the docs.

What change needs making?
The current ZeroState behavior of the Pipelines page in the Workflow UI should display in the event that either permissions are not correctly configured or the required CRDs are not installed, as well as the underlying error message. Also, the docs should probably contain some mention of the new pipeline functionality and what provides it (this may also apply to Events integration, the docs mostly call it out in the roadmap).

# Use Cases

This would be of most benefit to operators who are new to workflows and unfamiliar with the full Argo project suite, especially in the case of a relatively new addition like Dataflow.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Fixes #7001

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!
* 
Screenshot 2021-11-04 at 08 21 27
Screenshot 2021-11-04 at 08 21 39
Screenshot 2021-10-31 at 11 17 45

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Could you paste the screenshots after this change?

**Comment by alexec** [comment]
> Could you paste the screenshots after this change?

That is the screen shots I've attached?

**Comment by terrytangyuan** [comment]
It might be better to remove the "Not Found" notice at the top since this is the default behavior and we don't assume users have those installed.

**Comment by alexec** [comment]
> It might be better to remove the "Not Found"

I don't think you can differentiate "Not Found" from other errors.

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
