### PR TITLE
feat: allow setting loglevel and gloglevel for server

### PR DESCRIPTION
**Pull request by jmeridth**
With `logFormat` being added to server 2 years ago [here](https://github.com/argoproj/argo-workflows/pull/5158/files#diff-42623a9b98b20e51352de53c9e3283f5d13fcb2b9144bb2b62f7247119b773a1R46) figured we can add log levels also?

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [ ] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Comment by jmeridth** [comment]
Outstanding questions I have:
- Am I missing a place this option needs to be injected?
  -  Is this something we can't set for the server?  
- Have we never imported `"github.com/argoproj/pkg/cli"` on the server for a particular reason?

**Comment by jmeridth** [comment]
Docs need to be updated it seems.  Working on it.

**Comment by jmeridth** [comment]
CI says https://towardsdatascience.com/running-a-data-replication-pipeline-on-kubernetes-with-argo-and-singer-io-2fab5b0bad?utm_source=argo-docs is a dead link but it works for me in the browers and `make docs-linkcheck` passes for me locally

**Review by alexec — APPROVED** [review]

**Comment by jmeridth** [comment]
After the CI sdk failures I'm getting the following locally when I try to start the API with `make clean && make start API=true`. 

```
argo-server | ./dist/argo flag redefined: log_dir
argo-server | panic: ./dist/argo flag redefined: log_dir
argo-server | goroutine 1 [running]:
argo-server | flag.(*FlagSet).Var(0xc0001b4300, {0x2fe8d80, 0x44f7420}, {0x29f0608, 0x7}, {0x2a6c685, 0x2f})
argo-server |   /usr/local/go/src/flag/flag.go:879 +0x2f4
argo-server | flag.(*FlagSet).StringVar(...)
argo-server |   /usr/local/go/src/flag/flag.go:762
argo-server | k8s.io/klog/v2.InitFlags(0x5?)
argo-server |   /Users/jasonmeridth/go/pkg/mod/k8s.io/klog/v2@v2.60.1/klog.go:407 +0x55
argo-server | github.com/argoproj/argo-workflows/v3/util/cmd.SetGLogLevel(0x7ffc0ad9205b?)
argo-server |   /Users/jasonmeridth/go/src/github.com/argoproj/argo-workflows/util/cmd/glog.go:14 +0x25
argo-server | github.com/argoproj/argo-workflows/v3/cmd/argo/commands.NewServerCommand.func1(0xc000a57400?, {0x29eb4af?, 0x9?, 0x9?})
argo-server |   /Users/jasonmeridth/go/src/github.com/argoproj/argo-workflows/cmd/argo/commands/server.go:75 +0x185
argo-server | github.com/spf13/cobra.(*Command).execute(0xc000a57400, {0xc000a76000, 0x9, 0x9})
argo-server |   /Users/jasonmeridth/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
argo-server | github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c2a00)
argo-server |   /Users/jasonmeridth/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
argo-server | github.com/spf13/cobra.(*Command).Execute(...)
argo-server |   /Users/jasonmeridth/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
argo-server | main.main()
argo-server |   /Users/jasonmeridth/go/src/github.com/argoproj/argo-workflows/cmd/argo/main.go:14 +0x1e
argo-server | Terminating argo-server
```

I was trying to start the API so I could run `make --directory sdks/python install test -B`.

This made me hunt more and sure enough, bot the `cli.setLogLevel(logLevel)` and `cmd.setGLogLevel(gLogLevel)` are provided through parent commands from:

- main.go brings in NewCommand [here](https://github.com/argoproj/argo-workflows/blob/c0db6fd1b25fac6302b6f95c4e5f6b807291737d/cmd/argo/main.go#L14)
- NewCommand wires up ServerCommand [here](https://github.com/argoproj/argo-workflows/blob/c0db6fd1b25fac6302b6f95c4e5f6b807291737d/cmd/argo/commands/root.go#L100)
- NewCommand also wires up loglevels [here](https://github.com/argoproj/argo-workflows/blob/c0db6fd1b25fac6302b6f95c4e5f6b807291737d/cmd/argo/commands/root.go#L128-L129)

Closing this PR.  Nice job CI tests.  You did your job.

**Pull request closed without merging**
