### PR TITLE
chore(deps): bump google.golang.org/grpc from v1.38.0 to v1.41.1

### PR DESCRIPTION
**Pull request by blkperl**
Signed-off-by: William Van Hevelingen <william.vanhevelingen@acquia.com>

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Comment by blkperl** [comment]
This should unblock dependabot from updating viper in  https://github.com/argoproj/argo-workflows/pull/7645

**Review by terrytangyuan — APPROVED** [review]
LGTM. @alexec Please help double check as well.

**Comment by blkperl** [comment]
@terrytangyuan any idea on how to fix the failing e2e test?

**Comment by terrytangyuan** [comment]
> @terrytangyuan any idea on how to fix the failing e2e test?

Perhaps the new version changed the default content type? I’d check the release notes to see if anything else needs to be updated.

**Comment by alexec** [comment]
Look like it broke the test, that needs fixing.

**Review by alexec — CHANGES_REQUESTED** [review]
I wonder if we should change dependant to only update the patch version, too many minor versions seem to be breaking.

**Comment by blkperl** [comment]
@terrytangyuan @alexec I checked the grpc release notes and nothing stood out to me. I'm not familiar with grpc so I'm not quite sure what to try next.

**Comment by blkperl** [comment]
I asked upstream about 1.42.0 https://github.com/grpc/grpc-go/issues/5175

**Comment by blkperl** [comment]
@alexec We can merge this in the meantime as it passes on grpc 1.41.1.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Thank you!

**Pull request merged**
