### PR TITLE
fix: SDK CI workflow

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Fixes #TODO

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by alexec** [comment]
To test this change, you could push to `origin/dev-9609` and I think SDK will be published.

**Comment by alexec** [comment]
The SDK YAML is invalid. Not sure if SDKs public at all.

**Comment by terrytangyuan** [comment]
Python SDK seems to be published for 3.4.1

**Comment by terrytangyuan** [comment]
Let's merge this?

**Pull request merged**
