### PR TITLE
docs: BackUp Command Update

### PR DESCRIPTION
**Pull request by reddymh**
Signed-off-by: Rajshekar Reddy [reddymh@gmail.com](mailto:reddymh@gmail.com)

Current document shows command takes back up only on default namespace not from all the namespace

### CODE REVIEW

**Comment by sarabala1979** [comment]
@reddymh Please do DCO to fix the build failure

**Review by reddymh — COMMENTED** [review]
Signed-off-by: Rajshekar Reddy (reddymh@gmail.com)

**Comment by tczhao** [comment]
> Thanks for this. Just to make sure, what happens if you pass in "-A" but don't have access to other namespaces? Does it just report the namespaces you do have read access to?

The namespaced will use Role/ClusterRole rbac, -A will use ClusterRole rbac
If the account doesn't have cluster scope access, it will get blocked, so -A either returns all or none

**Comment by tczhao** [comment]
@reddymh to fix DCO you need to 
```
git commit -s --amend
git push -f
```

**Comment by juliev0** [comment]
> > Thanks for this. Just to make sure, what happens if you pass in "-A" but don't have access to other namespaces? Does it just report the namespaces you do have read access to?
> 
> The namespaced request will use Role/ClusterRole rbac, -A will use ClusterRole rbac If the account doesn't have cluster scope access, it will get blocked, so -A either returns all or none

Thanks. In that case, should we include both options depending on whether all namespaces are required @reddymh ?

**Comment by reddymh** [comment]
@juliev0  current command will only work for default namespace or I can add cluster wide with -A option as well as namespace back up

**Comment by reddymh** [comment]
> @reddymh to fix DCO you need to
> 
> ```
> git commit -s --amend
> git push -f
> ```

I used the same command now for pushing the changes but still same issue.

**Review by alexec — APPROVED** [review]

**Pull request merged**
