### PR TITLE
fix: move to upstream go-git

### PR DESCRIPTION
**Pull request by rohankmr414**
This PR changes the fork go-git dependency to upstream go-git dependency

Fixes #TODO

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Have all the fixes in our argoproj-labs fork landed in upstream yet?

**Comment by rohankmr414** [comment]
No, a critical test is failing

**Comment by rohankmr414** [comment]
will triage

**Comment by agilgur5** [comment]
Superseded by #12515

**Pull request closed without merging**
