### PR TITLE
feat: argo_template env variable without inputs

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/argoproj/argo-workflows/issues/8790

### Motivation

reduce etcd growth

### Modifications

will likely need env variable and else block to maintain existing functionality for some users

### CODE REVIEW

**Comment by tooptoop4** [comment]
what do u think @jswxstw ?

**Comment by jswxstw** [comment]
> what do u think @jswxstw ?

I think this is a better way to decrease the size of pod envs: https://github.com/argoproj/argo-workflows/issues/8790#issuecomment-2381964013.

**Comment by tooptoop4** [comment]
superseded by https://github.com/argoproj/argo-workflows/pull/13742

**Comment by agilgur5** [comment]
You can force push over your old commits to fix DCO instead of opening a new PR (which creates a bit of pollution)

**Pull request closed without merging**
