### PR TITLE
build: rename `master` branch to `main` branch

### LINKED ISSUE #12127: Rename "master" branch to "main" branch
Sub-task of https://github.com/argoproj/argoproj/issues/35 for this repo.

### PR DESCRIPTION
**Pull request by agilgur5**
Fixes #12127

### Motivation

- Prefer more inclusive language

### Modifications

- change GH Actions to use `main` branch in several branch checks
  - and change GH issue templates to use `main` branch
- change scripts to use `main` branch

- change docs to use `main` branch
  - also in many places we had absolute links instead of relative links
    - docs convention is to use relative links where possible
    - changing these to relative links meant that we no longer need to change the branch
    - some docs also linked to the codebase when there's a page in the docs for it; relative link to the docs where appropriate
  - change a few docs to use a permalink instead of a link to `master`
    - Upgrading Notes and Proposals in particular linked to a specific line in a file, which is no longer the correct line
      - fix the broken links with permalinks, since those docs are time-specific
  - change a few links to `argoproj/argoproj/master` to use `main` as well, since per https://github.com/argoproj/argoproj/issues/35 that repo's branch was already renamed 
  - misc docs improvements while changing these lines
    - use code backticks when referring to specific resource names, directories, etc, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#code-style-inline-code)
    - prefer 1 sentence per line where the whole file didn't need changing
    - add a few links to other docs where appropriate (e.g. when referencing environment variables)
    - improve ambiguous link text, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#links)
    - etc

- change UI references (that linked to examples) to use the `main` branch
  - and change one UI reference to link to the rendered docs website instead of the docs on `main`

### Verification

1. `make docs` and `make codegen` passes

1. Used a PR in my own fork (https://github.com/agilgur5/argo-workflows/pull/2) for testing purposes [as suggested](https://github.com/argoproj/argo-workflows/pull/12149#pullrequestreview-1745563352) below.
    - All actions [ran correctly](https://github.com/agilgur5/argo-workflows/actions/runs/6990844946?pr=2) as intended on the `main` branch.

### Notes to Reviewers

We should rename the branch on GH _before_ this is merged.
The branch rename functionality in GH will ensure that everything is redirected to the new branch name as well.

### CODE REVIEW

**Comment by agilgur5** [comment]
> We should rename the branch on GH _before_ this is merged.

Oh this is actually required; the required GH Actions checks aren't running on this PR right now because I changed the filter for PR to `master` to PR to `main`

**Review by terrytangyuan — COMMENTED** [review]
Can you test this in your fork to see if everything works correctly?

**Comment by terrytangyuan** [comment]
I would imagine some of these actions have used the default "master" branch so there's a possibility that workflows break

**Comment by agilgur5** [comment]
> Can you test this in your fork to see if everything works correctly?

Good point, I can check that.

> I would imagine some of these actions have used the default "master" branch so there's a possibility that workflows break

We specify the branch everywhere, so I don't think so. But even if that were the case, GH's redirect should make them work transparently

**Comment by agilgur5** [comment]
Tested this out in https://github.com/agilgur5/argo-workflows/pull/2 and confirmed that all actions ran correctly as intended on the renamed `main` branch!

I also rebased this with latest which should fix a [lint issue](https://github.com/agilgur5/argo-workflows/actions/runs/6990844946/job/19020762991?pr=2) that CI picked up there.

So this is ready to go.
As I mentioned above, the branch rename has to be done beforehand since checks won't run until that is done. I may need to push an empty commit to re-trigger CI on this PR once the rename is completed, as GH may not re-trigger on its own.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Renamed branch.

**Pull request merged**
