### PR TITLE
chore: upgrade argo-ui v2.5.0

### PR DESCRIPTION
**Pull request by krrrr38**
mainly upgrade [rxjs 6.x](https://github.com/ReactiveX/rxjs/blob/6.x/docs_app/content/guide/v6/migration.md).

@types/react-form/react-helmet/react-autocomplete are deleted from argo-ui, but argo-workflows uses them.

```sh
yarn upgrade argo-ui@"https://github.com/argoproj/argo-ui.git#v2.5.0"
yarn add -D '@types/react-form@^2.16.1' '@types/react-helmet@^6.1.0' '@types/react-autocomplete@^1.8.5'
```

argo-ui@v2.5.0 is required for https://github.com/argoproj/argo-workflows/pull/7387

----

<details>
<summary>autocomplete</summary>

image

</details>

<details>
<summary>workflow logs</summary>

https://user-images.githubusercontent.com/915731/150440630-68b956e8-bcac-44c5-9f4e-cdc751c4808f.mov

</details>

<details>
<summary>dropdown</summary>

image

</details>

<details>
<summary>timeline</summary>

https://user-images.githubusercontent.com/915731/150432310-9ea2f48a-50a3-4d5e-976f-325a2cfd2e88.mov

</details>

<details>
<summary>sensor</summary>

image

</details>

<details>
<summary>event source</summary>

image

</details>

<details>
<summary>event flow</summary>

image

</details>

### CODE REVIEW

**Review by alexec — CHANGES_REQUESTED** [review]
You'll need to get `yarn build` working, it appears to be failing with:

    "has no call signatures."

I'm afraid I'm not familiar with this.

Did you managed to get the UI running using `make start UI=true` and perform validation?

**Comment by alexec** [comment]
Fixed on master. Please sync with master to get working.

**Comment by alexec** [comment]
Can I ask for screenshots to demonstrate this is working ok please? Sometimes dep changes break stuff.

**Comment by krrrr38** [comment]
yep, I'm working to do it and paste in this PR description. Now WIP.

**Comment by krrrr38** [comment]
@alexec Now argo-ui v2.5.0 upgrade ready for review. Evidence screenshots are put on this PR description.

**Review by alexec — APPROVED** [review]

**Pull request merged**
