### PR TITLE
fix(executor): Fix git password permission. Fixes #5739

### LINKED ISSUE #5739: Issues with run argoexec used argoworkflow with k8s  enabled  "pod-security-policy" with option readOnlyRootFilesystem
## Summary 

What happened/what you expected to happen?
What happened:

* Problem of getting git artifact with k8s option enabled  "pod-security-policy" with option readOnlyRootFilesystem

## Diagnostics

What Kubernetes provider are you using?
bare metal vanilla k8s -  v1.20.0 - enabled  "pod-security-policy" with option readOnlyRootFilesystem
What version of Argo Workflows are you running?
v3.0.1

```yaml
  kubectl get wf -o yaml  input-artifact-gitncppt 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2021-04-22T14:37:10Z"
  generateName: input-artifact-git
  generation: 3
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        .: {}
        f:arguments: {}
        f:entrypoint: {}
        f:securityContext: {}
        f:serviceAccountName: {}
        f:templates: {}
      f:status: {}
    manager: argo
    operation: Update
    time: "2021-04-22T14:37:10Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/phase: {}
      f:status:
        f:artifactRepositoryRef: {}
        f:conditions: {}
        f:finishedAt: {}
        f:message: {}
        f:nodes: {}
        f:phase: {}
        f:progress: {}
        f:resourcesDuration: {}
        f:startedAt: {}
    manager: workflow-controller
    operation: Update
    time: "2021-04-22T14:37:20Z"
  name: input-artifact-gitncppt
  namespace: wtp-test-argoworkflows
  resourceVersion: "268405633"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/wtp-test-argoworkflows/workflows/input-artifact-gitncppt
  uid: d3dbf6e7-1965-4cb8-bc4d-116e304fb3ea
spec:
  arguments: {}
  entrypoint: git-clone
  securityContext:
    runAsNonRoot: true
    runAsUser: 2000
  serviceAccountName: argo
  templates:
  - container:
      args:
      - git status && ls && cat readme.md
      command:
      - sh
      - -c
      image: artifactory.wgdp.io/wtp-docker/golang:1.10
      name: ""
      resources: {}
      workingDir: /src
    inputs:
      artifacts:
      - git:
          passwordSecret:
            key: password
            name: git-usr
          repo: http://stash.wargaming.net/scm/poseidon/sendpulse.git
          revision: master
          usernameSecret:
            key: username
            name: git-usr
        name: argo-source
        path: /src
    metadata: {}
    name: git-clone
    outputs: {}
status:
  artifactRepositoryRef:
    default: true
  conditions:
  - status: "False"
    type: PodRunning
  - status: "True"
    type: Completed
  finishedAt: "2021-04-22T14:37:20Z"
  message: 'Error (exit code 1): open /git-ask-pass.sh: permission denied'
  nodes:
    input-artifact-gitncppt:
      displayName: input-artifact-gitncppt
      finishedAt: "2021-04-22T14:37:13Z"
      id: input-artifact-gitncppt
      inputs:
        artifacts:
        - git:
            passwordSecret:
              key: password
              name: git-usr
            repo: http://stash.wargaming.net/scm/poseidon/sendpulse.git
            revision: master
            usernameSecret:
              key: username
              name: git-usr
          name: argo-source
          path: /src
      message: 'Error (exit code 1): open /git-ask-pass.sh: permission denied'
      name: input-artifact-gitncppt
      phase: Error
      progress: 1/1
      resourcesDuration:
        cpu: 0
        memory: 0
      startedAt: "2021-04-22T14:37:10Z"
      templateName: git-clone
      templateScope: local/input-artifact-gitncppt
      type: Pod
  phase: Error
  progress: 1/1
  resourcesDuration:
    cpu: 0
    memory: 0
  startedAt: "2021-04-22T14:37:10Z"

```

```
a_pankratyev@LT1-LL-002:~/repos/sendpulse/ci/argo/workflows|WTPOPS-12295⚡ ⇒  kubectl logs  $(kubectl get pods -l app=workflow-controller  -o name) | grep input-artifact-gitncppt  
time="2021-04-22T14:37:10.556Z" level=info msg="Processing workflow" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:10.562Z" level=info msg="Updated phase  -> Running" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:10.563Z" level=info msg="Pod node input-artifact-gitncppt initialized Pending" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:10.625Z" level=info msg="Created pod: input-artifact-gitncppt (input-artifact-gitncppt)" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:10.664Z" level=info msg="Workflow update successful" namespace=wtp-test-argoworkflows phase=Running resourceVersion=268405328 workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Processing workflow" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Pod failed: Error (exit code 1): open /git-ask-pass.sh: permission denied" displayName=input-artifact-gitncppt namespace=wtp-test-argoworkflows pod=input-artifact-gitncppt templateName=git-clone workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Updating node input-artifact-gitncppt status Pending -> Error" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Updating node input-artifact-gitncppt message: Error (exit code 1): open /git-ask-pass.sh: permission denied" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Updated phase Running -> Error" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Updated message  -> Error (exit code 1): open /git-ask-pass.sh: permission denied" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Marking workflow completed" namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.626Z" level=info msg="Checking daemoned children of " namespace=wtp-test-argoworkflows workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.641Z" level=info msg="Workflow update successful" namespace=wtp-test-argoworkflows phase=Error resourceVersion=268405633 workflow=input-artifact-gitncppt
time="2021-04-22T14:37:20.647Z" level=info msg="cleaning up pod" action=labelPodCompleted key=wtp-test-argoworkflows/input-artifact-gitncppt/labelPodCompleted
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexey-pankratyev**
I fixed #5739 issue 

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

### CODE REVIEW

**Review by alexec — CHANGES_REQUESTED** [review]
Looks good. Please can you sign the DCO?

**Comment by alexey-pankratyev** [comment]
> Looks good. Please can you sign the DCO?
I've added 
Signed-off-by: aleksei pankratev <alexey.pankratev@gmail.com>

**Comment by alexey-pankratyev** [comment]
@alexec Checks hasn't passed but it seems with another library problem 
`diff --git a/pkg/apis/workflow/v1alpha1/generated.pb.go b/pkg/apis/workflow/v1alpha1/generated.pb.go`

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Can I ask how you tested this please?

**Comment by alexey-pankratyev** [comment]
> Can I ask how you tested this please?
I created a mini-module with this functionality locally and checked that this file is created in a temporary folder. 
I had to check something differently?

**Comment by alexec** [comment]
Thank you. Can you please sync with master to fix the codegen build job?

**Review by alexec — CHANGES_REQUESTED** [review]
Please run `make codegen lint` to fix lint issues. The, dismiss this review to get re-reviewed.

**Comment by alexey-pankratyev** [comment]
> make codegen lint

I've merge my branch from master upstream and tried build ` make codegen lint` but got an error
`k8s.io/apimachinery/pkg/util/intstr/generated.proto:8:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
2021/05/04 11:05:36 protoc -I . -I /home/a_pankratyev/go/src -I /home/a_pankratyev/repos/argo-workflows/vendor --gogo_out=/home/a_pankratyev/go/src /home/a_pankratyev/repos/argo-workflows/vendor/k8s.io/apimachinery/pkg/util/intstr/generated.proto
2021/05/04 11:05:36 Unable to generate protoc on k8s.io.apimachinery.pkg.util.intstr: exit status 1
make: *** [Makefile:311: pkg/apis/workflow/v1alpha1/generated.proto] Error 1
`
i have fedora33 installed
maybe something is missing in my package configurations?

**Comment by alexec** [comment]
Hmm. Try syncing with master to see if that fixes it.

**Comment by alexey-pankratyev** [comment]
> Hmm. Try syncing with master to see if that fixes it.

I's synced

**Comment by alexey-pankratyev** [comment]
@alexec i'm signed approve  workflow please

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Lgtm

**Pull request merged**
