### PR TITLE
chore: replace deprecated io/ioutil package

### PR DESCRIPTION
**Pull request by maxsxu**
### Motivation
This is the follow-up of #6964

The `io/ioutil` package has already been deprecated since go1.16 and Argo is currently using go1.19 to build, so I suppose we can move forward now. /cc @alexec

### CODE REVIEW

**Comment by maxsxu** [comment]
The [failed test](https://github.com/argoproj/argo-workflows/actions/runs/4787120446/jobs/8512054762?pr=10972) is irrelevant, because all CI passed in [my test PR](https://github.com/atmaxio/argo-workflows/actions/runs/4788172363).

@terrytangyuan Could you help re-run the failed CI job? thanks

**Comment by maxsxu** [comment]
> Good stuff.
> 
> Once we merge this, we'll get conflicts when back-porting any fixes. We should delay merging until close to next release.

Thanks for pointing this out. 
So I suppose you mean we'll merge this PR when ready to release 3.5?

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
Hold off until next release

**Comment by terrytangyuan** [comment]
We'll release a patch soon and then merge this.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Could you resolve conflicts?

**Comment by maxsxu** [comment]
@terrytangyuan Could you help re-run this failed CI job: https://github.com/argoproj/argo-workflows/actions/runs/5312452301/jobs/9616967402?pr=10972 , as it cannot reproduce in my local env.

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
