### PR TITLE
docs: remove tczhao from sustainability effort

### PR DESCRIPTION
**Pull request by juliev0**
### Motivation

I am imagining that tczhao has gotten too busy to be a part of this over the last few months?

### CODE REVIEW

**Comment by juliev0** [comment]
Hey @tczhao - I'm not sure if you have your slack notifications on for CNCF these days? I tried sending you a couple of messages. I know you were able to help out a great deal earlier this year but it seems you haven't been able to contribute much to Argo Workflows since then? Please do let me know if I'm mistaken, thank you!

**Review by agilgur5 — APPROVED** [review]
Approving in case there is no response, will let you merge after you've deemed it enough notice

**Comment by terrytangyuan** [comment]
> I tried sending you a couple of messages.

Tianchu has 3 Slack accounts so it's possible that you didn't send to the one he's paying attention to.

**Comment by agilgur5** [comment]
I thought he might have multiple since there are two "Tianchu Zhao" on Slack, although there is only one in the Sustainability channel and only one has ever sent a message in the Contributors channel (both are the one with the same profile picture as on GitHub)

**Comment by juliev0** [comment]
> > I tried sending you a couple of messages.
> 
> Tianchu has 3 Slack accounts so it's possible that you didn't send to the one he's paying attention to.

Thanks for thinking of this! It’s the same account, and he and I have communicated in the past

**Comment by Joibel** [comment]
I spoke with Tianchu on Friday on a video call, he is employed by the same employer he was and still doing some work on workflows there. I can't speak on his behalf, but he is around.

**Comment by tczhao** [comment]
Hi everyone,
I'm catching up with argo and will start reviewing PRs/issue again in a few days.

Sorry about this, I should've communicated this in slack ahead of time.

I was originally planned to spend 3 weeks doing major repair on my family cars (e.g. engine rebuild) but unexpected things happened and this 3 weeks quickly turned into almost 3 months.... Well, at least everything is good and done now :))

**Comment by juliev0** [comment]
Okay, we can close this then, thanks.

**Pull request closed without merging**
