### PR TITLE
fix: patch report outputs completed if task result not exists.

### PR DESCRIPTION
**Pull request by shuangkun**
Make sure FinalizeOutput executes, let taskresult Completed if taskresult not exists.

### Motivation

When executor didn't have create workflowtaskresult permission.
The workflow won't completed even if all pods completed. Bucause the FinalizeOutput did patch taskresults and annotations.

### Modifications

patch report outputs completed if task result not exists.

### CODE REVIEW

**Review by Joibel — APPROVED** [review]
Ah, this looks like a good catch. LGTM

**Comment by shuangkun** [comment]
Thanks！

**Comment by agilgur5** [comment]
Fixed merge conflict.

**Review by agilgur5 — APPROVED** [review]
This is an edge case of partial permissions, but makes sense to me

**Comment by agilgur5** [comment]
Backported to `release-3.5` as b189afa48
- Fixed a merge conflict due to the log line below having a versioned docs link

**Pull request merged**
