### PR TITLE
docs: full copy-edit of CronWorkflows page

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

Made a lot of modifications to this page during reviews of #13280 and #12696, so wanted to make the rest match the current style guides.
Also aligns with all my other full copy-edits of docs pages

### Modifications

- <details><summary>follow the style guides</summary>

  - simplify a bunch, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language)
  - use active voice and present tense where possible, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-present-tense)
  - avoid Latin phrases, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases)
  - avoid leveling words, per [k8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-words-that-assume-a-specific-level-of-understanding)
  - prefer 1 sentence per line of markdown, per [style guide](https://argo-workflows.readthedocs.io/en/release-3.5/doc-changes/)
  
</details>

- <details><summary>reformat the table of options so that it is readable in markdown </summary>

  - don't center the columns, left-align them
    - there's no reason to center them and this is inconsistent with the rest of the docs; unnecessarily complicated
      - note that later rows did not do this either
  - put the ending `|` one space after the row
    - the very long amount of whitespace would wrap around every row even in my wide screen monitors, despite that only a few options have long descriptions

</details>

- add Wikipedia links to IANA tzs and DST similar to the existing cron link
- specify that the same cron library is used by k8s `CronJobs`

### Verification

`make docs` passes

### CODE REVIEW

**Comment by eduardodbr** [comment]
LGTM

We still need to add documentation related to this [PR](https://github.com/argoproj/argo-workflows/pull/12616) before releasing v3.6. I can work on that

**Comment by eduardodbr** [comment]
> Oh, I forgot about that. Also all my other review comments 😅

Will you work on that or want me to? just to avoid duplicating efforts

**Comment by agilgur5** [comment]
If you could that'd be great. I have a bit too much on my plate as-is right now.

**Review by Joibel — APPROVED** [review]
As a copy edit this improves things so LGTM.

If anyone is going to do content additions I'd like to see a "Good practice" that cronworkflows should use workflowTemplateRef to trigger templates rather than containing the workflow.

**Comment by agilgur5** [comment]
Agreed; we could have a "Best Practices" section at the bottom of this page (and others)

**Pull request merged**
