### PR TITLE
feat(ui): resume on selected node. Fixes #5763

### LINKED ISSUE #5763: Can the resume function only target a node,not target a workflow
# Summary
Current implementation of resume targets workflow. When I have two nodes both suspend template, I just  want only one node resume to go on, other node is still suspend. Like this:

# Use Cases
image
I have two paths both suspend, when I click resume, both of them are resume. I just want D or E to resume instead of workflow.

### PR DESCRIPTION
**Pull request by tczhao**
Fixes #5763 #6666

https://user-images.githubusercontent.com/20961507/136479246-79e10dbb-62f0-4ed4-a810-b65221a03ec2.mp4

Tips:

* Maybe add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.
* If changes were requested, and you've made them, then dismis the review to get it looked at again.
* You can ask for help!

### CODE REVIEW

**Comment by alexec** [comment]
This seems counter intuitive to me. How about we add a "Resume" button on the sliding panel rather than use the one it toolbar?

**Comment by tczhao** [comment]
updated ui with more intuitive flow, added test

**Comment by tczhao** [comment]
Hi @daniel-winter, 
Not sure what exactly what you are referring to as documentation:
I'm thinking the resuming can be done in UI or cli.

The UI should be quite straightforward
For CLI, you can use --node-field-selector options to resume selected nodes
https://argoproj.github.io/argo-workflows/cli/argo_resume/

**Comment by tiwarisanjay** [comment]
@alexec @tczhao  Is it released ? Eagerly waiting for this one to test.

**Comment by daniel-winter** [comment]
@alexec Any news about that feature? Can't see any open PR where the feature is included?

**Comment by tiwarisanjay** [comment]
@alexec When we can expect this new feature?

**Pull request merged**
