### PR TITLE
[Snyk] Upgrade monaco-editor from 0.20.0 to 0.40.0

### PR DESCRIPTION
**Pull request by sarabala1979**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade monaco-editor from 0.20.0 to 0.40.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **493 versions** ahead of your current version.
- The recommended version was released **21 days ago**, on 2023-07-07.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/sarabala1979/project/05009f53-cf59-41dc-9a3c-4db00251e16a?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/sarabala1979/project/05009f53-cf59-41dc-9a3c-4db00251e16a/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/sarabala1979/project/05009f53-cf59-41dc-9a3c-4db00251e16a/settings/integration?pkg&#x3D;monaco-editor&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by agilgur5** [comment]
Taking a look as requested in [the contributor meeting today](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.qogh82i9yij0).

The [build error](https://github.com/argoproj/argo-workflows/actions/runs/5812236210/job/15757175464?pr=11475) here is actually different than I expected, looks like it might just require the [`monaco-editor-webpack-plugin`](https://github.com/argoproj/argo-workflows/blob/e46202a4c00f5c685a02eca9392ddfc1305ac9a0/ui/src/app/webpack.config.js#L3) to also be upgraded.
Well and we'll have to see if that causes any knock-on effects or if other build errors will show up after that (e.g. I suspected that `react-monaco-editor` could be impacted, which could have some React 17 follow-ons)

**Comment by agilgur5** [comment]
Was able to partially upgrade in #11593, but per the PR, there are some build system upgrades necessary to get all the way up to 0.40.0 (also 0.41.0 is latest now).

Upgraded to 0.30 for now, which did indeed require updating the Webpack plugin. See #11593 for more details

**Comment by agilgur5** [comment]
@terrytangyuan I was going to leave this open until we got `monaco-editor` to 0.40.0+

**Comment by sarabala1979** [comment]
@agilgur5 I will close it. Synk will open once it has a new version.

**Comment by agilgur5** [comment]
It will, but we're not even on 0.40.0 yet. This will also require manual intervention and testing either way as there are several related dependencies and [configurations](https://github.com/argoproj/argo-workflows/blob/8e26eb42b235aaa6b9f41f759574f9df7295313a/ui/src/app/webpack.config.js#L85) that often (but not always) require changing simultaneously.

**Comment by agilgur5** [comment]
Snyk opened #11699, which indeed failed to build for reasons I mentioned above. See my comment https://github.com/argoproj/argo-workflows/pull/11699#issuecomment-1696730970

I have updated the `monaco-editor` deps simultaneously myself in #11710 and tested it to ensure it is working.

**Pull request closed without merging**
