### PR TITLE
fix: disable concurrency when downloading azure files

### PR DESCRIPTION
**Pull request by roelarents**
workaround for https://github.com/Azure/azure-sdk-for-go/issues/22156

### Motivation

Recently [bumped](https://github.com/argoproj/argo-workflows/pull/12459) the azure sdk for go for blob storage. But it has an [issue](https://github.com/Azure/azure-sdk-for-go/issues/22156) with concurrent downloads.

### Modifications

Set concurrency when downloading artifacts/files/blobs from azure blob storage to 1 (instead of 5)

### Verification

Tested in production with a patch on 3.5.4. We [suffered](https://github.com/Azure/azure-sdk-for-go/issues/22156#issuecomment-1883653523) from this issue before (hanging workflow steps) and now not anymore.

### CODE REVIEW

**Comment by agilgur5** [comment]
This sounds like it's going to be [fixed soon upstream](https://github.com/Azure/azure-sdk-for-go/issues/22156#issuecomment-1893121130)? So maybe we should just wait for the fix and update the dep rather than adding and removing a workaround. I would think the Azure SDK would have a release before Argo as well

**Comment by roelarents** [comment]
True, if they fix it before the next argo release then this is obsolete. If not, I do suggest this temporary workaround. Because there is [another issue](https://github.com/Azure/azure-sdk-for-go/issues/20735) (that we also encountered in production) in the azure blob sdk since 1.0 (which is in argo 3.5). That has been fixed upstream already. I [bumped](https://github.com/argoproj/argo-workflows/pull/12459) the sdk to 1.2.1 for it. But that introduced this issue. (Probably/possibly there is a version in between with the fix for the one and not yet introducing the next. But I think using the latest version is easier.)

**Comment by tanyasethi-msft** [comment]
This fix constraints the concurrency to 1, which means parallel downloads not supported. 
We will be fixing the issue in our next release, Please use [azblob v1.1.0](https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fstorage%2Fazblob%2Fv1.1.0) for temporary mitigation.

**Comment by roelarents** [comment]
yep, they fixed it. this can be closed.

**Comment by agilgur5** [comment]
Looks like it was fixed in https://github.com/Azure/azure-sdk-for-go/pull/22334 which [was released in](https://github.com/Azure/azure-sdk-for-go/issues/22156#issuecomment-1941895878) `azblob` v1.3.0

**Pull request closed without merging**
