### PR TITLE
Update argo_delete.md

### PR DESCRIPTION
**Pull request by Amirioelmos**
Fixes #TODO

### CODE REVIEW

**Review by juliev0 — CHANGES_REQUESTED** [review]
Good catch. I think this file got autogenerated based on the comment in cmd/argo/commands/delete.go, so can you fix it there and then I believe you can run "make codegen -B" to autogenerate this from that? 

In fact, if I search the codebase, I see the same problem in cmd/argo/commands/list.go and cmd/argo/commands/terminate.go. Would you mind changing it in all of those?

**Comment by Amirioelmos** [comment]
> Good catch. I think this file got autogenerated based on the comment in cmd/argo/commands/delete.go, so can you fix it there and then I believe you can run "make codegen -B" to autogenerate this from that?
> 
> In fact, if I search the codebase, I see the same problem in cmd/argo/commands/list.go and cmd/argo/commands/terminate.go. Would you mind changing it in all of those?

yes, but  "make codegen -B" dosnt work with me, i try on it and change them.

**Comment by juliev0** [comment]
> > Good catch. I think this file got autogenerated based on the comment in cmd/argo/commands/delete.go, so can you fix it there and then I believe you can run "make codegen -B" to autogenerate this from that?
> > In fact, if I search the codebase, I see the same problem in cmd/argo/commands/list.go and cmd/argo/commands/terminate.go. Would you mind changing it in all of those?
> 
> yes, but "make codegen -B" dosnt work with me, i try on it and change them.

Would you like me to make all of the changes in a separate PR and then you can close this one?

**Comment by Amirioelmos** [comment]
> > > Good catch. I think this file got autogenerated based on the comment in cmd/argo/commands/delete.go, so can you fix it there and then I believe you can run "make codegen -B" to autogenerate this from that?
> > > In fact, if I search the codebase, I see the same problem in cmd/argo/commands/list.go and cmd/argo/commands/terminate.go. Would you mind changing it in all of those?
> > 
> > 
> > yes, but "make codegen -B" dosnt work with me, i try on it and change them.
> 
> Would you like me to make all of the changes in a separate PR and then you can close this one?

Yes.

**Comment by juliev0** [comment]
> > > > Good catch. I think this file got autogenerated based on the comment in cmd/argo/commands/delete.go, so can you fix it there and then I believe you can run "make codegen -B" to autogenerate this from that?
> > > > In fact, if I search the codebase, I see the same problem in cmd/argo/commands/list.go and cmd/argo/commands/terminate.go. Would you mind changing it in all of those?
> > > 
> > > 
> > > yes, but "make codegen -B" dosnt work with me, i try on it and change them.
> > 
> > 
> > Would you like me to make all of the changes in a separate PR and then you can close this one?
> 
> Yes.

okay, added this: https://github.com/argoproj/argo-workflows/pull/9334

Now you can close your PRs. Thanks!

**Comment by Amirioelmos** [comment]
> > > > > Good catch. I think this file got autogenerated based on the comment in cmd/argo/commands/delete.go, so can you fix it there and then I believe you can run "make codegen -B" to autogenerate this from that?
> > > > > In fact, if I search the codebase, I see the same problem in cmd/argo/commands/list.go and cmd/argo/commands/terminate.go. Would you mind changing it in all of those?
> > > > 
> > > > 
> > > > yes, but "make codegen -B" dosnt work with me, i try on it and change them.
> > > 
> > > 
> > > Would you like me to make all of the changes in a separate PR and then you can close this one?
> > 
> > 
> > Yes.
> 
> okay, added this: #9334
> 
> Now you can close your PRs. Thanks!

Thanks so much, I close this

**Pull request closed without merging**
