### PR TITLE
fix: upgrade `argo-ui` components to latest

### LINKED ISSUE #11448: UI: Intermediate parameters window is not scrollable
# Summary

For intermediate parameter suspending nodes with many parameters, the window for inputting values does not scroll. The only way to see the input box is to zoom out in your browser, otherwise the input fields are accessible by tabbing through, but not visible. The "ok"/"cancel" buttons are also inaccessible without zooming out.

e.g. for a node with 15 inputs, I can only see 10 here:

image

# Use Cases

Any intermediate parameters with 10+ inputs would be easier to use

<details><summary>Example yaml to test</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: intermediate-params-test-
spec:
  entrypoint: suspender
  templates:
  - name: suspender
    suspend: {}
    inputs:
      parameters:
      - default: ''
        name: param-1
      - default: ''
        name: param-2
      - default: ''
        name: param-3
      - default: ''
        name: param-4
      - default: ''
        name: param-5
      - default: ''
        name: param-6
      - default: ''
        name: param-7
      - default: ''
        name: param-8
      - default: ''
        name: param-9
      - default: ''
        name: param-10
      - default: ''
        name: param-11
      - default: ''
        name: param-12
      - default: ''
        name: param-13
      - default: ''
        name: param-14
      - default: ''
        name: param-15
    outputs:
      parameters:
      - name: param-1
        valueFrom:
          supplied: {}
      - name: param-2
        valueFrom:
          supplied: {}
      - name: param-3
        valueFrom:
          supplied: {}
      - name: param-4
        valueFrom:
          supplied: {}
      - name: param-5
        valueFrom:
          supplied: {}
      - name: param-6
        valueFrom:
          supplied: {}
      - name: param-7
        valueFrom:
          supplied: {}
      - name: param-8
        valueFrom:
          supplied: {}
      - name: param-9
        valueFrom:
          supplied: {}
      - name: param-10
        valueFrom:
          supplied: {}
      - name: param-11
        valueFrom:
          supplied: {}
      - name: param-12
        valueFrom:
          supplied: {}
      - name: param-13
        valueFrom:
          supplied: {}
      - name: param-14
        valueFrom:
          supplied: {}
      - name: param-15
        valueFrom:
          supplied: {}
```

</details>

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by agilgur5**
Replaces #11510, fixes all issues I commented about
Fixes #11448 by incorporating https://github.com/argoproj/argo-ui/pull/418

### Motivation

- Upgrade to latest version of `argo-ui` components
  - Upgrade and force resolve other deps to make sure build passes with latest version
- Fix intermediate parameters issue with the overflow fix
- Fix deprecation warnings in build

### Modifications

- Pin `argo-ui` to latest SHA: https://github.com/argoproj/argo-ui/commit/87d27fb1cb4f6e3ac4a49f85747e471b2efa7512
  - Add `@types/uuid` to fix lack of typing (see https://github.com/argoproj/argo-ui/pull/367 and https://github.com/argoproj/argo-cd/pull/13836)
  - Force resolve `react-toastify` to 9.0.3
    - This was pinned to 9.0.8 in https://github.com/argoproj/argo-ui/pull/379 but due to https://github.com/fkhadra/react-toastify/issues/775, that version is incompatible with Webpack/CRA v4 and was causing errors. Followed [this comment](https://github.com/fkhadra/react-toastify/issues/775#issuecomment-1150715526) to pin to 9.0.3, which fixed the errors
      - Argo CD [uses](https://github.com/argoproj/argo-cd/blob/bfaac2b5ac4b96c8af8158902c1b086f7ced7389/ui/package.json#L119) Webpack v5, so I assume that is why they didn't see the same issue
    - Enable `esModuleInterop` as this was added [in Argo UI](https://github.com/argoproj/argo-ui/pull/367/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R9), and since Argo UI is not compiled (we import source TS), we have to match its `tsconfig.json` to get the same results
       - This fixes a few import errors (as the errors say)
       - Use default imports for `classnames` and `moment` instead of namespace imports to fix the remaining import errors (as the errors suggest)

- Update `foundation-sites` to fix SCSS deprecation warnings
  - see https://github.com/foundation/foundation-sites/releases/tag/v6.7.0 which had various upgrades and compat fixes 

### Verification

Build passes, install succeeds

### CODE REVIEW

**Review by isubasinghe — APPROVED** [review]
Approving it early because CI/UI passes (only really needed to check this). LGTM! Thanks for your work

**Comment by agilgur5** [comment]
> ### Verification
> Build passes, install succeeds

Just noting here that I did not do a full test of rendering the actual UI as this my first time touching this build process so I still need to figure out how to do that. From a spot test, the UI does render, just with some source map warnings for `autolinker` (a dep that was not changed and is pinned).

There was one piece of the `argo-ui` upgrade that was particularly noteworthy, a breaking upgrade of `antd`: https://github.com/argoproj/argo-ui/pull/387#issuecomment-1679493537

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by agilgur5** [comment]
`react-toastify` forced resolution is removed with build upgrades in #11628

**Comment by JPZ13** [comment]
@terrytangyuan @sarabala1979 - did this PR ever get merged in to a v3.4.x commit? I'm looking through v3.4.16 and don't see it

**Comment by agilgur5** [comment]
It's not in the 3.4.x changelog and [didn't make it into](https://github.com/argoproj/argo-workflows/issues/11648#issuecomment-1707050496) 3.4.11 which is the only release issue back linked above.

I imagine this one might have had cherry-pick issues due to the `yarn.lock` changes, but idk

**Comment by terrytangyuan** [comment]
If it's not in changelog then there must have been a conflict. See https://github.com/argoproj/argo-workflows/issues/11648#issuecomment-1707441279 and the comment above and this commit is mentioned as not successfully cherry-picked.

**Pull request merged**
