### PR TITLE
feat: Expose customized UI links and columns

### LINKED ISSUE #10447: Customizable Argo UI (navigation links, custom columns)
# Summary

Many users use Argo Workflows for their CI or other application purposes (AI/ML). However, the UI does not lend itself to any specific application use case. It is a generic UI that allows you to do very generic things: filter on labels, namespace, etc... However, end users who might be visiting the Argo Workflows UI may not know where to start or how to use the UI to get to the filtered or curated view they are looking for.

This enhancement proposal is to allow **_workflow administrators_** to customize the UI in a couple of ways:
* providing tabs/links at the top of the interface which makes it obvious for their own users to navigate to curated/filtered views
* allowing the workflow administrator to customize the **_columns_** shown on the list view so that users can discern different workflow categories, e.g. by labels

# Use Cases

When would you use this?

For someone using workflows as CI, they could create various navigation links with predefined filters for their users, e.g.
* `Guestbook Builds`
* `Sockshop Builds`

These links would be predefined with filters based on labels that they choose in their environment. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #10447

The following in `workflow-controller-configmap.yaml`:

```yaml
data: 
  links:
    - name: Completed Workflows
      scope: workflow-list
      url: http://workflows?label=workflows.argoproj.io/completed=true
  columns: |
    - name: Workflow Completed
      type: label
      key: workflows.argoproj.io/completed
```

yields:

Screenshot 2023-04-03 at 10 08 20

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM. The changes are pretty straightforward. Would you like to add some documentation around it? For example, how to enable this in configmap.

**Comment by rbreeze** [comment]
Sure thing! Will add docs in a separate PR

**Comment by tooptoop4** [comment]
this looks great, when will it be released?

**Comment by terrytangyuan** [comment]
It will be part of v3.5

**Pull request merged**
