### PR TITLE
chore: update label categories / names

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- <details> <summary> we already have <code>area/*</code> labels for scopes, but other labels were not categorized, which makes labeling more difficult</summary>

  - also previously had `epic: ` and other categorized labels that seem to have all been deleted at some point
  - when categorized, you can type each category and then choose the appropriate labels
    - without categories, you have to know the labels off the top of your head or scroll through all labels
  - also keeps things consistent where possible 

</details>
  
Been wanting to do this for a while, now that I can change labels as an Approver, I figure it's a good time to standardize everything. Was already [standardizing colors](https://docs.google.com/document/d/1tznN5LB-KrNkC6dmeIzpKfuyvZWgCJpRuS-E84zseC8/edit#heading=h.itsuyfjwcmc3), descriptions, and adding more labels, now standardizing names/categories which requires some automation changes. These are very similar to the categories I use in other repos [I maintain](https://github.com/ezolenko/rollup-plugin-typescript2/labels)/[have maintained](https://github.com/jaredpalmer/tsdx/labels)

### Modifications

- use `type/*` for the type of issue, i.e. `type/bug`, `type/feature`, `type/support`, etc
  - chose `type` instead of `kind` to disambiguate from k8s kinds
- use `problem/*` if there are any problems, i.e. `problem/stale`, `problem/more information needed`, etc

- not used in the docs or automation at this time, but also have `solution/*` for how an issue was closed, i.e. `solution/duplicate`, `solution/invalid`, etc
  - that's it for now; might later consider `phase/*` for triage phases, e.g. `phase/triage`, `phase/proposal`, `phase/awaiting implementation` etc
  
- <details><summary> label renames everywhere they're used </summary>

  - Rename `enhancement` to the more commonly used term `feature`, which also matches `feat:` in conventional commits
  - Update other issue templates with label renames as well
  - Update `dependabot.yml` [with label renames](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates#setting-custom-labels)
  - Update Stale Action config with label renames
  - Update contributing docs with label renames

</details>

### Verification

Confirmed that the new links in the triaging docs work/will work with the renamed issue labels

### CODE REVIEW

**Comment by juliev0** [comment]
I am good with this. @terrytangyuan are you good with it?

**Review by terrytangyuan — COMMENTED** [review]
Is it just me who feel like there's additional overhead just to triage the issues?

**Comment by juliev0** [comment]
> Is it just me who feel like there's additional overhead just to triage the issues?

Related to this PR or unrelated? This PR groups the labels into categories, which should theoretically reduce overheard, except that it’s a change from what we’re used to (so I suppose there’s some overheard in the change).

**Comment by juliev0** [comment]
I like categorization.

Any issues with commonality with other repos or no? (you did mention your other repos have the change, so I guess there would be commonality there)

Just thinking about how users find bugs and features, and want to lay out how it affects them. Not that this is a reason not to do but want to discuss. Do the queries "is:bug" and "is:feature" still work? I guess if they're used to scrolling through the labels to find just bugs, they won't find "bug" itself, but presumably they can use the search box to find it.

**Comment by juliev0** [comment]
cc @Joibel

**Comment by agilgur5** [comment]
> This PR groups the labels into categories, which should theoretically reduce overheard

Indeed, that's what I wrote in the very first sentence of the PR.
It does indeed reduce overhead based on my own personal experience labeling thousands of issues + PRs on GitHub, especially when you come back to a repo after an absence and don't remember labels entirely, but remember the categories or recognize the categories as soon as you hit the "labels" button.

> Any issues with commonality with other repos or no? (you did mention your other repos have the change, so I guess there would be commonality there)

Not sure what you mean by this? What problems are you thinking of?
Categories are pretty standard, though the names of categories can vary per repo preference. And yes, as I wrote in the description, other repos I maintain have similar categories, Workflows itself has categories already (`area/*` right now, `epic: *` and others in the past), CD [has categories](https://github.com/argoproj/argo-cd/labels), and plenty of other repos in the [k8s](https://github.com/kubernetes/kubernetes/labels)/CNCF and other ecosystems have categories as well. It's very common practice.

> Do the queries "is:bug" and "is:feature" still work?

`label:bug` and `label:enhancement` would be the current filters. This would change those filters to `label:type/bug` and `label:type/feature`.

> but presumably they can use the search box to find it.

Yea I mean that's why I do myself.

**Comment by juliev0** [comment]
> > This PR groups the labels into categories, which should theoretically reduce overheard

> 
> > Any issues with commonality with other repos or no? (you did mention your other repos have the change, so I guess there would be commonality there)
> 
> Not sure what you mean by this? What problems are you thinking of? Categories are pretty standard, though the names of categories can vary per repo preference. And yes, as I wrote in the description, other repos I maintain have similar categories, Workflows itself has categories already (`area/*` right now, `epic: *` and others in the past), CD [has categories](https://github.com/argoproj/argo-cd/labels), and plenty of other repos in the [k8s](https://github.com/kubernetes/kubernetes/labels)/CNCF and other ecosystems have categories as well. It's very common practice.

That sounds good then.

> 
> > Do the queries "is:bug" and "is:feature" still work?
> 
> `label:bug` and `label:enhancement` would be the current filters. This would change those filters to `label:type/bug` and `label:type/feature`.
> 
Ahh, yeah, for some reason I thought “is:bug” was also somehow valid because it was apparently in my query history but it looks like that doesn’t work after all.

I guess anyone with a saved link will need to update it, but that’s probably just the few people that are actively triaging I imagine.

**Review by juliev0 — APPROVED** [review]

**Comment by agilgur5** [comment]
> I guess anyone with a saved link will need to update it, but that’s probably just the few people that are actively triaging I imagine.

I've never actually saved the links myself (I click labels and auto-fill every time), but they might be in contributing docs etc, which is half of what this PR updates

**Comment by agilgur5** [comment]
Merging as this has been approved (by someone who previously did bug triage too), has been under `prioritized-review` for over a week, and makes issue/PR triage easier and more consistent.

**Pull request merged**
