### PR TITLE
fix: Health check from lister not apiserver

### PR DESCRIPTION
**Pull request by cwdsuzhou**
Fixes [#11374](https://github.com/argoproj/argo-workflows/issues/11374)

### Motivation

Reduce the `List` check from controller. IMO, it is not reasonable to list from apiserver for health check. Informer is not so reliable and if informer is not healthy, the controller may exit or resync from apiserver.

### Modifications

Change the health check logic from apiserver to the local cache

### CODE REVIEW

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
See discussions in https://github.com/argoproj/argo-workflows/issues/11374

**Comment by terrytangyuan** [comment]
Bump

**Comment by cwdsuzhou** [comment]
Since we have disscussed https://github.com/argoproj/argo-workflows/issues/11374, can we work on this PR now?

@terrytangyuan

**Review by terrytangyuan — APPROVED** [review]
I am ok with this change. Let's watch for any issues once merged/released

**Comment by astraw99** [comment]
> I am ok with this change. Let's watch for any issues once merged/released

Raised a PR https://github.com/argoproj/argo-workflows/pull/11770 to fix an issue https://github.com/argoproj/argo-workflows/issues/11769 introduced from this.
PTAL thanks.

**Comment by juliev0** [comment]
@cwdsuzhou When you tested this, were you able to successfully execute line 37 while catching a Workflow that hadn't been reconciled yet? We noticed a panic occurring on [this](https://github.com/argoproj/argo-workflows/blob/main/pkg/client/listers/workflow/v1alpha1/workflow.go#L68) line, when the `*Unstructured` type in the Informer gets type asserted to a `*Workflow` type instead. It seems like the Informer holds `*Unstructured` types, so I'm not sure if this type conversion ever works. If you have any thoughts, let me know. Thanks!

**Comment by agilgur5** [comment]
> We noticed a panic occurring on [this](https://github.com/argoproj/argo-workflows/blob/main/pkg/client/listers/workflow/v1alpha1/workflow.go#L68) line, when the `*Unstructured` type in the Informer gets type asserted to a `*Workflow` type instead. It seems like the Informer holds `*Unstructured` types, so I'm not sure if this type conversion ever works.

For posterity, this was followed up in #12326 and #12353

**Pull request merged**
