### PR TITLE
Revert "chore(deps): bump react-router-dom and @types/react-router-dom in /ui"

### PR DESCRIPTION
**Pull request by isubasinghe**
Reverts argoproj/argo-workflows#10547

### CODE REVIEW

**Comment by isubasinghe** [comment]
This is quite urgent, master is broken due to the react-router-dom upgrade. 
Could we setup dependabot to only upgrade minor versions?

**Comment by alexec** [comment]
> This is quite urgent, master is broken due to the react-router-dom upgrade.

Could you say how please?

> Could we setup dependabot to only upgrade minor versions?

Good idea. Would you like to submit a PR?

https://github.com/orgs/community/discussions/21626

**Review by alexec — APPROVED** [review]

**Comment by isubasinghe** [comment]
> Could you say how please?

argo-ui assumes the react-router-dom version is 4. In nav.bar.tsx the AppContext contains an undefined router as a result. 
This in turn leads to a broken AppRouter in the workflows ui and only displays a blank page. 

> Good idea. Would you like to submit a PR?
Sure I will do after the current bug fix I am working on atm.

**Comment by agilgur5** [comment]
> > Could we setup dependabot to only upgrade minor versions?
> 
> Good idea. Would you like to submit a PR?
> 
> https://github.com/orgs/community/discussions/21626

I added an answer in that discussion about how to ignore all major versions: https://github.com/orgs/community/discussions/21626#discussioncomment-6771318

**Pull request merged**
