### PR TITLE
fix: wrong node name was used when concat pod name

### PR DESCRIPTION
**Pull request by juchaosong**
Please do not open a pull request until you have checked ALL of these:

* [ ] Create the PR as draft .
* [ ] Run `make pre-commit -B` to fix codegen and lint problems.
* [ ] Sign-off your commits (otherwise the DCO check will fail).
* [ ] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [ ] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [ ] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [ ] Github checks are green.
* [ ] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Comment by juchaosong** [comment]
> Can you paste the output before and after the change?

```
argo get copy-record-to-oss-bbs6j
Name:                copy-record-to-oss-bbs6j
Namespace:           default
ServiceAccount:      unset
Status:              Running
Conditions:          
 PodRunning          False
Created:             Sat Nov 05 13:58:36 +0800 (20 seconds ago)
Started:             Sat Nov 05 13:58:36 +0800 (20 seconds ago)
Duration:            20 seconds
Progress:            3/4
ResourcesDuration:   10s*(1 cpu),10s*(100Mi memory)
Parameters:          
  remote_file_url:   

STEP                           TEMPLATE                   PODNAME                                                        DURATION  MESSAGE
 ● copy-record-to-oss-bbs6j    main                                                                                                                       
 ├───✔ generate-filter         generate-filter-step       copy-record-to-oss-bbs6j-generate-filter-step-3445618464       5s                               
 ├───✔ list-project-records    list-project-records-step  copy-record-to-oss-bbs6j-list-project-records-step-4119320579  5s                               
 ├───○ download-record         download-record-step                                                                                Skipped, empty params  
 └───◷ output-record-revision  output-record-revision     copy-record-to-oss-bbs6j-output-record-revision-612305082      0s                               
$ k get pod copy-record-to-oss-bbs6j-generate-filter-step-3445618464
Error from server (NotFound): pods "copy-record-to-oss-bbs6j-generate-filter-step-3445618464" not found
```
We cannot find the pod because `argo` use the wrong node name to generate pod name.


```
$ go run ./cmd/argo get copy-record-to-oss-bbs6j
Name:                copy-record-to-oss-bbs6j
Namespace:           default
ServiceAccount:      unset
Status:              Succeeded
Conditions:          
 PodRunning          False
 Completed           True
Created:             Sat Nov 05 13:58:36 +0800 (2 minutes ago)
Started:             Sat Nov 05 13:58:36 +0800 (2 minutes ago)
Finished:            Sat Nov 05 13:59:26 +0800 (1 minute ago)
Duration:            50 seconds
Progress:            6/6
ResourcesDuration:   21s*(1 cpu),21s*(100Mi memory)
Parameters:          
  remote_file_url:   

STEP                                TEMPLATE                   PODNAME                                                       DURATION  MESSAGE
 ✔ copy-record-to-oss-bbs6j         main                                                                                                                      
 ├───✔ generate-filter              generate-filter-step       copy-record-to-oss-bbs6j-generate-filter-step-2776805078      5s                               
 ├───✔ list-project-records         list-project-records-step  copy-record-to-oss-bbs6j-list-project-records-step-780734510  5s                               
 ├───○ download-record              download-record-step                                                                               Skipped, empty params  
 ├───✔ output-record-revision       output-record-revision     copy-record-to-oss-bbs6j-output-record-revision-4292434670    6s                               
 └───✔ output-oss-path              output-oss-path            copy-record-to-oss-bbs6j-output-oss-path-345425175            5s                               
                                                                                                                                                                       
 ✔ copy-record-to-oss-bbs6j.onExit  workflow-callback          copy-record-to-oss-bbs6j-workflow-callback-3197651933         5s                               
$ k get pod copy-record-to-oss-bbs6j-generate-filter-step-2776805078
NAME                                                       READY   STATUS      RESTARTS   AGE
copy-record-to-oss-bbs6j-generate-filter-step-2776805078   0/2     Completed   0          2m32s
```
We find the pod using the pr code.
You can reproduce this bug locally.

**Comment by terrytangyuan** [comment]
Thanks. Can you fix the test?

**Comment by juchaosong** [comment]
I will fix it, but it will take some time.

**Comment by spencercjh** [comment]
image

**Comment by terrytangyuan** [comment]
Looks like has been fixed already. Could you check? Thank you for your contribution!

**Comment by spencercjh** [comment]
It seems that the fix patch doesn't release.

**Comment by terrytangyuan** [comment]
Yeah it will need to wait for next release.

**Pull request closed without merging**
