### PR TITLE
Revert "chore(deps): bump react-router-dom and @types/react-router-do…

### PR DESCRIPTION
**Pull request by alexec**
…m in /ui (#10587)"

This reverts commit 2622afa7e554071004c7dd08d0890ed5a6f558b8.

Fixes broken master.

### CODE REVIEW

**Comment by danielandersson** [comment]
For the same reason as with https://github.com/argoproj/argo-workflows/pull/10575, `master` (and the `latest` image) is currently broken.

Anything that is holding back from merging this?

**Review by sarabala1979 — APPROVED** [review]

**Comment by juliev0** [comment]
@alexec What prevents dependabot from doing this again? @JPZ13 I believe was going to add something to our [dependabot.yml](https://github.com/argoproj/argo-workflows/blame/master/.github/dependabot.yml) file to prevent it. cc @sarabala1979 @caelan-io

**Comment by JPZ13** [comment]
I'll put out the pull request later this evening

**Comment by juliev0** [comment]
> I'll put out the pull request later this evening

Thanks, JP!

**Comment by JPZ13** [comment]
Any time! PR is out at #10648

**Pull request merged**
