### PR TITLE
chore: Remove onExit naming transition scaffolding code

### PR DESCRIPTION
**Pull request by simster7**
Closes https://github.com/argoproj/argo-workflows/issues/5502

The fix in https://github.com/argoproj/argo-workflows/pull/5486 was added with some scaffold code in order to not impact running workflows when upgrading to v3.0. We're now in v3.1, so this code is no longer necessary.

Signed-off-by: Simon Behar <simbeh7@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).

Tips:

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by simster7** [comment]
@sarabala1979 @alexec Can I get a rubber stamp here?

**Review by alexec — COMMENTED** [review]
Would there be a problem upgrading from v2.12 say?

**Comment by simster7** [comment]
I expect this to be released on `v3.2` so it would only be a problem when upgrading from `v2.12` to `v3.2`. Any other upgrade would be fine.

**Review by sarabala1979 — APPROVED** [review]

**Comment by sarabala1979** [comment]
@simster7 Can you add a  steps to fix when they are doing upgrade?

**Comment by simster7** [comment]
> @simster7 Can you add steps to fix when they are doing the upgrade?

Will do

**Pull request merged**
