### PR TITLE
fix: Fixed workflow template skip whitespaced parameters. Fixes #11767

### LINKED ISSUE #11767: Workflow templating is skipped when whitespace is added to template parameters
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

Workflow templating is skipped when whitespace is added to template parameters. When referring to `{{workflow.thisdoesnotexist}}` in a workflow template, an error prevents submitting the workflow. But when referring to `{{ workflow.thisdoesnotexist }}`, there is no error, and the workflow proceeds without that template being substituted.

### Version

v3.4.9

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: helloworld
spec:
  serviceAccountName: argo
  entrypoint: helloworld
  templates:
  - name: helloworld
    container:
      image: "alpine:3.18"
      command: ["echo", "{{ workflow.thisdoesnotexist }}"]
```

### Logs from the workflow controller

```text
time="2023-09-06T19:44:17.289Z" level=info msg="Processing workflow" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:17.301Z" level=info msg="Updated phase  -> Running" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:17.301Z" level=info msg="Pod node helloworld-hhccl initialized Pending" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:17.336Z" level=info msg="Created pod: helloworld-hhccl (helloworld-hhccl)" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:17.336Z" level=info msg="TaskSet Reconciliation" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:17.336Z" level=info msg=reconcileAgentPod namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:17.344Z" level=info msg="Workflow update successful" namespace=argo-events phase=Running resourceVersion=96464776 workflow=helloworld-hhccl
time="2023-09-06T19:44:27.337Z" level=info msg="Processing workflow" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:27.337Z" level=info msg="Task-result reconciliation" namespace=argo-events numObjs=0 workflow=helloworld-hhccl
time="2023-09-06T19:44:27.337Z" level=info msg="node changed" namespace=argo-events new.message= new.phase=Succeeded new.progress=0/1 nodeID=helloworld-hhccl old.message= old.phase=Pending old.progress=0/1 workflow=helloworld-hhccl
time="2023-09-06T19:44:27.338Z" level=info msg="TaskSet Reconciliation" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:27.338Z" level=info msg=reconcileAgentPod namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:27.338Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:27.338Z" level=info msg="Marking workflow completed" namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:27.338Z" level=info msg="Checking daemoned children of " namespace=argo-events workflow=helloworld-hhccl
time="2023-09-06T19:44:27.343Z" level=info msg="cleaning up pod" action=deletePod key=argo-events/helloworld-hhccl-1340600742-agent/deletePod
time="2023-09-06T19:44:27.347Z" level=info msg="Workflow update successful" namespace=argo-events phase=Succeeded resourceVersion=96464883 workflow=helloworld-hhccl
time="2023-09-06T19:44:27.371Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo-events/helloworld-hhccl/labelPodCompleted
```

### Logs from in your workflow's wait container

```text
time="2023-09-06T19:44:18.953Z" level=info msg="Starting Workflow Executor" version=v3.4.9
time="2023-09-06T19:44:18.957Z" level=info msg="Using executor retry strategy" Duration=1s Factor=1.6 Jitter=0.5 Steps=5
time="2023-09-06T19:44:18.957Z" level=info msg="Executor initialized" deadline="0001-01-01 00:00:00 +0000 UTC" includeScriptOutput=false namespace=argo-events podName=helloworld-hhccl template="{\"name\":\"helloworld\",\"inputs\":{},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine:3.18\",\"command\":[\"echo\",\"{{ workflow.thisdoesnotexist }}\"],\"resources\":{}}}" version="&Version{Version:v3.4.9,BuildDate:2023-07-20T14:01:57Z,GitCommit:b76329f3a2dedf4c76a9cac5ed9603ada289c8d0,GitTag:v3.4.9,GitTreeState:clean,GoVersion:go1.20.4,Compiler:gc,Platform:linux/amd64,}"
time="2023-09-06T19:44:18.957Z" level=info msg="Starting deadline monitor"
time="2023-09-06T19:44:20.957Z" level=info msg="Main container completed" error="<nil>"
time="2023-09-06T19:44:20.957Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-09-06T19:44:20.957Z" level=info msg="No output parameters"
time="2023-09-06T19:44:20.957Z" level=info msg="No output artifacts"
time="2023-09-06T19:44:20.958Z" level=info msg="Alloc=7381 TotalAlloc=16013 Sys=33661 NumGC=5 Goroutines=7"
time="2023-09-06T19:44:20.958Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2023-09-06T19:44:20.958Z" level=info msg="Deadline monitor stopped"
```

### PR DESCRIPTION
**Pull request by shmruin**
Fixes #11767 

### Motivation

In workflow template, parameters with leading/trailing whitespace parameter is skipped to check validation.
Actually, I think any kind of whitespaced parameter is just passing the validation check which is in [resolveAllVariables](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L652) function so far.

In the function's return clause, currently there is no trimming for the `tag` (which is the parameter value in `{{ }}`)

And there is also [checkValidWorkflowVariablePrefix](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/workflow/validate/validate.go#L658C7-L658C39), which also checks the prefix.

The summary is like below.

```go
func resolveAllVariables(scope map[string]interface{}, globalParams map[string]string, tmplStr string, workflowTemplateValidation bool) error {
	// ...
	return template.Validate(tmplStr, func(tag string) error {
		// Skip the custom variable references
		if !checkValidWorkflowVariablePrefix(tag) {
			return nil
		}
		_, ok := scope[tag]
		_, isGlobal := globalParams[tag]
		if !ok && !isGlobal {
			if (tag == "item" || strings.HasPrefix(tag, "item.")) && allowAllItemRefs {
				// we are *probably* referencing a undetermined item using withParam
				// NOTE: this is far from foolproof.
			} else if strings.HasPrefix(tag, "workflow.outputs.parameters.") && allowAllWorkflowOutputParameterRefs {
				// Allow runtime resolution of workflow output parameter names
			} else if strings.HasPrefix(tag, "workflow.outputs.artifacts.") && allowAllWorkflowOutputArtifactRefs {
				// Allow runtime resolution of workflow output artifact names
			} else if strings.HasPrefix(tag, "outputs.") {
				// We are self referencing for metric emission, allow it.
			} else if strings.HasPrefix(tag, common.GlobalVarWorkflowCreationTimestamp) {
			} else if strings.HasPrefix(tag, common.GlobalVarWorkflowCronScheduleTime) {
				// Allow runtime resolution for "scheduledTime" which will pass from CronWorkflow
			} else if strings.HasPrefix(tag, common.GlobalVarWorkflowDuration) {
			} else if strings.HasPrefix(tag, "tasks.name") {
			} else if strings.HasPrefix(tag, "steps.name") {
			} else if strings.HasPrefix(tag, "node.name") {
			} else if strings.HasPrefix(tag, "workflow.parameters") && workflowTemplateValidation {
				// If we are simply validating a WorkflowTemplate in isolation, some of the parameters may come from the Workflow that uses it
			} else {
				return fmt.Errorf("failed to resolve {{%s}}", tag)
			}
		}
		return nil
	})
}

// checkValidWorkflowVariablePrefix is a helper methood check variable starts workflow root elements
func checkValidWorkflowVariablePrefix(tag string) bool {
	for _, rootTag := range common.GlobalVarValidWorkflowVariablePrefix {
		if strings.HasPrefix(tag, rootTag) {
			return true
		}
	}
	return false
}

// ...

// GlobalVarWorkflowRootTags is a list of root tags in workflow which could be used for variable reference
var GlobalVarValidWorkflowVariablePrefix = []string{"item.", "steps.", "inputs.", "outputs.", "pod.", "workflow.", "tasks."}
```

I also check the [template.Validate](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/util/template/validate.go#L9) function but don't think this is doing some trimming.

So, if there is some parameter like `{{ workflow.thisdoesnotexist }}` come in, `workflow.` in `GlobalVarValidWorkflowVariablePrefix` never matched as prefix for `<space>workflow.thisdoesnotexist<space>`, and `checkValidWorkflowVariablePrefix` function returns false and goes to return nil for `resolveAllVariables`.

`{{ workflow.thisdoesnotexist }}` is just dealt like an custom variable reference.

returning error 'failed to resolve' will not happens.

### Modifications

I just trim the tag in returning clause, and use that for validation in it.

This trimmed tag is only used here and never go outside.

I think in this way leading and trailing space parameters can be also verified correctly.

**BUT If there are some users who use already use their template with some prefix workflow, items, tasks, ... as a custom value then this change can be affected. Those parameters should pass validation check.**

### Verification

The workflow template below now makes an error.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: helloworld
spec:
  serviceAccountName: argo
  entrypoint: helloworld
  templates:
  - name: helloworld
    container:
      image: "alpine:3.18"
      command: ["echo", "{{ workflow.thisdoesnotexist }}"]
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: helloworld
spec:
  serviceAccountName: argo
  entrypoint: helloworld
  templates:
  - name: helloworld
    container:
      image: "alpine:3.18"
      command: ["echo", "{{workflow.thisdoesnotexist}}"]
```

```yaml
{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "WorkflowTemplate",
  "metadata": {
    "name": "helloworld"
  },
  "spec": {
    "serviceAccountName": "argo",
    "entrypoint": "helloworld",
    "arguments": {
      "parameters": [
        {
          "name": "thisexist",
          "value": "default-value"
        }
      ]
    },
    "templates": [
      {
        "name": "helloworld",
        "container": {
          "image": "alpine:3.18",
          "command": [
            "echo",
            "{{ workflow.parameters.thisexist }}"
          ]
        }
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by shmruin** [comment]
With this change e2e test of [TestInvalidNameParameterSubstitution](https://github.com/argoproj/argo-workflows/blob/9955958a8c7d835b04de9a602118a7b91c802341/test/e2e/workflow_configmap_substitution_test.go#L110) fails.
Originally, It just pass the validation check, and the error occur when running.
But this change prevent this TestInvalidNameParameterSubstitution's weird parameter not go through. Does the original e2e should works?

<< Current >>
image

<< Changed >>
image

**Review by terrytangyuan — COMMENTED** [review]
Triggered re-run to see if it's flaky

**Comment by shmruin** [comment]
@terrytangyuan , I retry that but still same error. I think the reason is not due to flasky test, but what I wrote above.

**Comment by terrytangyuan** [comment]
Fixed in https://github.com/argoproj/argo-workflows/pull/11806

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
