### PR TITLE
docs: Fix port definitions in examples

### PR DESCRIPTION
**Pull request by hjorth**
FIx port definition errors in examples.

### CODE REVIEW

**Review by simster7 — COMMENTED** [review]
These were recently changed to strings from ints: https://github.com/argoproj/argo-workflows/pull/4831/files#diff-fbd4cc7bade7a2809ed6ed26bb784529a98b8ef86453e9cec02394be45dce8c7R27

Which is the correct one? cc @kennytrytek

**Comment by hjorth** [comment]
> These were recently changed to strings from ints: https://github.com/argoproj/argo-workflows/pull/4831/files#diff-fbd4cc7bade7a2809ed6ed26bb784529a98b8ef86453e9cec02394be45dce8c7R27
> 
> Which is the correct one? cc @kennytrytek

I tested all the examples on 3.1.14, GKE 1.20 - they weren't working.

Just checked daemon-nginx on 3.2.4, it failes with:
```bash
step group deemed errored due to child daemon-nginx-6qcjp[0].nginx-server error: Pod "daemon-nginx-6qcjp-3819426501" is invalid: spec.containers[1].readinessProbe.httpGet.port: Invalid value: "80": must contain at least one letter or number (a-z, 0-9)
```

**Comment by kennytrytek** [comment]
https://github.com/argoproj/argo-workflows/issues/4817#issuecomment-778855785
>[PR is open](https://github.com/argoproj/argo-workflows/pull/4831) to revert back to only support `string`. `IntOrString` was previously defined strictly as a string [in this commit](https://github.com/argoproj/argo-workflows/blob/673553729e12d4ad83387eba68b3cbfb0aea8fe4/api/openapi-spec/swagger.json#L7094-L7099). It was changed in [this pull request](https://github.com/argoproj/argo-workflows/pull/4611) to generate the invalid "int or string" spec. While technically closer to the intent of the field name, supporting both types cannot be implemented until Swagger v3.1 is used, as discussed above.

This is my best understanding of where things sit, so I think string is correct. Feel free to correct me if I've missed something.

**Comment by alexec** [comment]
I think this PR is probably correct. I think this is just vanilla values.

**Review by alexec — CHANGES_REQUESTED** [review]
However, I think this PR does need to fix the DCO and Semantic Pull Request.

**Comment by hjorth** [comment]
> However, I think this PR does need to fix the DCO and Semantic Pull Request.

Will check that out.

**Comment by ZPerling** [comment]
nor my port is  defined by a input parameter

```yaml
spec:
  templates:
    - name: java-service-run
      inputs:
        parameters:
          - name: run-command
          - name: port
            value: "8080"
      daemon: true
      retryStrategy:
        limit: "1"
      container:
        workingDir: '/work/'
        image: jdk:8u333-centos7
        command:
        - '{{inputs.parameters.run-command}}'
        readinessProbe:
          tcpSocket:
            port: "{{inputs.parameters.port}}"
          initialDelaySeconds: 60
          periodSeconds: 6
          failureThreshold: 30
```
 same error occurred
image

I try remove `'{{inputs.parameters.run-command}}'` quotes like `{{inputs.parameters.run-command}}`, but can not subbmit , how can I fix this problem

**Comment by agilgur5** [comment]
This PR was superseded by #9207

**Comment by agilgur5** [comment]
> now my port is defined by a input parameter

This isn't related to this PR specifically, but is related to one mentioned above: #4831
For anyone that comes here, If you still have this issue, please open a new issue about that.
Also you might be able to workaround it with `podSpecPatch`

**Pull request closed without merging**
