### PR TITLE
fix(ui): ignore `@every` cron expression for FE pretty printing and update `cronstrue` dependency. Fixes #13489

### LINKED ISSUE #13489: UI: Allow `@schedules` in CronWorkflow field
# Summary

Currently the validator restricts the `schedule` and `schedules` fields of CronWorkflows to contain 5 parts and responds with 
```
Error: Expression has only 2 parts. At least 5 parts are required.
```
if you attempt to use [Predefined Schedules](https://pkg.go.dev/github.com/robfig/cron#hdr-Predefined_schedules).

https://pkg.go.dev/github.com/robfig/cron supports these Predefined Schedules, and will run them if you bypass the validator with `kubectl apply` or `kubectl create`.

This feature would teach the validator that this format is also fine for this field. This is really most useful for the [`@every`](https://pkg.go.dev/github.com/robfig/cron#hdr-Intervals) format, as the other schedules can be written using standard 5 part cron schedules.

See https://cloud-native.slack.com/archives/C01QW9QSSSK/p1724080720962949

**Message from the maintainers**:

Love this feature request? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by djanjic**
Fixes #13489 

### Motivation
This change should address confusion when submitting/ checking a cron workflow using UI. 

### Modifications
- Updated `pretty-schedule.tsx` to ignore cron expressions in `@every` format since library used for pretty printing is not supporting this format.  `schedule-validation.tsx` is not updated with this change but I'm still considering that since there's a BE validation. For `@every` format, there's no pretty printed description nor next schedule date. 
- `@daily`, `@hourly` and other formats supported by BE library (https://github.com/robfig/cron) are support in FE js library in the latest version (https://github.com/bradymholt/cRonstrue/pull/318). This PR contains dependency update to include this change.

### Verification
Check screenshots:
Screenshot 2024-09-11 at 13 52 54
Screenshot 2024-09-11 at 13 53 14

### CODE REVIEW

**Comment by agilgur5** [comment]
> Fixes #13489

Oh, we thought this was an API validation bug, but I guess not, it's only the UI that's affected?

**Comment by Joibel** [comment]
> Oh, we thought this was an API validation bug, but I guess not, it's only the UI that's affected?

Indeed, I did as well.

Had me a bit foxed looking at the validator and not seeing where it was going wrong.

**Comment by agilgur5** [comment]
> * are support in FE js library in the latest version ([Support for '@' expressions bradymholt/cRonstrue#318](https://github.com/bradymholt/cRonstrue/pull/318)).

> * Updated `pretty-schedule.tsx` to ignore cron expressions in `@every` format since library used for pretty printing is not supporting this format.

Have you considered contributing `@every` support upstream?

**Comment by agilgur5** [comment]
> Have you considered contributing `@every` support upstream?

Nevermind, apparently [`@every`](https://pkg.go.dev/github.com/robfig/cron#hdr-Intervals) is a non-standard extension from `robfig/cron` and uses the Go specific `time.Duration` format that [k8s API conventions recommend against](https://github.com/kubernetes/community/blob/fb55d44/contributors/devel/sig-architecture/api-conventions.md#units)

**Review by Joibel — APPROVED** [review]

**Pull request merged**
