### PR TITLE
chore(deps): bump github.com/vektra/mockery from v2.26.0 to v2.42.0

### PR DESCRIPTION
**Pull request by blkperl**
### Motivation

This is part of a series of PRs to update build dependencies until the build no longer panics on Golang 1.22

### Modifications

The new version of mockery generated some new files and no other changes were made. 

### Verification

No verification, the tests will fail if the mock changes do not work.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
Thanks!

**Comment by blkperl** [comment]
@isubasinghe Hey, I need help on the nix change for this PR as well. Thanks!

**Comment by blkperl** [comment]
@isubasinghe I'm unsure how to get the new SHA. I wasn't able to see it fail when I run nix develop in the github codespace.

**Comment by isubasinghe** [comment]
> @isubasinghe I'm unsure how to get the new SHA. I wasn't able to see it fail when I run nix develop in the github codespace.

error: hash mismatch in fixed-output derivation '/nix/store/akhi4m5mxiz1m5352ddc59q6w2kxjvw0-source.drv':
         specified: sha256-3wJ7XY/wfVXB4nEHLqEtNRscow/KrAo79sr2OgJisSY=
            got:    sha256-wwt7rhHWPlYtvudWKb8vk8t19MeN7AMfMugs0XeBDVk=
            
Weird that you aren't getting these error msgs, could be do to with a buggy version of nix then?

**Comment by isubasinghe** [comment]
https://github.com/argoproj/argo-workflows/pull/12719#issuecomment-1988234901

**Review by isubasinghe — APPROVED** [review]
LGTM

**Comment by blkperl** [comment]
@isubasinghe Thanks, I've updated the SHA. It should be good to go once CI passes.

**Review by agilgur5 — APPROVED** [review]
Re-ran CI since the failure was an unrelated test flake (see #12836 and [Slack thread](https://cloud-native.slack.com/archives/C0510EUH90V/p1710260573672209)), passed this time around.

Deps LGTM, and if Isitha said Nix was good, then all clear 🚀

**Pull request merged**
