### PR TITLE
fix: Page workflow event bindings basehref

### LINKED ISSUE #7416: workflow-event-bindings page support basehref
# Summary

image

If the `basehref` is set, the placeholder address of the `workflow-event-bindings` page should also be added synchronously

Similarly, the Swagger-API docs needs to be handled

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

### PR DESCRIPTION
**Pull request by chf007**
Fixes #7416 

- Page workflow event bindings curl example support basehref.
- Enhance the robustness of the code.
  - export shared/base baseUrl 
  - base.getAttribute('href') may return null (`<base target="_blank">`)
  -  userinfo/components/cli-help.tsx argoBaseHref may report undefined error

### CODE REVIEW

**Comment by sarabala1979** [comment]
have you tested? please. provide the screen shot and examples

**Comment by chf007** [comment]
> have you tested? please. provide the screen shot and examples

I started it in the local environment and tested it through basepath=/.

Since argo-server can set basepath=xxx when it is started locally, it does not actually take effect, so the case of basepath=xxx has not been measured.

The following is a description of my local environment:

minikube

`export BASE_HREF=/my-path/ && make start API=true UI=true`

image

image

**Comment by sarabala1979** [comment]
@simster7 Can you take a quick look for this PR?

**Comment by sarabala1979** [comment]
@chf007 Please  fix  the lint

**Comment by sarabala1979** [comment]
@chf007 Do you want to merge this  PR for v3.3?

**Review by sarabala1979 — CHANGES_REQUESTED** [review]
Changes  requested

**Comment by agilgur5** [comment]
This was replaced by #10759

**Pull request closed without merging**
