### PR TITLE
docs: Add OpenSSF Scorecard status badge to README.md

### PR DESCRIPTION
**Pull request by redenferno**
Created OpenSSF Scorecard badge for project README.

### Motivation

This was requested by @agilgur5 as part of #9769

### Verification

image

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
I am in for less badges unless really needed

**Comment by agilgur5** [comment]
@terrytangyuan generally I am agreed on that.

In this case, this is specifically for the [CNCF CLOMonitor](https://github.com/cncf/clomonitor), for which #9769 is a tracking issue. That issue was from last year's [CNCF Security Slam](https://community.cncf.io/cloud-native-security-slam/), which will start up again this year in around ~2 weeks (I'm planning on working on SLSA Level 3 and 4, as recently discussed in SIG Security yesterday). 

We are missing two badges for CLOMonitor, this is one of them. Although the OpenSSF Scorecard also requires running in CI, which we don't currently do as far as I know, so I think this badge is using an old result(?) or something.

As CLOMonitor is a metric CNCF highlights for supply chain security, I think it would be good to bring our score up and in line with CD.

**Review by agilgur5 — COMMENTED** [review]
@redenferno have you worked on setting up the scorecard action? Without that the badge is a bit premature

If you haven't, I was planning to pick it up simultaneously with SLSA in October

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Thanks

**Comment by eddie-knight** [comment]
> @redenferno have you worked on setting up the scorecard action? Without that the badge is a bit premature
> 
> If you haven't, I was planning to pick it up simultaneously with SLSA in October

FYI @agilgur5, the Scorecard score presented in the badge will be accurate to the last weekly cron job (Google sponsors a scan of over a million repos every week, including this one).

The GitHub Action can serve to increase the precision by updating the score whenever new code is merged, but it isn't a prerequisite for the badge.

**Comment by agilgur5** [comment]
> FYI @agilgur5, the Scorecard score presented in the badge will be accurate to the last weekly cron job (Google sponsors a scan of over a million repos every week, including this one).

Oh I didn't know that, thanks for the context!
Could you link to a source for this? like docs from OpenSSF or the repo for this cron job?

**Comment by eddie-knight** [comment]
I didn't find anything in the docs yet, but I know this because the maintainers made sure it was included in the [LF Course](https://trainingportal.linuxfoundation.org/learn/course/automating-supply-chain-security-sboms-and-signatures-lfel1007) on the topic. They probably should add it to the docs more clearly.

Here is confirmation from the BigQuery data that argo workflows is included in the cron:

Screen Shot 2023-10-04 at 1 27 57 PM

**Comment by agilgur5** [comment]
Ah I found it. There are docs on this in the ["Public Data"](https://github.com/ossf/scorecard/tree/63fff3c84090a64a81dca399eea2b8d6817b343e#public-data) section of the scorecard README. It links to [a CSV](https://github.com/ossf/scorecard/blob/63fff3c84090a64a81dca399eea2b8d6817b343e/cron/internal/data/projects.csv) in the repo of all projects tracked as well (though it's ~70mb so it can be difficult to load 😅 ). I believe the `cron` directory that the CSV is in is the code for the cron job as well.

**Pull request merged**
