### PR TITLE
fix: TestWorkflowStepRetry's comment accurately reflects what it does.

### PR DESCRIPTION
**Pull request by robertkotcher**
Update TestWorkflowStepRetry's comment to accurately reflect what it does.

Signed-off-by: rkotcher <robert@synthesis.ai>

### CODE REVIEW

**Comment by robertkotcher** [comment]
Looks like the Docs failure is unrelated to changes made in this PR 🤔

**Review by juliev0 — APPROVED** [review]

**Comment by robertkotcher** [comment]
@juliev0 it looks like you have approved, but github doesn't seem to recognize that since it still says:

```
Merging can be performed automatically with 1 approving review
```

Have you seen this before? Also assuming you have write access? (looks like that is also a requirement)

Thank you!

**Comment by juliev0** [comment]
> @juliev0 it looks like you have approved, but github doesn't seem to recognize that since it still says:
> 
> ```
> Merging can be performed automatically with 1 approving review
> ```
> 
> Have you seen this before? Also assuming you have write access? (looks like that is also a requirement)
> 
> Thank you!

You guessed it. I don't have permission. That "1 approving review" message is confusing. I'm a member of argo-workflows but not yet an "approver".

**Comment by robertkotcher** [comment]
@sarabala1979 you assigned to @juliev0 but it seems somebody with write perms will also need to approve. Thanks!

**Review by sarabala1979 — APPROVED** [review]

**Comment by robertkotcher** [comment]
@sarabala1979 seems as if somebody else will also have to click the merge button. when does that happen? (thx, just trying to learn the process here :) )

**Comment by juliev0** [comment]
> @sarabala1979 seems as if somebody else will also have to click the merge button. when does that happen? (thx, just trying to learn the process here :) )

Hey Robert. Sorry for the delay. Unfortunately, some of these PRs aren't getting immediate attention. I'll bring it up to him tomorrow and hopefully we can just merge it.

**Comment by robertkotcher** [comment]
> > @sarabala1979 seems as if somebody else will also have to click the merge button. when does that happen? (thx, just trying to learn the process here :) )
> 
> Hey Robert. Sorry for the delay. Unfortunately, some of these PRs aren't getting immediate attention. I'll bring it up to him tomorrow and hopefully we can just merge it.

No worries :) just trying to learn the process as I'm hoping to contribute with more meaningful PRs in the future. Thanks @juliev0

**Comment by sarabala1979** [comment]
@robertkotcher sorry for the delay

**Comment by juliev0** [comment]
Thanks, @sarabala1979!



> > > @sarabala1979 seems as if somebody else will also have to click the merge button. when does that happen? (thx, just trying to learn the process here :) )
> > 
> > 
> > Hey Robert. Sorry for the delay. Unfortunately, some of these PRs aren't getting immediate attention. I'll bring it up to him tomorrow and hopefully we can just merge it.
> 
> No worries :) just trying to learn the process as I'm hoping to contribute with more meaningful PRs in the future. Thanks @juliev0

Great @robertkotcher!

Thanks @sarabala1979 !

**Pull request merged**
