### PR TITLE
docs(auth): add link to FAQ on invalid token error

### LINKED ISSUE #5832: link to SSO docs when login fails: "token not valid for running mode"
Many users are confused by this error. This means they have not configured `--auth-mode` correctly.

We could enhance this error message with more help.

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- link was requested by Alex, fixes #5832

- also shorten the error message to "token not valid" as, in my experience at least, "for running mode" actually significantly increased confusion (c.f. https://github.com/argoproj/argo-workflows/issues/4991#issuecomment-1466465686)
  - everyone on my teams thought that it meant we misconfigured our auth or that only one mode could be used at a time - but actually, we were just missing the `"Bearer "` prefix for our token

- my comment about the `"Bearer "` prefix (https://github.com/argoproj/argo-workflows/issues/4991#issuecomment-1466465686) got a few upvotes, so thought this would be worth documenting as well

### Modifications

- add a link to the auth error message in `gatekeeper.go` when the token is invalid
  -  shorten the error message as well, per above motivation

- add the `"Bearer "` prefix as another common reason for this error in the FAQ

### Verification

Ran `make docs`

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
docs build need to be fixed

**Comment by agilgur5** [comment]
hmm let me figure out which part broke -- looks like it may be detecting the `Bearer ` reference as a false positive token match. from [the logs](https://github.com/argoproj/argo-workflows/actions/runs/5479062739/jobs/9980381761?pr=11300):

```diff
-If you're using `--auth-mode=client`, make sure you have `*** in front of the token, as mentioned in [Access Token](access-token.md#token-creation).
+If you're using `--auth-mode=client`, make sure you have `Bearer` in front of the token, as mentioned in [Access Token](access-token.md#token-creation).
```
it's also missing the intentional space after `Bearer` in the docs as well 🤔

**Comment by agilgur5** [comment]
ah okay, looks like removing the intentional space in front of `Bearer ` was the change, and then GitHub Actions's log is redacting it as a false positive.

**Comment by agilgur5** [comment]
@terrytangyuan error should be fixed now

Seems like `markdownlint` has no line ignore functionality unfortunately (https://github.com/markdownlint/markdownlint/issues/16), so just removed the intentional space

**Pull request merged**
