### PR TITLE
fix: parse exit code when Outputs is not populated

### PR DESCRIPTION
**Pull request by tooptoop4**
Relates to https://github.com/argoproj/argo-workflows/issues/12572#issuecomment-2162093707
and https://github.com/argoproj/argo-workflows/blame/465c7b6d6abd06a36165955d7fd01d9db2b6a2d4/workflow/controller/operator.go#L1621
Seems more of a workaround than addressing real root cause

### CODE REVIEW

**Comment by agilgur5** [comment]
Not sure why you filed a duplicate of #13180... It is once again missing DCO as well

**Comment by tooptoop4** [comment]
so after running this for a while it seems to never extract an exit code, but the extra debug logs are handy. whenever exit is -1 which is most of the time, message is empty 98% of the time or something like "lastRetry.duration:57.383139809 lastRetry.exitCode:-1 lastRetry.message:child 'redact-1335299960' failed lastRetry.status:Failed retries:1"          seems there is some broader issue of why it is not finding the right message/exitcode

**Comment by jswxstw** [comment]
I don't understand why we need to extract the exit code from the message.
Under what circumstances would the exit code be nil but appear in the message?

**Comment by tooptoop4** [comment]
from above tests it is useless, but these debug logs did help uncover steps referencing a template defined in the same yaml are a reliable reproduction of exitcode not being set, maybe i should make issue for that

**Comment by tooptoop4** [comment]
this PR did not solve any issue but it helped to investigate exactly what the root cause is, which is now being tracked in https://github.com/argoproj/argo-workflows/issues/13297

**Pull request closed without merging**
