### PR TITLE
fix: add gh ecdsa and ed25519 to known hosts

### PR DESCRIPTION
**Pull request by robherley**
Here's the doc page with new keys:
- https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

Here's the blog post detailing the changes:
- https://github.blog/2021-09-01-improving-git-protocol-security-github/

Signed-off-by: Rob Herley <robherley@github.com>

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by robherley** [comment]
👋 @terrytangyuan can you [approval the workflow to run](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)?

**Review by gandelman-a — APPROVED** [review]
This is exactly what we updated on our local `argoexec `image to fix the github key issue.

**Review by kennytrytek-wf — APPROVED** [review]
Confirmed these changes function in our Argo instance. Can this get moved out of draft? It's a blocker for systems that rely on being able to pull artifacts from GitHub.

**Review by razvantudorica-gl — APPROVED** [review]

**Comment by alexec** [comment]
Does this need to got into v3.2.4?

**Pull request merged**
