### PR TITLE
feat: Allow remove of PVC protection finalizer. Fixes #6629

### LINKED ISSUE #6629: Removing PVC finalizer to let it be terminated
## Summary 

What happened/what you expected to happen?
When Argo deletes a PVC at the end of the run, it stays as "Terminated" until the Workflow object is deleted.
I'd expect it to terminate it completely to save space.
It is caused by a finalizer 'kubernetes.io/pvc-protection' protecting the PVC from being terminated and it was discussed here #3095

Note: If the PVC is deleted, while resubmitting works, retry does not. So maybe deleting it should be optional when failed with configuration but I don't think there is any problem doing it for completed successfully workflows.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
OpenShift 4.x (One of latest ones, 4.5 I think)

What version of Argo Workflows are you running? 
3.1.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary
Emissary

Did this work in a previous version? I.e. is it a regression?
I don't think it ever worked.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Don't bother creating a PR until you've done this:

* [x] Run `make pre-commit -B` to fix codegen, lint, and commit message problems.

Create your PR as a draft.

* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it
  does not need to pass.
* Once required tests have passed, you can make it "Ready for review".
* Say how how you tested your changes. If you changed the UI, attach screenshots.

Tips:

* If changes were requested, and you've made them, then dismiss the review to get it looked at again.
* Add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md) if you like.
* You can ask for help!

### CODE REVIEW

**Comment by naor2013** [comment]
Thanks for implementing this feature! It will really help us maintain many workflows with less manual work.

I have a question, will your implementation still work if that environment variable will be set when the finalizer does not exist?
Our problem is that we use Argo Controllers on both new and old versions of k8s (those versions are not officially supported by Argo but they still work and we don't control the k8s versions). On old versions of k8s this finalizer doesn't exist and we hope to just automatically add this environment variable in all of our workflows without knowing what cluster it will be deployed on.

**Comment by alexec** [comment]
It won't matter. If the finaliser is not added, it will not be removed.

**Review by sarabala1979 — APPROVED** [review]

**Comment by naor2013** [comment]
Hi @alexec 
Is this PR a part of version 3.2.5? I don't see it in the changelog.

**Comment by alexec** [comment]
No. We only back port `fix:` by default.

**Pull request merged**
