### PR TITLE
chore!: remove legacy `patch` `pods` fallback

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- the fallback is old and insecure, and the error confuses users as it's not mentioned in the docs (as it's legacy and a fallback)
  - e.g. #12783 and also frequently on Slack. See #13041 for more such examples of confusion
- it's also tech debt that we have to write code around specifically right now
- it's no longer needed and hasn't been the main RBAC in a few versions, so remove it in the next breaking minor release

### Modifications

- remove the Executor code that patches pods
- remove the operator code that reads the patched annotations

### Verification

Tests pass

### CODE REVIEW

**Comment by agilgur5** [comment]
@Garett-MacGowan would you be interested in taking over this PR? This seems to need more refactoring than I anticipated and I know you've worked with some of these pod annotations before

**Comment by Garett-MacGowan** [comment]
Hey! Sorry for the late response, I've been swamped. I can try and take a look at this some time next week.

**Comment by Garett-MacGowan** [comment]
Ran out of time this week. Haven't forgotten about this.

**Comment by agilgur5** [comment]
Superseded by #13100

**Pull request closed without merging**
