### PR TITLE
fix: add HTTP genre and sort

### PR DESCRIPTION
**Pull request by rwong2888**
Fix https://github.com/argoproj/argo-workflows/issues/6794

### CODE REVIEW

**Comment by alexec** [comment]
Thank you. Were you able to test this? If so, could you share a screenshot?

**Comment by rwong2888** [comment]
@alexec I'll set up locally and test when I get a chance.
https://argoproj.github.io/argo-workflows/running-locally/

**Comment by sarabala1979** [comment]
@rwong2888 Can you fix the DCO and semantics?

**Comment by rwong2888** [comment]
Not following. Can you elaborate @sarabala1979 ?

**Comment by sarabala1979** [comment]
@rwong2888 Can you sign in DCO?

**Comment by alexec** [comment]
Hi, you have two failing checks:

image

Click on "Details" to fine out how to fix them. Should only take 5m.

**Review by whynowy — DISMISSED** [review]
DCO please.

**Comment by rwong2888** [comment]
Thank you. Am new to this. Added DCO @sarabala1979 , @alexec , @whynowy

I think @alexec fixed the semantics with the title change to `fix:`

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
> Semantic Pull Request — PR has only one non-merge commit and it's not semantic; add another commit before squashing

**Comment by rwong2888** [comment]
A little after the fact and it took me a while to set up, but here is a screenshot @alexec !

image

**Pull request merged**
