### PR TITLE
refactor(tests): `if assert.*` -> `require.*`. Fixes #13465

### LINKED ISSUE #13465: tests: change `if assert` to `require` in remaining places
As suggested by @agilgur5:

Implement remaining `if assert.*` -> `require.*` changes as mentioned in [#13401 (comment)](https://github.com/argoproj/argo-workflows/pull/13401#discussion_r1696246571) etc

### PR DESCRIPTION
**Pull request by djanjic**
Fixes #13465 

### Motivation
Reduce unneeded nesting by changing `if assert.*` to `require.*`.

### Modifications
Updated tests where `if assert.*` is used to `require.*`

### Verification
Tests

### CODE REVIEW

**Review by Joibel — CHANGES_REQUESTED** [review]
Thanks for tackling this.

There's a missing negative case [here](https://github.com/djanjic/argo-workflows/blob/5d979a22f19382eece7ca0fa2b5825482620f26d/pkg/apis/workflow/v1alpha1/workflow_types_test.go#L897) that should be converted.

Also several in [context_test](https://github.com/djanjic/argo-workflows/blob/5d979a22f19382eece7ca0fa2b5825482620f26d/workflow/templateresolution/context_test.go#L194) where
```
	if !assert.True(t, ok) {
		t.Fatal("tmplBase is not a WorkflowTemplate")
	}
```
could be converted to
```
	require.True(t, ok, "tmplBase is not a WorkflowTemplate")
```

**Review by Joibel — APPROVED** [review]
LGTM, thanks for the contribution. I'll leave this for a day for @agilgur5 to look at as it was his idea.

**Comment by agilgur5** [comment]
> There's a missing negative case

nice catch, I totally forgot about the negative cases!

> I'll leave this for a day for @agilgur5 to look at as it was his idea.

I've gone through about half of it, feel free to merge if I don't get through the rest soon

**Review by agilgur5 — APPROVED** [review]
Nice work! I appreciate the attention to detail in adding new lines in a few places to aid readability where there is no longer indentation 🙂 

Also feel free to take a look at more [`good first issue`](https://github.com/argoproj/argo-workflows/labels/good%20first%20issue) and [`solution/suggested`](https://github.com/argoproj/argo-workflows/labels/solution%2Fsuggested) issues (if it's only the latter, it may be less straightforward than a `good first issue`). [Seems like](https://github.com/argoproj/argo-workflows/issues?q=label%3Asolution%2Fsuggested+assignee%3Adjanjic+is%3Aopen+) you've already taken a next one already though, great!

**Pull request merged**
