### PR TITLE
fix: add omitted children to the dag Fixes #9852

### LINKED ISSUE #9852: A step that depends on an omitted step is invisible in the DAG
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

In this simple workflow, there are three sequential steps:

- The first step always runs successfully.
- The second step only runs if the first step fails. So in this case, it will always be omitted.
- The third step runs if the second step fails. So in this case, it will always run.

This hypothetical case presents a common pattern for running extra logic to handle failures. 

The 3rd step is not displayed as part of the DAG in the UI. See below image:

image

Nevertheless, step3 runs successfully and you can see it in the "timeline" view:

image

I would have expected to see the 3rd step in the DAG view with it connected to the 2nd step.

Finally, I am very happy to contribute with a solution, however, I may need a bit of hand holding as I'm quite new to Argo & Go. 😄  I will create a [mentor request](https://argoproj.github.io/argo-workflows/mentoring/) shortly.

### Version

latest

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
kind: Workflow
metadata:
  generateName: hidden-step-example-
spec:
  entrypoint: hidden-step-example
  templates:
  - name: hidden-step-example
    dag:
      tasks:
      - name: step1
        template: hello-world-template
        arguments:
          parameters:
          - name: message
            value: 'step1 runs fine'
      - name: step2
        template: hello-world-template
        arguments:
          parameters:
          - name: message
            value: 'step2 is omitted, so you shouldn''t see this message'
        depends: step1.Failed
      - name: step3
        template: hello-world-template
        arguments:
          parameters:
            - name: message
              value: 'step3 runs but you won''t see it on the DAG'
        depends: step2.Omitted
  - name: hello-world-template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: [ "{{inputs.parameters.message}}" ]
    inputs:
      parameters:
        - name: message
```

### Logs from the workflow controller

```
time="2022-10-17T15:11:36.099Z" level=info msg="Processing workflow" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.102Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.102Z" level=info msg="DAG node hidden-step-example-q7m82 initialized Running" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.102Z" level=info msg="All of node hidden-step-example-q7m82.step1 dependencies [] completed" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.102Z" level=info msg="Pod node hidden-step-example-q7m82-3430015642 initialized Pending" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.108Z" level=info msg="Created pod: hidden-step-example-q7m82.step1 (hidden-step-example-q7m82-hello-world-template-3430015642)" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.108Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.108Z" level=info msg=reconcileAgentPod namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:36.113Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=22365 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="Processing workflow" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=1 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="task-result changed" namespace=argo nodeID=hidden-step-example-q7m82-3430015642 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=hidden-step-example-q7m82-3430015642 old.message= old.phase=Pending old.progress=0/1 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="Skipped node hidden-step-example-q7m82-3413238023 initialized Omitted (message: omitted: depends condition not met)" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="All of node hidden-step-example-q7m82.step3 dependencies [step2] completed" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.110Z" level=info msg="Pod node hidden-step-example-q7m82-3396460404 initialized Pending" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.115Z" level=info msg="Created pod: hidden-step-example-q7m82.step3 (hidden-step-example-q7m82-hello-world-template-3396460404)" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.115Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.115Z" level=info msg=reconcileAgentPod namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.121Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=22395 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:46.127Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/hidden-step-example-q7m82-hello-world-template-3430015642/labelPodCompleted
time="2022-10-17T15:11:56.117Z" level=info msg="Processing workflow" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.117Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=2 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.118Z" level=info msg="task-result changed" namespace=argo nodeID=hidden-step-example-q7m82-3396460404 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.118Z" level=info msg="node changed" namespace=argo new.message= new.phase=Succeeded new.progress=0/1 nodeID=hidden-step-example-q7m82-3396460404 old.message= old.phase=Pending old.progress=0/1 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="Outbound nodes of hidden-step-example-q7m82 set to [hidden-step-example-q7m82-3396460404]" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="node hidden-step-example-q7m82 phase Running -> Succeeded" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="node hidden-step-example-q7m82 finished: 2022-10-17 15:11:56.119435589 +0000 UTC" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="Checking daemoned children of hidden-step-example-q7m82" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="TaskSet Reconciliation" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg=reconcileAgentPod namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="Marking workflow completed" namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.119Z" level=info msg="Checking daemoned children of " namespace=argo workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.125Z" level=info msg="cleaning up pod" action=deletePod key=argo/hidden-step-example-q7m82-1340600742-agent/deletePod
time="2022-10-17T15:11:56.130Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=22427 workflow=hidden-step-example-q7m82
time="2022-10-17T15:11:56.153Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/hidden-step-example-q7m82-hello-world-template-3396460404/labelPodCompleted
```

### Logs from in your workflow's wait container

```
time="2022-10-17T15:11:51.975Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: hidden-step-example-q7m82/hidden-step-example-q7m82-hello-world-template-3396460404/main.log"
time="2022-10-17T15:11:51.975Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2022-10-17T15:11:51.976Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=hidden-step-example-q7m82/hidden-step-example-q7m82-hello-world-template-3396460404/main.log path=/tmp/argo/outputs/logs/main.log
time="2022-10-17T15:11:51.982Z" level=info msg="Save artifact" artifactName=main-logs duration=6.405417ms error="<nil>" key=hidden-step-example-q7m82/hidden-step-example-q7m82-hello-world-template-3396460404/main.log
time="2022-10-17T15:11:51.982Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2022-10-17T15:11:51.982Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2022-10-17T15:11:51.987Z" level=info msg="Create workflowtaskresults 201"
time="2022-10-17T15:11:51.988Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-17T15:11:51.989Z" level=info msg="Deadline monitor stopped"
time="2022-10-17T15:11:51.989Z" level=info msg="Alloc=7408 TotalAlloc=12682 Sys=18898 NumGC=3 Goroutines=7"
time="2022-10-17T15:11:41.539Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: hidden-step-example-q7m82/hidden-step-example-q7m82-hello-world-template-3430015642/main.log"
time="2022-10-17T15:11:41.539Z" level=info msg="Creating minio client using static credentials" endpoint="minio:9000"
time="2022-10-17T15:11:41.539Z" level=info msg="Saving file to s3" bucket=my-bucket endpoint="minio:9000" key=hidden-step-example-q7m82/hidden-step-example-q7m82-hello-world-template-3430015642/main.log path=/tmp/argo/outputs/logs/main.log
time="2022-10-17T15:11:41.550Z" level=info msg="Save artifact" artifactName=main-logs duration=11.004709ms error="<nil>" key=hidden-step-example-q7m82/hidden-step-example-q7m82-hello-world-template-3430015642/main.log
time="2022-10-17T15:11:41.550Z" level=info msg="not deleting local artifact" localArtPath=/tmp/argo/outputs/logs/main.log
time="2022-10-17T15:11:41.550Z" level=info msg="Successfully saved file: /tmp/argo/outputs/logs/main.log"
time="2022-10-17T15:11:41.558Z" level=info msg="Create workflowtaskresults 201"
time="2022-10-17T15:11:41.559Z" level=info msg="Deadline monitor stopped"
time="2022-10-17T15:11:41.559Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-10-17T15:11:41.559Z" level=info msg="Alloc=6849 TotalAlloc=12657 Sys=18898 NumGC=4 Goroutines=7"
```

### PR DESCRIPTION
**Pull request by isubasinghe**
Signed-off-by: Isitha Subasinghe <isitha@pipekit.io>

Fixes #9852

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [x] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [x] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [x] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### CODE REVIEW

**Review by tczhao — COMMENTED** [review]
The original line was introduced in https://github.com/argoproj/argo-workflows/pull/4109
Did you test the change with exit handler example?
https://github.com/argoproj/argo-workflows/blob/master/examples/exit-handlers.yaml

**Comment by isubasinghe** [comment]
@tczhao Yes it works here is a picture:
image

I think perhaps the author misunderstood OMITTED To mean "not be displayed"

**Review by tczhao — APPROVED** [review]
lgtm

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
@sarabala1979 @alexec Any concerns displaying the omitted nodes?

**Comment by alexec** [comment]
I'm not sure how this work, because it hides omitted nodes?

**Comment by isubasinghe** [comment]
> I'm not sure how this work, because it hides omitted nodes?

@alexec The traverse function was used to traverse the graph and discover nodes to display. For some reason, nodes of type OMITTED were not being traversed. All this does is make OMITTED traversable. This is a pretty safe change as a result imo.

**Comment by caelan-io** [comment]
@sarabala1979 can we get your approval on this one to close #9852?

**Review by JPZ13 — APPROVED** [review]

**Pull request merged**
