### PR TITLE
refactor(ui): optimize Link functionality

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

- Optimize the `links` module and its usage a bit
- Simplify code a bit by reducing nesting
- Fix some JS conventions etc

Stumbled upon this while investigating #11741 and thought it could use some improvements

### Modifications

- move static functions outside of the component
  - this way they are not created every time the component is and hence use less memory etc
- use named `function`s instead of `const`s assigned to anonymous functions
  - this makes tracing a bit easier and source maps a bit clearer
  - (also technically a memory improvement as well)
- both of these also reduce nesting

- re-use `openLinkWithKey` in `WorkflowDetails` instead of having duplicate code
  - rename to `openLinkWithKey` so that it doesn't overlap with `openLink` and to be a bit more specific
  - (also a very tiny memory improvement)

- remove redundant `formatURL` function

- use lowercase "p" in `processURL`
  - JS convention that only classes are capitalized (or components in React, which used to always be classes)
    - I imagine this might have been capitalized b/c Go uses capitals for exports?

- be more specific with `urlExpression` as the argument since it is not necessarily a raw URL and that is why it needs "processing"

### Verification

Stylistic and performance changes, but no usage changes (minor semantic differences that improve tracing, memory, etc as mentioned above, but do not change usage).

### CODE REVIEW

**Review by isubasinghe — APPROVED** [review]
Could totally be my lack of frontend knowledge, but I didn't quite understand the function name for `openLinkWithKey` here, I assumed this was more my fault and approved.

**Comment by agilgur5** [comment]
> I didn't quite understand the function name for `openLinkWithKey` here

I wrote this a few weeks ago, but it's quite literal, since it's when clicked with `ctrlKey` or `metaKey` (i.e. Ctrl+Click or Middle Click) to open in a new tab. "Key" as in with one of those two keys (or without)

**Review by terrytangyuan — COMMENTED** [review]
This doesn't seem to fix https://github.com/argoproj/argo-workflows/issues/11741?

**Review by terrytangyuan — APPROVED** [review]

**Comment by agilgur5** [comment]
poop, this had a one-line semi-colon conflict with #11882 😭 . mentioned [on Slack](https://cloud-native.slack.com/archives/C0510EUH90V/p1695705273908319?thread_ts=1694644337.627309&cid=C0510EUH90V) that I tried pretty hard to avoid a conflict on this old PR but missed a single character

**Pull request merged**
