### PR TITLE
fix: Modify the client in  EventStreamReader  supporting TLS.

### PR DESCRIPTION
**Pull request by neWs1587**
Tips:

* Maybe add you organization to [USERS.md](https://github.com/argoproj/argo-workflows/blob/master/USERS.md).
* Your PR needs to pass the required checks before it can be approved. If the check is not required (e.g. E2E tests) it does not need to pass
* Sign-off your commits to pass the DCO check: `git commit --signoff`.
* Run `make pre-commit -B` to fix codegen or lint problems. 
* Say how how you tested your changes. If you changed the UI, attach screenshots.
* If changes were requested, and you've made them, then dismis the review to get it looked at again.
* You can ask for help!

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
@neWs1587 can you please signoff your commits so this passed the DCO check?

How to:

https://github.com/argoproj/argo-workflows/pull/6803/checks?check_run_id=3712922911

**Review by alexec — CHANGES_REQUESTED** [review]
DCO needs correcting.

**Comment by NikeNano** [comment]
I think this handled the same changes ar: https://github.com/argoproj/argo-workflows/pull/6800/files

**Comment by alexec** [comment]
This PR is a dupe. First time this has happened I think.

**Pull request closed without merging**
