### PR TITLE
fix: fix iam permissions to retrieve logs from aws s3

### PR DESCRIPTION
**Pull request by agido-heppe**
Signed-off-by: Lukas Heppe <lukas.heppe@agido.com>

Fixes #TODO

Please do not open a pull request until you have checked ALL of these:

* [x] Create the PR as draft .
* [ ] Run `make pre-commit -B` to fix codegen and lint problems.
* [x] Sign-off your commits (otherwise the DCO check will fail).
* [x] Use [a conventional commit message](https://www.conventionalcommits.org/en/v1.0.0/) (otherwise the commit message check will fail).
* [ ] "Fixes #" is in both the PR title (for release notes) and this description (to automatically link and close the issue).
* [x] Add unit or e2e tests. Say how you tested your changes. If you changed the UI, attach screenshots.
* [x] Github checks are green.
* [ ] Once required tests have passed, mark your PR "Ready for review".

If changes were requested, and you've made them, dismiss the review to get it reviewed again.

### Description

When using the IAM policy provided in the docs I couldn't view the logs via UI. By allowing the `ListBucket` Policy on the bucket instead of the objects within, I was able to retrieve those. 

The prinicple is also described in the AWS Blog post https://aws.amazon.com/de/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
What's the difference?

**Comment by agido-heppe** [comment]
It's the same problem as in the SO post below. You are allowed to perform actions on the resources (objects) within the bucket (marked by the wildcard *), but you are not allowed to list the bucket itself. 

If you want to access the logs of some worklfow via UI, the S3 client seems to try to perform a "ListBucket" operation, but it is not allowed to do so. Therefore, this policy explicitly whitelists this action. I will try to find the respective line later.

https://stackoverflow.com/questions/38774798/accessdenied-for-listobjects-for-s3-bucket-when-permissions-are-s3

**Review by juliev0 — APPROVED** [review]
Thank you for helping to figure out what the right policy settings should be! What you've written makes sense to me.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Thanks for clarifying!

**Comment by agido-heppe** [comment]
You are welcome! Thank you providing such nice projects :+1:

**Pull request merged**
